<?php
$title = 'Administración de Legajos';
?>
<h1 class="page-header" style="padding-top:20px"><?php echo $this->escapeHtml($title); ?></h1>
<?php
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
            &times;
            </button>
        <ul><li>')
        ->setMessageSeparatorString('</li><li>')
        ->setMessageCloseString('</li></ul></div>');

echo $flash->render('error', array('alert', 'alert-dismissable', 'alert-danger', 'flashAlert'));
echo $flash->render('info', array('alert', 'alert-dismissable', 'alert-info', 'flashAlert'));
echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning', 'flashAlert'));
echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success', 'flashAlert'));
?>

<div class="alert alert-warning" id="diagAlert">
    <a href="#" class="close" data-dismiss="alert">&times;</a>
    <strong><span class="dataAlert"></span></strong>
</div>

<br>
<div class="content">
    <div class="row">
        <div class="col-xs-6 col-md-4">
            <div class="btn-group">
                <button type="button" class="btn btn-primary btn-lg" id="btnAddLegajos">Alta</button>
                <button type="button" class="btn btn-primary btn-lg" id="btnDelLegajos" style="display: none;">Baja</button>
                <button type="button" class="btn btn-primary btn-lg" id="btnEditLegajos">Modificación</button>
            </div>
            <br>
            <div id="jqGridLegajos" style="padding-top:10px;">
                <table id="gridLegajos"></table>
                <div id="pagerLegajos"></div>
            </div>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-8">
            <div id="tabsLegajos">
                <ul>
                    <li><a href="#tabsLegajoDesc">Legajo</a></li>
                    <li><a href="#tabsFoto">Foto</a></li>
                    <li><a href="#tabsFamiliares">Familiares</a></li>
                    <li><a href="#tabsLiquidaciones">Liquidaciones</a></li>
                </ul>
                <div id="tabsLegajoDesc">
                    <div id="tab-add-edit-Legajos" class="container-fluid">
                        <div class="row">
                            <div class="col-xs-6 col-sm-6">
                                <div class="row">
                                    <div class="form-group form-group-sm">
                                        <label class="control-label small" for="input-vista-tab-legajos">Vista seleccionada:</label>
                                    </div>
                                </div>
                                <div class="row">
                                    <form class="form-inline" role="form">
                                        <div class="form-group form-group-sm">
                                            <select class="form-control" id="select-vista-tab-legajos">
                                                <option value="">Seleccione un legajo</option>
                                            </select>
                                            <button type="button" class="btn btn-default btn-xs" id="btnRefreshVistasLegajos">
                                                <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>
                                            </button>
                                        </div>
                                    </form>
                                </div>
                                <div class="row">
                                    <div id="jqGridDatosPpdLegajo" style="padding-top:10px;">
                                        <table id="gridDatosPpdLegajo"></table>
                                        <div id="pagerDatosPpdLegajo"></div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-6 col-sm-1">
                                <div class="row"></div>
                                <div class="row"></div>
                                <div class="row">
                                    <div class="btn-group-vertical" role="group" style="padding-top: 150px; padding-left: 35px;">
                                        <button type="button" class="btn btn-info btn-xs" id="btnAddValProp">
                                            <span class="glyphicon glyphicon-circle-arrow-left" aria-hidden="true"></span>
                                        </button>
                                        <button type="button" class="btn btn-success btn-xs" id="btnSaveData">
                                            <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
                                        </button>
                                        <button type="button" class="btn btn-danger btn-xs" id="btnRestoreData">
                                            <span class="glyphicon glyphicon-remove-sign" aria-hidden="true"></span>
                                        </button>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-6 col-sm-5">
                                <div class="row">
                                    <div class="form-group form-group-sm">
                                        <label class="control-label small" for="input-vista-tab-legajos">Valores posibles:</label>
                                    </div>
                                </div>
                                <div class="row"></div>
                                <div class="row">
                                    <div id="jqGridDatosLegajosVal" style="padding-top:10px;">
                                        <table id="gridDatosLegajosVal"></table>
                                        <div id="pagerDatosLegajosVal"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <br>
                        <div class="alert alert-warning" id="diagAlertTab">
                            <a href="#" class="close" data-dismiss="alert">&times;</a>
                            <strong><span class="dataAlertTab"></span></strong>
                        </div>
                    </div>
                </div>
                <div id="tabsFoto">
                    <p></p>
                </div>
                <div id="tabsFamiliares">
                    <p></p>
                </div>
                <div id="tabsLiquidaciones">
                    <p></p>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    var oEdit = false;
    var lastSel;

    $(document).ready(function () {
        //Grids
        $("#gridLegajos").jqGrid({
            width: 100,
            height: 260,
            autowidth: true,
            rowNum: 1000,
            rownumbers: true,
            url: "<?php echo $this->url('legajos', array('action' => 'loadLegajosGrid')); ?>",
            datatype: 'json',
            mtype: 'POST',
            colNames: ["Id", "EmpresaId", "Legajo", "Apellido y Nombre", "Foto", "Inactivo"],
            colModel: [
                {name: 'id', index: 'id',
                    width: 10,
                    align: "center",
                    sortable: false,
                    sorttype: 'int',
                    hidden: true
                },
                {name: 'empresaId', index: 'empresaId',
                    width: 10,
                    align: "center",
                    sortable: true,
                    sorttype: 'int',
                    hidden: true
                },
                {name: 'legajo', index: 'legajo',
                    width: 7,
                    align: "center",
                    sortable: true,
                    sorttype: 'int',
                    search: true,
                    stype: 'text',
                    searchoptions: {clearSearch: true}
                },
                {name: 'apellido_y_nombre', index: 'apellido_y_nombre',
                    width: 30,
                    align: "center",
                    sortable: true,
                    sorttype: 'text',
                    search: true,
                    stype: 'text',
                    searchoptions: {clearSearch: true}
                },
                {name: 'foto', index: 'foto',
                    width: 10,
                    align: "center",
                    sortable: true,
                    sorttype: 'int',
                    hidden: true
                },
                {name: 'inactivo', index: 'inactivo',
                    width: 10,
                    align: "center",
                    sortable: true,
                    sorttype: 'text',
                    hidden: true
                }
            ],
            pager: "#pagerLegajos",
            sortname: "id",
            sortorder: "ASC",
            viewrecords: true,
            viewsortcols: [true, 'horizontal', true],
            gridview: true,
            hidegrid: false,
            ignoreCase: true,
            autoencode: true,
            forceFit: false,
            pgbuttons: false,
            pgtext: false,
            pginput: false,
            loadonce: true,
            editurl: "<?php echo $this->url('legajos', array('action' => 'editGridItem')); ?>",
            //caption: "Legajos",
            gridComplete: function () {
                var ids = $("#gridLegajos").jqGrid('getDataIDs');
                ids = ids.toString();
                ids = ids.split(",");

                for (var i = 0; i < ids.length; i++) {
                    var cl = ids[i];
                    var data = $("#gridLegajos").jqGrid('getRowData', ids[i]);
                    if (data['inactivo'].toUpperCase() == 'I') {
                        $("#gridLegajos").jqGrid('setRowData', cl, false, {color: '#000000', background: '#FFC285'});
                    }
                }
            },
            onSelectRow: function (id) {
                //$("#select-vista-tab-legajos").val("");
                deleteGrid("gridDatosPpdLegajo");
                deleteGrid("gridDatosLegajosVal");
                loadSelectView();
            }
        });
        $("#gridLegajos").navGrid("#pagerLegajos",
                {edit: false, add: false, del: false, search: false, refresh: false, view: false});
        $("#gridLegajos").navButtonAdd("#pagerLegajos", {
            caption: "Borrar filtros",
            title: "Borrar filtros",
            buttonicon: 'ui-icon-refresh',
            onClickButton: function () {
                $("#gridLegajos")[0].clearToolbar();
                gridReload('gridLegajos');
            }
        });
        $('#gridLegajos').jqGrid('filterToolbar', {stringResult: true, searchOnEnter: false, autoSearch: false, defaultSearch: 'cn', ignoreCase: true});

        $("#gridDatosPpdLegajo").jqGrid({
            width: 460,
            height: 175,
            shrinkToFit: true,
            forceFit: false,
            autowidth: true,
            //rowNum: 1000,
            rownumbers: true,
            datatype: "local",
            colNames: ["Id", "SL", "Dato", "Valor", "Contant", "PPId", "Tipo"],
            colModel: [
                {name: 'id', index: 'id',
                    width: 10,
                    align: "center",
                    sortable: false,
                    sorttype: 'int',
                    hidden: true
                },
                {name: 'solo_lectura', index: 'solo_lectura',
                    width: 5,
                    align: "center",
                    sortable: true,
                    sorttype: 'text',
                    search: true,
                    stype: 'select',
                    searchoptions: {value: ":;S:Si;N:o"}
                },
                {name: 'descripcion', index: 'descripcion',
                    width: 30,
                    align: "center",
                    sortable: true,
                    sorttype: 'text',
                    search: true,
                    stype: 'text',
                    searchoptions: {clearSearch: true}
                },
                {name: 'contenido', index: 'contenido',
                    width: 15,
                    align: "center",
                    sortable: true,
                    sorttype: 'text',
                    search: true,
                    stype: 'text',
                    searchoptions: {clearSearch: true}
                },
                {name: 'contant', index: 'contant',
                    width: 30,
                    align: "center",
                    sortable: true,
                    sorttype: 'text',
                    search: true,
                    stype: 'text',
                    searchoptions: {clearSearch: true},
                    hidden: true
                },
                {name: 'pp_id', index: 'pp_id',
                    width: 10,
                    align: "center",
                    sortable: false,
                    sorttype: 'int',
                    hidden: true
                },
                {name: 'tipo', index: 'tipo',
                    width: 10,
                    align: "center",
                    sortable: true,
                    sorttype: 'text',
                    search: true,
                    stype: 'select',
                    searchoptions: {value: ":;C:Caracter;N:Numero;F:Fecha"},
                    hidden: true
                }
            ],
            pager: "#pagerDatosPpdLegajo",
            sortname: "id",
            sortorder: "ASC",
            viewrecords: true,
            viewsortcols: [true, 'horizontal', true],
            gridview: true,
            hidegrid: false,
            ignoreCase: true,
            autoencode: true,
            pgbuttons: false,
            pgtext: false,
            pginput: false,
            loadonce: true,
            //caption: ""
            gridComplete: function () {
                var ids = $("#gridDatosPpdLegajo").jqGrid('getDataIDs');
                ids = ids.toString();
                ids = ids.split(",");

                for (var i = 0; i < ids.length; i++) {
                    var cl = ids[i];
                    var data = $("#gridDatosPpdLegajo").jqGrid('getRowData', ids[i]);
                    if (data['solo_lectura'] == 'S') {
                        $("#gridDatosPpdLegajo").jqGrid('setRowData', cl, false, {color: '#000000', background: '#FFC285'});
                    }
                }
            },
            onSelectRow: function (rowid) {
                var dataPpdLegajo = $("#gridDatosPpdLegajo").jqGrid('getRowData', rowid);
                loadGrid('gridDatosLegajosVal', dataPpdLegajo['id']);
                setSelectionGrid('gridDatosLegajosVal', dataPpdLegajo);
            }
        });
        $("#gridDatosPpdLegajo").navGrid("#pagerDatosPpdLegajo",
                {edit: false, add: false, del: false, search: false, refresh: false, view: false});
        $("#gridDatosPpdLegajo").navButtonAdd("#pagerDatosPpdLegajo", {
            caption: "Borrar filtros",
            title: "Borrar filtros",
            buttonicon: 'ui-icon-refresh',
            onClickButton: function () {
                $("#gridDatosPpdLegajo")[0].clearToolbar();
                //loadGrid('gridDatosPpdLegajo');
                //gridReload('gridDatosPpdLegajo');
            }
        });
        $('#gridDatosPpdLegajo').jqGrid('filterToolbar', {stringResult: true, searchOnEnter: false, autoSearch: false, defaultSearch: 'cn', ignoreCase: true});

        $("#gridDatosLegajosVal").jqGrid({
            width: 400,
            height: 205,
            shrinkToFit: true,
            forceFit: false,
            autowidth: true,
            //rowNum: 1000,
            rownumbers: true,
            datatype: 'local',
            colNames: ["Id", "PropiedadId", "Valor", "Significado"],
            colModel: [
                {name: 'id', index: 'id',
                    width: 10,
                    align: "center",
                    sortable: false,
                    sorttype: 'int',
                    hidden: true
                },
                {name: 'propiedadId', index: 'propiedadId',
                    width: 10,
                    align: "center",
                    sortable: true,
                    sorttype: 'int',
                    hidden: true
                },
                {name: 'valor_posible', index: 'valor_posible',
                    width: 10,
                    align: "center",
                    sortable: false,
                    sorttype: 'text',
                    search: true,
                    stype: 'text',
                    searchoptions: {clearSearch: true}
                },
                {name: 'significado', index: 'significado',
                    width: 30,
                    align: "center",
                    sortable: false,
                    sorttype: 'text',
                    search: true,
                    stype: 'text',
                    searchoptions: {clearSearch: true}
                }
            ],
            pager: "#pagerDatosLegajosVal",
            sortname: "id",
            sortorder: "ASC",
            viewrecords: true,
            viewsortcols: [true, 'horizontal', true],
            gridview: true,
            hidegrid: false,
            ignoreCase: true,
            autoencode: true,
            pgbuttons: false,
            pgtext: false,
            pginput: false,
            loadonce: true
                    //caption: ""
        });
        $("#gridDatosLegajosVal").navGrid("#pagerDatosLegajosVal",
                {edit: false, add: false, del: false, search: false, refresh: false, view: false});
        $("#gridDatosLegajosVal").navButtonAdd("#pagerDatosLegajosVal", {
            caption: "Borrar filtros",
            title: "Borrar filtros",
            buttonicon: 'ui-icon-refresh',
            onClickButton: function () {
                $("#gridDatosLegajosVal")[0].clearToolbar();
                //loadGrid('gridDatosLegajosVal');
                //gridReload('gridDatosLegajosVal');
            }
        });
        $('#gridDatosLegajosVal').jqGrid('filterToolbar', {stringResult: true, searchOnEnter: false, autoSearch: false, defaultSearch: 'cn', ignoreCase: true});

        //Tabs
        $("#tabsLegajos").tabs({
            heightStyle: "content"
        });

        //Buttons
        $("#btnAddLegajos").click(function () {
            openDiagLegajos("form-add-edit-Legajos", "add", "", "");
        });
        $("#btnDelLegajos").click(function () {
            var rowid = $("#gridLegajos").jqGrid('getGridParam', 'selrow');
            if (rowid != null) {
                $.ajax({
                    url: "<?php echo $this->url('legajos', array('action' => 'deleteGridItem')); ?>",
                    global: false,
                    type: "POST",
                    data: "id=" + rowid,
                    dataType: "json",
                    async: false,
                    success: function (msg) {
                        gridReload('gridLegajos');
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        alert(xhr.status + " " + thrownError);
                    }
                });
            }
            else {
                msgAlert("diagAlert", "dataAlert", "Por favor seleccione una fila.");
            }
        });
        $("#btnEditLegajos").click(function () {
            var rowid = $("#gridLegajos").jqGrid('getGridParam', 'selrow');
            if (rowid != null) {
                openDiagLegajos("form-add-edit-Legajos", "edit", "gridLegajos", rowid);
            }
            else {
                msgAlert("diagAlert", "dataAlert", "Por favor seleccione una fila.");
            }
        });
        $("#btnRefreshVistasLegajos").click(function () {
            loadSelectView();
        });

        //btnAddValProp
        $("#btnAddValProp").click(function () {
            var rowidLegajosVal = $("#gridDatosLegajosVal").jqGrid('getGridParam', 'selrow');
            if (rowidLegajosVal != null) {
                var rowidPpdLegajo = $("#gridDatosPpdLegajo").jqGrid('getGridParam', 'selrow');
                var dataRowPpdLegajo = $("#gridDatosPpdLegajo").jqGrid('getRowData', rowidPpdLegajo);
                if (dataRowPpdLegajo['solo_lectura'] != "S") {
                    var dataRowLegajosVal = $("#gridDatosLegajosVal").jqGrid('getRowData', rowidLegajosVal);
                    $('#gridDatosPpdLegajo').setCell(rowidPpdLegajo, 'contenido', dataRowLegajosVal['valor_posible']);
                }
                else {
                    msgAlert("diagAlertTab", "dataAlertTab", "Campo de solo lectura.");
                }
            }
            else {
                msgAlert("diagAlertTab", "dataAlertTab", "Por favor seleccione una fila.");
            }
        });
        //btnSaveData
        $("#btnSaveData").click(function () {
            var rowidLegajos = $("#gridLegajos").jqGrid('getGridParam', 'selrow');
            if (rowidLegajos != null) {
                var dataGridDatosPpdLegajo = new Array();// = $("#gridDatosPpdLegajo").jqGrid('getGridParam', 'data');
//            var dataGridDatosLegajosVal;// = $("#gridDatosLegajosVal").jqGrid('getGridParam', 'data');
                var ids = $("#gridDatosPpdLegajo").jqGrid('getDataIDs');
                ids = ids.toString();
                ids = ids.split(",");

                for (var i = 0; i < ids.length; i++) {
                    var data = $("#gridDatosPpdLegajo").jqGrid('getRowData', ids[i]);
                    data['objetoId'] = rowidLegajos;
                    $.ajax({
                        url: "<?php echo $this->url('legajos', array('action' => 'loadDataGrid')); ?>",
                        global: true,
                        type: "POST",
                        data: "id=" + data['id'],
                        dataType: "json",
                        async: false,
                        success: function (result) {
                            if (result.data.length > 0) {
                                var dataGridDatosLegajosVal = new Array();
                                for (var j = 0; j < result.data.length; j++) {
                                    var dataDatosLegajosVal = {
                                        "id": result.data[j][0],
                                        "propiedadId": result.data[j][1],
                                        "valor_posible": result.data[j][2],
                                        "significado": result.data[j][3]
                                    };
                                    dataGridDatosLegajosVal[j] = dataDatosLegajosVal;
                                }
                                data['dataGridDatosLegajosVal'] = dataGridDatosLegajosVal;
                            }
                        },
                        error: function (xhr, ajaxOptions, thrownError) {
                            alert(xhr.status + " " + thrownError);
                        }
                    });
                    dataGridDatosPpdLegajo[i] = data;
                }
                if (dataGridDatosPpdLegajo.length > 0) {
                    if (checkConsistency(dataGridDatosPpdLegajo)) {
                        $.ajax({
                            url: "<?php echo $this->url('legajos', array('action' => 'editGridItemVal')); ?>",
                            global: false,
                            type: "POST",
                            data: "data=" + JSON.stringify(dataGridDatosPpdLegajo),
                            dataType: "json",
                            async: false,
                            success: function (msg) {
//                            for (var i = 0; i < msg.data.length; i++) {
//                                    var data = $("#gridLegajos").jqGrid('getRowData', ids[i]);
//                                    if (data['legajo'].toLowerCase() == legajo.toLowerCase()) {
//                                        e++;
//                                        $('#gridDatosPpdLegajo').setCell(rowidPpdLegajo, 'contenido', dataRowLegajosVal['valor_posible']);
//                                    }
//                                }
                                var rowidLegajos = $("#gridLegajos").jqGrid('getGridParam', 'selrow');
                                if (rowidLegajos != null) {
                                    loadGrid('gridDatosPpdLegajo', rowidLegajos);
                                    deleteGrid('gridDatosLegajosVal');
                                    msgAlert("diagAlertTab", "dataAlertTab", "Datos guardados correctamente.");
                                }
                            },
                            error: function (xhr, ajaxOptions, thrownError) {
                                alert(xhr.status + " " + thrownError);
                            }
                        });
                    } else {
                        //msgAlert("diagAlertTab", "dataAlertTab", "Por favor seleccione una fila.");
                    }
                }
            }
        });
        //btnRestoreData
        $("#btnRestoreData").click(function () {
            var rowidLegajos = $("#gridLegajos").jqGrid('getGridParam', 'selrow');
            if (rowidLegajos != null) {
                var dataGridDatosPpdLegajo = $("#gridDatosPpdLegajo").jqGrid('getGridParam', 'data');
                for (var i = 0; i < dataGridDatosPpdLegajo.length; i++) {
                    var rowData = $('#gridDatosPpdLegajo').jqGrid('getRowData', i + 1);
                    rowData.contenido = dataGridDatosPpdLegajo[i]['contant'];
                    $('#gridDatosPpdLegajo').setRowData(i + 1, rowData);
                    //var contant = dataGridDatosPpdLegajo[i]['contant'];
                    //$('#gridDatosPpdLegajo').setCell(i + 1, 'contenido', contant, null, null, true);
                    //$('#gridDatosPpdLegajo').restoreRow(i+1);
                }
                //loadGrid('gridDatosPpdLegajo', rowidLegajos);
                deleteGrid('gridDatosLegajosVal');
            }
            else {
                //msgAlert("diagAlertTab", "dataAlertTab", "Por favor seleccione una fila.");
            }
        });

        //Dialog addLegajos
        $("#form-add-edit-Legajos").dialog({
            autoOpen: false,
            resizable: true,
            draggable: true,
            closeOnEscape: false,
            modal: true,
            width: 'auto', //1000, 
            height: 'auto', //500,
            maxWidth: 1200,
            //position: ['center',110] , //{ my: "center", at: "center", of: window }
            //fluid: true, //new option
            open: function (event, ui) {
                $(event.target).parent().css('position', 'fixed');
                $(event.target).parent().css('top', '110px');
                $(event.target).parent().css('left', '275px');
            },
            buttons: {
                'Aceptar': function () {
                    var legajo = $("#legajo-add-Legajos").val();
                    var apellidoYNombre = $("#apellidoYNombre-add-Legajos").val();

                    if (legajo != '' && apellidoYNombre != '') {
                        var ids = $("#gridLegajos").jqGrid('getDataIDs');
                        ids = ids.toString();
                        ids = ids.split(",");

                        var e = 0;
                        var rowid = "";

                        if (oEdit) {
                            rowid = $("#gridLegajos").jqGrid('getGridParam', 'selrow');
                            if (rowid != null) {
                                if (ids != "") {
                                    for (var i = 0; i < ids.length; i++) {
                                        var data = $("#gridLegajos").jqGrid('getRowData', ids[i]);
                                        if (data['id'] != rowid) {
                                            if (data['legajo'].toLowerCase() === legajo.toLowerCase()) {
                                                e++;
                                            }
                                        }
                                    }
                                }
                            } else {
                                msgAlert("diagAlert", "dataAlert", "Por favor seleccione una fila.");
                            }
                        } else {
                            if (ids != "") {
                                for (var i = 0; i < ids.length; i++) {
                                    var data = $("#gridLegajos").jqGrid('getRowData', ids[i]);
                                    if (data['legajo'].toLowerCase() === legajo.toLowerCase()) {
                                        e++;
                                    }
                                }
                            }
                        }
                        if (e == 0) {
                            var data = {
                                "id": rowid,
                                "legajo": legajo,
                                "apellido_y_nombre": apellidoYNombre
                            };
                            $.ajax({
                                url: "<?php echo $this->url('legajos', array('action' => 'editGridItem')); ?>",
                                global: false,
                                type: "POST",
                                data: "data=" + JSON.stringify(data),
                                dataType: "json",
                                async: false,
                                success: function (msg) {
                                    gridReload('gridLegajos');
                                    $("#form-add-edit-Legajos").dialog('close');
                                },
                                error: function (xhr, ajaxOptions, thrownError) {
                                    alert(xhr.status + " " + thrownError);
                                }
                            });
                        } else {
                            msgAlert("diagAlertModal", "dataAlertModal", "Ya existe un registro con esa combinacion.");
                        }
                    } else {
                        msgAlert("diagAlertModal", "dataAlertModal", "Ingrese valores a los campos.");
                    }
                },
                'Cancelar': function () {
                    clearDataLegajos();
                    $(this).dialog('close');
                }
            },
            close: function () {
                clearDataLegajos();
            }
        });

        //AlertManager
        $('#diagAlert').on('closed.bs.alert', function () {
            $('.dataAlert').html("");
        });
        $('#diagAlertModal').on('closed.bs.alert', function () {
            $('.dataAlertModal').html("");
        });
        $('#diagAlertTab').on('closed.bs.alert', function () {
            $('.dataAlertTab').html("");
        });

        //loadSelectView();
        $("#select-vista-tab-legajos").change(function () {
            //alert($(this).val());
            var rowid = $("#gridLegajos").jqGrid('getGridParam', 'selrow');
            if (rowid != null) {
                deleteGrid("gridDatosPpdLegajo");
                deleteGrid("gridDatosLegajosVal");
                loadGrid('gridDatosPpdLegajo', rowid);
            }
            else {
                msgAlert("diagAlertModal", "dataAlertModal", "Seleccione un legajo.");
            }
        });
    });

    // remove window resize namespace
    $(document).on("dialogclose", ".ui-dialog", function (event, ui) {
        $(window).off("resize.responsive");
    });

    function gridReload(gridName) {
        $("#" + gridName).setGridParam({datatype: 'json'})/*.setGridParam({rowNum: 1000})*/.trigger('reloadGrid');
    }

    function openDiagLegajos(diagName, op, grid, id) {
        clearDataLegajos();
        if (op == "edit") {
            var rowdata = $("#" + grid).getRowData(id);
            $('#legajo-add-Legajos').val(rowdata['legajo']);
            $('#apellidoYNombre-add-Legajos').val(rowdata['apellido_y_nombre']);
            $('#' + diagName).dialog("option", "title", "Editar registro");
            $('#' + diagName).dialog('open');
            $('#' + diagName).dialog('moveToTop');
            oEdit = true;
        } else {
            $('#' + diagName).dialog("option", "title", "Agregar registro");
            $('#' + diagName).dialog('open');
            $('#' + diagName).dialog('moveToTop');
            oEdit = false;
        }
    }

    function clearDataLegajos() {
        $('#legajo-add-Legajos').val("");
        $('#legajo-edit-Legajos').val("");
        $('#apellidoYNombre-add-Legajos').val("");
        $('#apellidoYNombre-edit-Legajos').val("");
    }

    function msgAlert(diagName, selectorName, msg) {
        $('#' + diagName).show();
        $('.' + selectorName).html(msg);
        setTimeout(function () {
            $('#' + diagName).hide("drop", {direction: "up"}, "slow");
            $('.' + selectorName).html("");
        }, 3000);
        return;
    }

    function loadGrid(gridName, rowid) {
        switch (gridName) {
            case 'gridDatosPpdLegajo':
                var data = {
                    "id": rowid,
                    "vistaLegajoSel": $('#select-vista-tab-legajos').val()
                };
                $.ajax({
                    url: "<?php echo $this->url('legajos', array('action' => 'loadPpdLegajoGrid')); ?>",
                    global: false,
                    type: "POST",
                    data: "data=" + JSON.stringify(data),
                    dataType: "json",
                    async: false,
                    success: function (result) {
                        deleteGrid('gridDatosPpdLegajo');
                        if (result.data.length > 0) {
                            for (var i = 0; i < result.data.length; i++) {
                                var dataLocal = {
                                    "id": result.data[i][0],
                                    "descripcion": result.data[i][1],
                                    "contenido": result.data[i][2],
                                    "contant": result.data[i][3],
                                    "pp_id": result.data[i][4],
                                    "solo_lectura": result.data[i][5],
                                    "tipo": result.data[i][6]
                                };
                                var ids = $("#gridDatosPpdLegajo").jqGrid('getDataIDs');
                                ids = ids.toString();

                                ids = ids.split(",");
                                if (ids.length > 0 && ids[0] != 'undefined' && ids[0] != "") {
                                    $("#gridDatosPpdLegajo").jqGrid('addRowData', ids.length + 1, dataLocal);
                                } else {
                                    $("#gridDatosPpdLegajo").jqGrid('addRowData', 1, dataLocal);
                                }
                            }
                        }
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        alert(xhr.status + " " + thrownError);
                    }
                });
                break;
            case 'gridDatosLegajosVal':
                $.ajax({
                    url: "<?php echo $this->url('legajos', array('action' => 'loadDataGrid')); ?>",
                    global: false,
                    type: "POST",
                    data: "id=" + rowid,
                    dataType: "json",
                    async: false,
                    success: function (result) {
                        deleteGrid('gridDatosLegajosVal');
                        if (result.data.length > 0) {
                            for (var i = 0; i < result.data.length; i++) {
                                var dataLocal = {
                                    "id": result.data[i][0],
                                    "propiedadId": result.data[i][1],
                                    "valor_posible": result.data[i][2],
                                    "significado": result.data[i][3]
                                };
                                var ids = $("#gridDatosLegajosVal").jqGrid('getDataIDs');
                                ids = ids.toString();

                                ids = ids.split(",");
                                if (ids.length > 0 && ids[0] != 'undefined' && ids[0] != "") {
                                    $("#gridDatosLegajosVal").jqGrid('addRowData', ids.length + 1, dataLocal);
                                } else {
                                    $("#gridDatosLegajosVal").jqGrid('addRowData', 1, dataLocal);
                                }
                            }
                        }
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        alert(xhr.status + " " + thrownError);
                    }
                });
                break;
        }
    }

    function deleteGrid(gridName) {
        var $table;
        $table = $('#' + gridName);

        var ids = $table.jqGrid('getDataIDs');
        ids = ids.toString();
        ids = ids.split(",");
        if (ids.length > 0) {
            for (var i = 0; i < ids.length; i++) {
                $table.delRowData(ids[i]);
            }
        }
        $table.clearGridData(true).trigger("reloadGrid");
    }

    function loadSelectView() {
        var rowid = $("#gridLegajos").jqGrid('getGridParam', 'selrow');

        if (rowid != null) {
            var list_target_id = 'select-vista-tab-legajos';
            $("#" + list_target_id).val("");
            $('#' + list_target_id).html('<option value="">Cargando vistas</option>');

            $.ajax({
                url: "<?php echo $this->url('legajos', array('action' => 'loadSelectView')); ?>",
                global: false,
                type: "POST",
                dataType: "json",
                async: false,
                success: function (result) {
                    $('#' + list_target_id).html("");
                    $.each(result.data, function (i, d) {
                        $('#' + list_target_id).append('<option value="' + i + '">' + d + '</option>');
                    });
                    $("#" + list_target_id).change();
                    //$('#' + list_target_id + " option:eq(0)").prop('selected', true);
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert(xhr.status + " " + thrownError);
                }
            });
        }
        else {
            msgAlert("diagAlertTab", "dataAlertTab", "Seleccione un legajo.");
        }
    }

    function setSelectionGrid(gridName, data) {
        var ids = $("#" + gridName).jqGrid('getDataIDs');
        ids = ids.toString();
        ids = ids.split(",");

        for (var i = 0; i < ids.length; i++) {
            var dataDatosLegajosVal = $("#" + gridName).jqGrid('getRowData', ids[i]);
            if (dataDatosLegajosVal['valor_posible'] == data['contenido']) {
                $("#" + gridName).jqGrid('setSelection', ids[i], false);
            }
        }
    }

    function validaFechaDDMMAAAA(fecha) {
        var dtCh = "/";
        var minYear = 1900;
        var maxYear = 2100;
        function isInteger(s) {
            var i;
            for (i = 0; i < s.length; i++) {
                var c = s.charAt(i);
                if (((c < "0") || (c > "9")))
                    return false;
            }
            return true;
        }
        function stripCharsInBag(s, bag) {
            var i;
            var returnString = "";
            for (i = 0; i < s.length; i++) {
                var c = s.charAt(i);
                if (bag.indexOf(c) == -1)
                    returnString += c;
            }
            return returnString;
        }
        function daysInFebruary(year) {
            return (((year % 4 == 0) && ((!(year % 100 == 0)) || (year % 400 == 0))) ? 29 : 28);
        }
        function DaysArray(n) {
            for (var i = 1; i <= n; i++) {
                this[i] = 31
                if (i == 4 || i == 6 || i == 9 || i == 11) {
                    this[i] = 30
                }
                if (i == 2) {
                    this[i] = 29
                }
            }
            return this;
        }
        function isDate(dtStr) {
            var daysInMonth = DaysArray(12);
            var pos1 = dtStr.indexOf(dtCh);
            var pos2 = dtStr.indexOf(dtCh, pos1 + 1);
            var strDay = dtStr.substring(0, pos1);
            var strMonth = dtStr.substring(pos1 + 1, pos2);
            var strYear = dtStr.substring(pos2 + 1);
            strYr = strYear;
            if (strDay.charAt(0) == "0" && strDay.length > 1)
                strDay = strDay.substring(1);
            if (strMonth.charAt(0) == "0" && strMonth.length > 1)
                strMonth = strMonth.substring(1);
            for (var i = 1; i <= 3; i++) {
                if (strYr.charAt(0) == "0" && strYr.length > 1)
                    strYr = strYr.substring(1);
            }
            month = parseInt(strMonth);
            day = parseInt(strDay);
            year = parseInt(strYr);
            if (pos1 == -1 || pos2 == -1) {
                return false;
            }
            if (strMonth.length < 1 || month < 1 || month > 12) {
                return false;
            }
            if (strDay.length < 1 || day < 1 || day > 31 || (month == 2 && day > daysInFebruary(year)) || day > daysInMonth[month]) {
                return false;
            }
            if (strYear.length != 4 || year == 0 || year < minYear || year > maxYear) {
                return false;
            }
            if (dtStr.indexOf(dtCh, pos2 + 1) != -1 || isInteger(stripCharsInBag(dtStr, dtCh)) == false) {
                return false;
            }
            return true;
        }
        if (isDate(fecha)) {
            return true;
        } else {
            return false;
        }
    }

    function checkConsistency(dataGrid1) {
        var status = false;

        for (var i = 0; i < dataGrid1.length; i++) {
            if (dataGrid1[i]['solo_lectura'].toUpperCase() == "S") {
                dataGrid1[i]['contenido'] = dataGrid1[i]['contant'];
            } else {
                if (dataGrid1[i]['contenido'] != dataGrid1[i]['contant']) {
                    if (dataGrid1[i]['contenido'] != "") {
                        if (dataGrid1[i]['tipo'].toUpperCase() == "F") {
                            if (!validaFechaDDMMAAAA(dataGrid1[i]['contenido'])) {
                                msgAlert("diagAlertTab", "dataAlertTab", "Formato de fecha erróneo.");
                            } else {
                                status = true;
                            }
                        }
                        if (dataGrid1[i]['tipo'].toUpperCase() == "N" && dataGrid1[i]['dataGridDatosLegajosVal'].length > 0) {
                            var valorEncontrado = 0;
                            for (var j = 0; j < dataGrid1[i]['dataGridDatosLegajosVal'].length; j++) {
                                if (dataGrid1[i]['contenido'].trim().toUpperCase() == dataGrid1[i]['dataGridDatosLegajosVal'][j]['valor_posible'].trim().toUpperCase()) {
                                    valorEncontrado++;
                                    status = true;
                                }
                            }
                            if (valorEncontrado == 0) {
                                msgAlert("diagAlertTab", "dataAlertTab", "No existe el valor posible.");
                            }
                        }
                        if (dataGrid1[i]['tipo'].toUpperCase() == "C" && dataGrid1[i]['dataGridDatosLegajosVal'].length > 0) {
                            var valorEncontrado = 0;
                            for (var j = 0; j < dataGrid1[i]['dataGridDatosLegajosVal'].length; j++) {
                                if (dataGrid1[i]['contenido'].trim().toUpperCase() == dataGrid1[i]['dataGridDatosLegajosVal'][j]['valor_posible'].trim().toUpperCase()) {
                                    valorEncontrado++;
                                    status = true;
                                }
                            }
                            if (valorEncontrado == 0) {
                                msgAlert("diagAlertTab", "dataAlertTab", "No existe el valor posible.");
                            }
                        }
                    }
                }
            }
        }
        return status;
    }

</script>

<!-- Dialogo form-add-edit-Legajos -->
<div id="form-add-edit-Legajos" class="container-fluid" title="" >
    <form class="form-horizontal" role="form">
        <div class="form-group">
            <label for="input-legajo-add-Legajos" class="col-sm-4 control-label">Legajo Nº:</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="legajo-add-Legajos" placeholder="">
            </div>
        </div>
        <div class="form-group">
            <label for="input-apellidoYNombre-add-Legajos" class="col-sm-4 control-label">Apellido y nombre:</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="apellidoYNombre-add-Legajos" placeholder="">
            </div>
        </div>
    </form>
    <div class="alert alert-warning" id="diagAlertModal">
        <a href="#" class="close" data-dismiss="alert">&times;</a>
        <strong><span class="dataAlertModal"></span></strong>
    </div>
</div>