<?php
$title = 'Administración de Legajos';
?>
<h1 class="page-header" style="padding-top:20px"><?php echo $this->escapeHtml($title); ?></h1>
<?php
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
            &times;
            </button>
        <ul><li>')
        ->setMessageSeparatorString('</li><li>')
        ->setMessageCloseString('</li></ul></div>');

echo $flash->render('error', array('alert', 'alert-dismissable', 'alert-danger', 'flashAlert'));
echo $flash->render('info', array('alert', 'alert-dismissable', 'alert-info', 'flashAlert'));
echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning', 'flashAlert'));
echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success', 'flashAlert'));
?>

<div class="alert alert-warning" id="diagAlert">
    <a href="#" class="close" data-dismiss="alert">&times;</a>
    <strong><span class="dataAlert"></span></strong>
</div>

<br>
<div class="content">
    <div class="row">
        <div class="col-xs-6 col-md-4">
            <div class="btn-group">
                <button type="button" class="btn btn-primary btn-lg" id="btnAddLegajos">Alta</button>
                <button type="button" class="btn btn-primary btn-lg" id="btnDelLegajos">Baja</button>
                <button type="button" class="btn btn-primary btn-lg" id="btnEditLegajos">Modificación</button>
            </div>
            <br>
            <div id="jqGridLegajos" style="padding-top:10px;">
                <table id="gridLegajos"></table>
                <div id="pagerLegajos"></div>
            </div>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-8">
            <div id="tabsLegajos">
                <ul>
                    <li><a href="#tabsLegajoDesc">Legajo</a></li>
                    <li><a href="#tabsFoto">Foto</a></li>
                    <li><a href="#tabsFamiliares">Familiares</a></li>
                    <li><a href="#tabsLiquidaciones">Liquidaciones</a></li>
                </ul>
                <div id="tabsLegajoDesc">
                    <div id="tab-add-edit-Legajos" class="container-fluid">
                        <div class="row">
                            <div class="col-xs-6 col-sm-6">
                                <div class="row">
                                    <div class="form-group form-group-sm">
                                        <label class="control-label small" for="input-vista-tab-legajos">Vista seleccionada:</label>
                                    </div>
                                </div>
                                <div class="row">
                                    <form class="form-inline" role="form">
                                        <div class="form-group form-group-sm">
                                            <select class="form-control" id="select-vista-tab-legajos"></select>
                                            <button type="button" class="btn btn-default btn-xs" id="btnRefreshVistasLegajos">
                                                <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span> Refrescar vistas
                                            </button>
                                        </div>
                                    </form>
                                </div>
                                <div class="row">
                                    <div id="jqGridDatosPpdLegajo" style="padding-top:10px;">
                                        <table id="gridDatosPpdLegajo"></table>
                                        <div id="pagerDatosPpdLegajo"></div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-6 col-sm-1">
                                <div class="row"></div>
                                <div class="row"></div>
                                <div class="row">
                                    <div class="btn-group-vertical" role="group" style="padding-top:70px;">
                                        <button type="button" class="btn btn-info btn-xs" id="btnAddAllData">
                                            <span class="glyphicon glyphicon-circle-arrow-left" aria-hidden="true"></span>
                                        </button>
                                        <button type="button" class="btn btn-success btn-xs" id="btnAddSingleData">
                                            <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span> Aplicar
                                        </button>
                                        <button type="button" class="btn btn-danger btn-xs" id="btnDelSingleData">
                                            <span class="glyphicon glyphicon-remove-sign" aria-hidden="true"></span>
                                        </button>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-6 col-sm-5">
                                <div class="row">
                                    <div class="form-group form-group-sm">
                                        <label class="control-label small" for="input-vista-tab-legajos">Valores posibles:</label>
                                    </div>
                                </div>
                                <div class="row"></div>
                                <div class="row">
                                    <div id="jqGridDatosLegajosVal" style="padding-top:10px;">
                                        <table id="gridDatosLegajosVal"></table>
                                        <div id="pagerDatosLegajosVal"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="alert alert-warning" id="diagAlertTab">
                            <a href="#" class="close" data-dismiss="alert">&times;</a>
                            <strong><span class="dataAlertTab"></span></strong>
                        </div>
                    </div>
                </div>
                <div id="tabsFoto">
                    <p></p>
                </div>
                <div id="tabsFamiliares">
                    <p></p>
                </div>
                <div id="tabsLiquidaciones">
                    <p></p>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    var oEdit = false;
    var lastSel;

    $(document).ready(function () {
        //Grids
        $("#gridLegajos").jqGrid({
            width: 100,
            height: 250,
            autowidth: true,
            rownumbers: true,
            url: "<?php echo $this->url('legajos', array('action' => 'loadLegajosGrid')); ?>",
            datatype: 'json',
            mtype: 'POST',
            colNames: ["Id", "EmpresaId", "Legajo", "Apellido y Nombre", "Foto"],
            colModel: [
                {name: 'id', index: 'id',
                    width: 10,
                    align: "center",
                    sortable: false,
                    sorttype: 'int',
                    hidden: true
                },
                {name: 'empresaId', index: 'empresaId',
                    width: 10,
                    align: "center",
                    sortable: true,
                    sorttype: 'int',
                    hidden: true
                },
                {name: 'legajo', index: 'legajo',
                    width: 10,
                    align: "center",
                    sortable: true,
                    sorttype: 'int',
                    search: true,
                    stype: 'text',
                    searchoptions: {clearSearch: true}
                },
                {name: 'apellido_y_nombre', index: 'apellido_y_nombre',
                    width: 30,
                    align: "center",
                    sortable: true,
                    sorttype: 'text',
                    search: true,
                    stype: 'text',
                    searchoptions: {clearSearch: true}
                },
                {name: 'foto', index: 'foto',
                    width: 10,
                    align: "center",
                    sortable: true,
                    sorttype: 'int',
                    hidden: true
                }
            ],
            pager: "#pagerLegajos",
            sortname: "id",
            sortorder: "ASC",
            viewrecords: true,
            viewsortcols: [true, 'horizontal', true],
            gridview: true,
            hidegrid: false,
            ignoreCase: true,
            autoencode: true,
            forceFit: false,
            pgbuttons: false,
            pgtext: false,
            pginput: false,
            loadonce: true,
            editurl: "<?php echo $this->url('legajos', array('action' => 'editGridItem')); ?>",
            //caption: "Legajos",
            gridComplete: function () {
                var ids = $("#gridLegajos").jqGrid('getDataIDs');
                ids = ids.toString();
                ids = ids.split(",");

                for (var i = 0; i < ids.length; i++) {
                    var cl = ids[i];
                    var data = $("#gridLegajos").jqGrid('getRowData', ids[i]);
                    if (data['legajo'] == '2') {
                        jQuery("#gridLegajos").jqGrid('setRowData', cl, false, {color: '#000000', background: '#FFC285'});
                    }
                }
            },
            onSelectRow: function (id) {
                $("#select-vista-tab-legajos").val("");
                deleteGrid("gridDatosPpdLegajo");
                deleteGrid("gridDatosLegajosVal");
                //loadGrid("gridDatosPpdLegajo", id);
                //loadGrid("gridDatosLegajosVal", id);
            }
        });
        $("#gridLegajos").navGrid("#pagerLegajos",
                {edit: false, add: false, del: false, search: false, refresh: false, view: false});
        $("#gridLegajos").navButtonAdd("#pagerLegajos", {
            caption: "Borrar filtros",
            title: "Borrar filtros",
            buttonicon: 'ui-icon-refresh',
            onClickButton: function () {
                jQuery("#gridLegajos")[0].clearToolbar();
                gridReload('gridLegajos');
            }
        });
        $('#gridLegajos').jqGrid('filterToolbar', {stringResult: true, searchOnEnter: false, autoSearch: false, defaultSearch: 'cn', ignoreCase: true});

        $("#gridDatosPpdLegajo").jqGrid({
            width: 460,
            height: 150,
            shrinkToFit: true,
            forceFit: false,
            autowidth: true,
            rowNum: 1000,
            rownumbers: true,
            datatype: "local",
            colNames: ["Id", "Solo Lectura", "Dato", "Contenido", "Contant", "PPId", "Tipo"],
            colModel: [
                {name: 'id', index: 'id',
                    width: 10,
                    align: "center",
                    sortable: false,
                    sorttype: 'int',
                    hidden: false
                },
                {name: 'solo_lectura', index: 'solo_lectura',
                    width: 10,
                    align: "center",
                    sortable: true,
                    sorttype: 'text',
                    search: true,
                    stype: 'select',
                    searchoptions: {value: ":;S:Si;N:o"}
                },
                {name: 'descripcion', index: 'descripcion',
                    width: 30,
                    align: "center",
                    sortable: true,
                    sorttype: 'text',
                    search: true,
                    stype: 'text',
                    searchoptions: {clearSearch: true}
                },
                {name: 'contenido', index: 'contenido',
                    width: 30,
                    align: "center",
                    sortable: true,
                    sorttype: 'text',
                    search: true,
                    stype: 'text',
                    searchoptions: {clearSearch: true}
                },
                {name: 'contant', index: 'contant',
                    width: 30,
                    align: "center",
                    sortable: true,
                    sorttype: 'text',
                    search: true,
                    stype: 'text',
                    searchoptions: {clearSearch: true}
                },
                {name: 'pp_id', index: 'pp_id',
                    width: 10,
                    align: "center",
                    sortable: false,
                    sorttype: 'int',
                    hidden: true
                },
                {name: 'tipo_de_campo', index: 'tipo_de_campo',
                    width: 10,
                    align: "center",
                    sortable: true,
                    sorttype: 'text',
                    search: true,
                    stype: 'select',
                    searchoptions: {value: ":;C:Caracter;N:Numero;F:Fecha"},
                    hidden: true
                }
            ],
            pager: "#pagerDatosPpdLegajo",
            sortname: "id",
            sortorder: "ASC",
            viewrecords: true,
            viewsortcols: [true, 'horizontal', true],
            gridview: true,
            hidegrid: false,
            ignoreCase: true,
            autoencode: true,
            pgbuttons: false,
            pgtext: false,
            pginput: false,
            loadonce: true,
            //caption: ""
            gridComplete: function () {
                var ids = $("#gridDatosPpdLegajo").jqGrid('getDataIDs');
                ids = ids.toString();
                ids = ids.split(",");

                for (var i = 0; i < ids.length; i++) {
                    var cl = ids[i];
                    var data = $("#gridDatosPpdLegajo").jqGrid('getRowData', ids[i]);
                    if (data['solo_lectura'] == 'S') {
                        jQuery("#gridDatosPpdLegajo").jqGrid('setRowData', cl, false, {color: '#000000', background: '#FFFF99'});
                    }
                }
            },
            onSelectRow: function (rowid) {
                var data = $("#gridDatosPpdLegajo").jqGrid('getRowData', rowid);
                loadGrid('gridDatosLegajosVal', data['id']);
            }
        });
        $("#gridDatosPpdLegajo").navGrid("#pagerDatosPpdLegajo",
                {edit: false, add: false, del: false, search: false, refresh: false, view: false});
//        $("#gridDatosPpdLegajo").navButtonAdd("#pagerDatosPpdLegajo", {
//            caption: "Borrar filtros",
//            title: "Borrar filtros",
//            buttonicon: 'ui-icon-refresh',
//            onClickButton: function () {
//                jQuery("#gridDatosPpdLegajo")[0].clearToolbar();
//                //loadGrid('gridDatosPpdLegajo');
//                //gridReload('gridDatosPpdLegajo');
//            }
//        });
        $('#gridDatosPpdLegajo').jqGrid('filterToolbar', {stringResult: true, searchOnEnter: false, autoSearch: false, defaultSearch: 'cn', ignoreCase: true});

        $("#gridDatosLegajosVal").jqGrid({
            width: 400,
            height: 205,
            shrinkToFit: true,
            forceFit: false,
            autowidth: true,
            rowNum: 1000,
            rownumbers: true,
            datatype: 'local',
            colNames: ["Id", "PropiedadId", "Valor", "Significado"],
            colModel: [
                {name: 'id', index: 'id',
                    width: 10,
                    align: "center",
                    sortable: false,
                    sorttype: 'int',
                    hidden: true
                },
                {name: 'propiedad', index: 'propiedad',
                    width: 10,
                    align: "center",
                    sortable: true,
                    sorttype: 'int',
                    hidden: true
                },
                {name: 'valor_posible', index: 'valor_posible',
                    width: 15,
                    align: "center",
                    sortable: false,
                    sorttype: 'text',
                    search: true,
                    stype: 'text',
                    searchoptions: {clearSearch: true}
                },
                {name: 'significado', index: 'significado',
                    width: 15,
                    align: "center",
                    sortable: false,
                    sorttype: 'text',
                    search: true,
                    stype: 'text',
                    searchoptions: {clearSearch: true}
                }
            ],
            pager: "#pagerDatosLegajosVal",
            sortname: "id",
            sortorder: "ASC",
            viewrecords: true,
            viewsortcols: [true, 'horizontal', true],
            gridview: true,
            hidegrid: false,
            ignoreCase: true,
            autoencode: true,
            pgbuttons: false,
            pgtext: false,
            pginput: false,
            loadonce: true
            //caption: ""
        });
        $("#gridDatosLegajosVal").navGrid("#pagerDatosLegajosVal",
                {edit: false, add: false, del: false, search: false, refresh: false, view: false});
//        $("#gridDatosLegajosVal").navButtonAdd("#pagerDatosLegajosVal", {
//            caption: "Borrar filtros",
//            title: "Borrar filtros",
//            buttonicon: 'ui-icon-refresh',
//            onClickButton: function () {
//                jQuery("#gridDatosLegajosVal")[0].clearToolbar();
//                //loadGrid('gridDatosLegajosVal');
//                //gridReload('gridDatosLegajosVal');
//            }
//        });
        $('#gridDatosLegajosVal').jqGrid('filterToolbar', {stringResult: true, searchOnEnter: false, autoSearch: false, defaultSearch: 'cn', ignoreCase: true});
        jQuery("#gridDatosLegajosVal").jqGrid('sortableRows', {
            update: function (e, ui) {
                reOrder('gridDatosLegajosVal', 'orden');
            }
        });

        //Tabs
        $("#tabsLegajos").tabs({
            heightStyle: "content"
        });

        //Buttons
        $("#btnAddLegajos").click(function () {
            openDiagLegajos("form-add-edit-Legajos", "add", "", "");
        });
        $("#btnDelLegajos").click(function () {
            var rowid = jQuery("#gridLegajos").jqGrid('getGridParam', 'selrow');
            if (rowid != null) {
                $.ajax({
                    url: "<?php echo $this->url('legajos', array('action' => 'deleteGridItem')); ?>",
                    global: false,
                    type: "POST",
                    data: "id=" + rowid,
                    dataType: "json",
                    async: false,
                    success: function (msg) {
                        gridReload('gridLegajos');
                    }
                });
            }
            else {
                msgAlert("diagAlert", "dataAlert", "Por favor seleccione una fila.");
            }
        });
        $("#btnEditLegajos").click(function () {
            var rowid = jQuery("#gridLegajos").jqGrid('getGridParam', 'selrow');
            if (rowid != null) {
                openDiagLegajos("form-add-edit-Legajos", "edit", "gridLegajos", rowid);
            }
            else {
                msgAlert("diagAlert", "dataAlert", "Por favor seleccione una fila.");
            }
        });
        $("#btnRefreshVistasLegajos").click(function () {
            loadSelectView();
        });

        //btnAddAllData =>>
        $("#btnAddAllData").click(function () {
            var dataGrid = jQuery("#gridDatosPpdLegajo").jqGrid('getGridParam', 'data');
            if (dataGrid.length > 0) {
                for (var i = 0; i < dataGrid.length; i++) {
                    var ids = $("#gridDatosLegajosVal").jqGrid('getDataIDs');
                    ids = ids.toString();
                    ids = ids.split(",");

                    var data = {
                        "propiedadId": dataGrid[i]['id'],
                        "propiedad": dataGrid[i]['descripcion'],
                        "tipo": dataGrid[i]['tipo_de_campo'],
                        "formularioId": "",
                        "orden": (ids.length > 0 && ids[0] != 'undefined' && ids[0] != "") ? ids.length + 1 : 1,
                        "solo_lectura": "Si"
                    };

                    if (ids.length > 0 && ids[0] != 'undefined' && ids[0] != "") {
                        $("#gridDatosLegajosVal").jqGrid('addRowData', parseInt(ids[ids.length - 1]) + 1, data);
                    } else {
                        $("#gridDatosLegajosVal").jqGrid('addRowData', 1, data);
                    }
                }
                deleteGrid('gridDatosPpdLegajo');
            }
        });
        //btnAddSingleData >
        $("#btnAddSingleData").click(function () {
            var rowid = jQuery("#gridDatosPpdLegajo").jqGrid('getGridParam', 'selrow');
            if (rowid != null) {
                var dataRow = $("#gridDatosPpdLegajo").jqGrid('getRowData', rowid);
                var ids = $("#gridDatosLegajosVal").jqGrid('getDataIDs');
                ids = ids.toString();
                ids = ids.split(",");

                var data = {
                    "propiedadId": dataRow['id'],
                    "propiedad": dataRow['descripcion'],
                    "tipo": dataRow['tipo_de_campo'],
                    "formularioId": "",
                    "orden": (ids.length > 0 && ids[0] != 'undefined' && ids[0] != "") ? ids.length + 1 : 1,
                    "solo_lectura": "Si"
                };

                if (ids.length > 0 && ids[0] != 'undefined' && ids[0] != "") {
                    $("#gridDatosLegajosVal").jqGrid('addRowData', ids.length + 1, data);
                } else {
                    $("#gridDatosLegajosVal").jqGrid('addRowData', 1, data);
                }
                $("#gridDatosPpdLegajo").jqGrid('delRowData', rowid);
            }
            else {
                msgAlert("diagAlertModal", "dataAlertModal", "Por favor seleccione una fila.");
            }
        });
        //btnDelSingleData <
        $("#btnDelSingleData").click(function () {
            var rowid = jQuery("#gridDatosLegajosVal").jqGrid('getGridParam', 'selrow');
            if (rowid != null) {
                var dataRow = $("#gridDatosLegajosVal").jqGrid('getRowData', rowid);
                var data = {
                    "id": dataRow['propiedadId'],
                    "descripcion": dataRow['propiedad'],
                    "tipo_de_campo": dataRow['tipo']
                };

                $("#gridDatosPpdLegajo").jqGrid('addRowData', dataRow['propiedadId'], data);
                $("#gridDatosLegajosVal").jqGrid('delRowData', rowid);
                reOrder('gridDatosLegajosVal', 'orden');
                $("#gridDatosPpdLegajo").setGridParam({datatype: 'local', sortname: 'id'}).trigger('reloadGrid');
            }
            else {
                msgAlert("diagAlertModal", "dataAlertModal", "Por favor seleccione una fila.");
            }
        });
        //btnDelAllData <<=
        $("#btnDelAllData").click(function () {
            var dataGrid = jQuery("#gridDatosLegajosVal").jqGrid('getGridParam', 'data');
            if (dataGrid.length > 0) {
                for (var i = 0; i < dataGrid.length; i++) {
                    var ids = $("#gridDatosPpdLegajo").jqGrid('getDataIDs');
                    ids = ids.toString();
                    ids = ids.split(",");

                    var data = {
                        "id": dataGrid[i]['propiedadId'],
                        "descripcion": dataGrid[i]['propiedad'],
                        "tipo_de_campo": dataGrid[i]['tipo']
                    };

                    if (ids.length > 0 && ids[0] != 'undefined' && ids[0] != "") {
                        $("#gridDatosPpdLegajo").jqGrid('addRowData', parseInt(ids[ids.length - 1]) + 1, data);
                    } else {
                        $("#gridDatosPpdLegajo").jqGrid('addRowData', 1, data);
                    }
                }
                $("#gridDatosPpdLegajo").setGridParam({datatype: 'local', sortname: 'id'}).trigger('reloadGrid');
                deleteGrid('gridDatosLegajosVal');
            }
        });

        //Dialog addLegajos
        $("#form-add-edit-Legajos").dialog({
            autoOpen: false,
            resizable: true,
            draggable: true,
            closeOnEscape: false,
            modal: true,
            width: 'auto', //1000, 
            height: 'auto', //500,
            maxWidth: 1200,
            //position: ['center',110] , //{ my: "center", at: "center", of: window }
            //fluid: true, //new option
            open: function (event, ui) {
                $(event.target).parent().css('position', 'fixed');
                $(event.target).parent().css('top', '110px');
                $(event.target).parent().css('left', '275px');
            },
            buttons: {
                'Aceptar': function () {
                    var legajo = $("#legajo-add-Legajos").val();
                    var apellidoYNombre = $("#apellidoYNombre-add-Legajos").val();

                    if (legajo != '' && apellidoYNombre != '') {
                        var ids = $("#gridLegajos").jqGrid('getDataIDs');
                        ids = ids.toString();
                        ids = ids.split(",");

                        var e = 0;
                        var rowid = "";

                        if (oEdit) {
                            rowid = jQuery("#gridLegajos").jqGrid('getGridParam', 'selrow');
                            if (rowid != null) {
                                if (ids != "") {
                                    for (var i = 0; i < ids.length; i++) {
                                        var data = $("#gridLegajos").jqGrid('getRowData', ids[i]);
                                        if (data['legajo'].toLowerCase() == $("#legajo-add-Legajos").val().toLowerCase() && data['id'] != rowid) {
                                            e++;
                                        }
                                    }
                                }
                            } else {
                                msgAlert("diagAlert", "dataAlert", "Por favor seleccione una fila.");
                            }
                        } else {
                            if (ids != "") {
                                for (var i = 0; i < ids.length; i++) {
                                    var data = $("#gridLegajos").jqGrid('getRowData', ids[i]);
                                    if (data['legajo'].toLowerCase() == legajo.toLowerCase()) {
                                        e++;
                                    }
                                }
                            }
                        }
                        if (e == 0) {
                            var data = {
                                "legajo": legajo,
                                "apellido_y_nombre": apellidoYNombre
                            };
                            $.ajax({
                                url: "<?php echo $this->url('legajos', array('action' => 'editGridItem')); ?>",
                                global: false,
                                type: "POST",
                                data: "data=" + JSON.stringify(data),
                                dataType: "json",
                                async: false,
                                success: function (msg) {
                                    gridReload('gridLegajos');
                                    $("#form-add-edit-Legajos").dialog('close');
                                }
                            });
                        } else {
                            msgAlert("diagAlertModal", "dataAlertModal", "Ya existe un registro con esa combinacion.");
                        }
                    } else {
                        msgAlert("diagAlertModal", "dataAlertModal", "Ingrese valores a los campos.");
                    }
                },
                'Cancelar': function () {
                    clearDataLegajos();
                    $(this).dialog('close');
                }
            },
            close: function () {
                clearDataLegajos();
            }
        });

        //AlertManager
        $('#diagAlert').on('closed.bs.alert', function () {
            $('.dataAlert').html("");
        });
        $('#diagAlertModal').on('closed.bs.alert', function () {
            $('.dataAlertModal').html("");
        });
        $('#diagAlertTab').on('closed.bs.alert', function () {
            $('.dataAlertTab').html("");
        });

        $("#select-vista-tab-legajos").change(function () {
            //alert($(this).val());
            var rowid = jQuery("#gridLegajos").jqGrid('getGridParam', 'selrow');
            if (rowid != null) {
                loadGrid('gridDatosPpdLegajo', rowid);
            }
            else {
                msgAlert("diagAlertModal", "dataAlert", "Por favor seleccione una fila.");
            }
        });
    });

    // remove window resize namespace
    $(document).on("dialogclose", ".ui-dialog", function (event, ui) {
        $(window).off("resize.responsive");
    });

    function gridReload(gridName) {
        $("#" + gridName).setGridParam({datatype: 'json'})/*.setGridParam({rowNum: 10})*/.trigger('reloadGrid');
    }

    function openDiagLegajos(diagName, op, grid, id) {
        clearDataLegajos();
        if (op == "edit") {
            rowdata = jQuery("#" + grid).getRowData(id);
            $('#legajo-add-Legajos').val(rowdata['legajo']);
            $('#apellidoYNombre-add-Legajos').val(rowdata['apellido_y_nombre']);
            $('#' + diagName).dialog("option", "title", "Editar registro");
            $('#' + diagName).dialog('open');
            $('#' + diagName).dialog('moveToTop');
            oEdit = true;
        } else {
            $('#' + diagName).dialog("option", "title", "Agregar registro");
            $('#' + diagName).dialog('open');
            $('#' + diagName).dialog('moveToTop');
            oEdit = false;
        }
    }

    function clearDataLegajos() {
        $('#legajo-add-Legajos').val("");
        $('#legajo-edit-Legajos').val("");
        $('#apellidoYNombre-add-Legajos').val("");
        $('#apellidoYNombre-edit-Legajos').val("");
    }

    function msgAlert(diagName, selectorName, msg) {
        $('#' + diagName).show();
        $('.' + selectorName).html(msg);
        setTimeout(function () {
            $('#' + diagName).hide("drop", {direction: "up"}, "slow");
            $('.' + selectorName).html("");
        }, 3000);
        return;
    }

    function loadGrid(gridName, rowid) {
        switch (gridName) {
            case 'gridDatosPpdLegajo':
                var data = {
                    "id": rowid,
                    "vistaLegajoSel": $('#select-vista-tab-legajos').val()
                };
                $.ajax({
                    url: "<?php echo $this->url('legajos', array('action' => 'loadPpdLegajoGrid')); ?>",
                    global: false,
                    type: "POST",
                    data: "data=" + JSON.stringify(data),
                    dataType: "json",
                    async: false,
                    success: function (result) {
                        if (result.type == "success") {// ok	
                            deleteGrid('gridDatosPpdLegajo');
                            if (result.data.length > 0) {
                                for (var i = 0; i < result.data.length; i++) {
                                    var dataLocal = {
                                        "id": result.data[i][0],
                                        "descripcion": result.data[i][1],
                                        "contenido": result.data[i][2],
                                        "contant": result.data[i][3],
                                        "pp_id": result.data[i][4],
                                        "solo_lectura": result.data[i][5],
                                        "tipo_de_campo": result.data[i][6]
                                    };
                                    var ids = jQuery("#gridDatosPpdLegajo").jqGrid('getDataIDs');
                                    ids = ids.toString();

                                    ids = ids.split(",");
                                    if (ids.length > 0 && ids[0] != 'undefined' && ids[0] != "") {
                                        $("#gridDatosPpdLegajo").jqGrid('addRowData', ids.length + 1, dataLocal);
                                    } else {
                                        $("#gridDatosPpdLegajo").jqGrid('addRowData', 1, dataLocal);
                                    }
                                }
                            }
                        }
                    }
                });
                break;
            case 'gridDatosLegajosVal':
                $.ajax({
                    url: "<?php echo $this->url('legajos', array('action' => 'loadDataGrid')); ?>",
                    global: false,
                    type: "POST",
                    data: "id=" + rowid,
                    dataType: "json",
                    async: false,
                    success: function (result) {
                        if (result.type == "success") {
                            deleteGrid('gridDatosLegajosVal');
                            if (result.data.length > 0) {
                                for (var i = 0; i < result.data.length; i++) {
                                    var dataLocal = {
                                        "id": result.data[i][0],
                                        "propiedadId": result.data[i][1],
                                        "valor_posible": result.data[i][2],
                                        "significado": result.data[i][3]
                                    };
                                    var ids = jQuery("#gridDatosLegajosVal").jqGrid('getDataIDs');
                                    ids = ids.toString();

                                    ids = ids.split(",");
                                    if (ids.length > 0 && ids[0] != 'undefined' && ids[0] != "") {
                                        $("#gridDatosLegajosVal").jqGrid('addRowData', ids.length + 1, dataLocal);
                                    } else {
                                        $("#gridDatosLegajosVal").jqGrid('addRowData', 1, dataLocal);
                                    }
                                }
                            }
                        }
                    }
                });
                break;
        }
    }

    function deleteGrid(gridName) {
        var $table;
        $table = $('#' + gridName);

        var ids = $table.jqGrid('getDataIDs');
        ids = ids.toString();
        ids = ids.split(",");
        if (ids.length > 0) {
            for (var i = 0; i < ids.length; i++) {
                $table.delRowData(ids[i]);
            }
        }
        $table.clearGridData(true).trigger("reloadGrid");
    }

    function reOrder(gridName, sortField) {
        var ids = $("#" + gridName).jqGrid('getDataIDs');
        ids = ids.toString();
        ids = ids.split(",");

        var orden = 1;

        if (ids != "") {
            for (var i = 0; i < ids.length; i++) {
                jQuery('#' + gridName).setCell(ids[i], sortField, orden);
                orden++;
            }
        }
    }

    function loadSelectView() {
        var list_target_id = 'select-vista-tab-legajos';
        $('#' + list_target_id).html('<option value="">Cargando...</option>');

        $.ajax({
            url: "<?php echo $this->url('legajos', array('action' => 'loadSelectView')); ?>",
            global: false,
            type: "POST",
            dataType: "json",
            async: false,
            success: function (result) {
                $('#' + list_target_id).html("");
                $.each(result.data, function (i, d) {
                    $('#' + list_target_id).append('<option value="' + i + '">' + d + '</option>');
                });
            },
            error: function (xhr, ajaxOptions, thrownError) {
                alert(xhr.status + " " + thrownError);
            }
        });
    }
</script>

<!-- Dialogo form-add-edit-Legajos -->
<div id="form-add-edit-Legajos" class="container-fluid" title="" >
    <form class="form-horizontal" role="form">
        <div class="form-group">
            <label for="input-legajo-add-Legajos" class="col-sm-4 control-label">Legajo Nº:</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="legajo-add-Legajos" placeholder="">
            </div>
        </div>
        <div class="form-group">
            <label for="input-apellidoYNombre-add-Legajos" class="col-sm-4 control-label">Apellido y nombre:</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="apellidoYNombre-add-Legajos" placeholder="">
            </div>
        </div>
    </form>
    <div class="alert alert-warning" id="diagAlertModal">
        <a href="#" class="close" data-dismiss="alert">&times;</a>
        <strong><span class="dataAlertModal"></span></strong>
    </div>
</div>