<?php
$title = 'Definición de datos de Legajos';
?>
<h1 class="page-header" style="padding-top:20px"><?php echo $this->escapeHtml($title); ?></h1>
<?php
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
            &times;
            </button>
        <ul><li>')
        ->setMessageSeparatorString('</li><li>')
        ->setMessageCloseString('</li></ul></div>');

echo $flash->render('error', array('alert', 'alert-dismissable', 'alert-danger', 'flashAlert'));
echo $flash->render('info', array('alert', 'alert-dismissable', 'alert-info', 'flashAlert'));
echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning', 'flashAlert'));
echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success', 'flashAlert'));
?>

<script type="text/javascript" src="../js/jqueryValidation/dist/jquery.validate.min.js"></script>    
<script type="text/javascript" src="../js/jqueryValidation/dist/additional-methods.min.js"></script>  
<script type="text/javascript" src="../js/jqueryValidation/dist/localization/messages_es_AR.min.js"></script>  

<div class="alert alert-warning ui-state-highlight ui-corner-all" id="diagAlertMain">
    <a href="#" class="close" data-dismiss="alert">&times;</a>
    <strong><span class="dataAlertMain"></span></strong>
</div>

<br>
<div class="content">
    <div class="row">
        <div class="col-xs-6">
            <div class="btn-group">
                <button type="button" class="btn btn-primary btn-lg" id="btnAddDatosLegajos">Alta</button>
                <button type="button" class="btn btn-primary btn-lg" id="btnDelDatosLegajos">Baja</button>
                <button type="button" class="btn btn-primary btn-lg" id="btnEditDatosLegajos">Modificación</button>
            </div>
            <br>
            <div id="jqGridDatosLegajos" style="padding-top:10px;">
                <table id="gridDatosLegajos"></table>
                <div id="pagerDatosLegajos"></div>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="btn-group">
                <button type="button" class="btn btn-primary btn-lg" id="btnAddDatosLegajosVal">Alta</button>
                <button type="button" class="btn btn-primary btn-lg" id="btnDelDatosLegajosVal">Baja</button>
                <button type="button" class="btn btn-primary btn-lg" id="btnEditDatosLegajosVal">Modificación</button>
            </div>
            <br>
            <div id="jqGridDatosLegajosVal" style="padding-top:10px;">
                <table id="gridDatosLegajosVal"></table>
                <div id="pagerDatosLegajosVal"></div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        //Grids
        $("#gridDatosLegajos").jqGrid({
            width: 100,
            height: 230,
            autowidth: true,
            rowNum: 1000,
            rownumbers: true,
            url: "<?php echo $this->url('datoslegajos', array('action' => 'loadDataGrid')); ?>",
            datatype: 'json',
            mtype: 'POST',
            colNames: ["Id", "Propiedad", "Tipo"],
            colModel: [
                {name: 'id', index: 'id',
                    width: 10,
                    align: "center",
                    sortable: false,
                    sorttype: 'int',
                    hidden: true
                },
                {name: 'descripcion', index: 'descripcion',
                    width: 30,
                    align: "center",
                    sortable: true,
                    sorttype: 'text',
                    search: true,
                    stype: 'text',
                    searchoptions: {clearSearch: true}
                },
                {name: 'tipo_de_campo', index: 'tipo_de_campo',
                    width: 5,
                    align: "center",
                    sortable: true,
                    sorttype: 'text',
                    search: true,
                    stype: 'select',
                    searchoptions: {value: ":;C:Caracter;N:Numero;F:Fecha"}
                }
            ],
            pager: "#pagerDatosLegajos",
            sortname: "id",
            sortorder: "ASC",
            viewrecords: true,
            viewsortcols: [true, 'horizontal', true],
            gridview: true,
            hidegrid: false,
            ignoreCase: true,
            autoencode: true,
            forceFit: false,
            pgbuttons: false,
            pgtext: false,
            pginput: false,
            loadonce: true,
            editurl: "<?php echo $this->url('datoslegajos', array('action' => 'editGridItem')); ?>",
            caption: "Datos de Legajos",
            onSelectRow: function (id) {
                loadGridDatosLegajosVal(id);
            }
        });
        $("#gridDatosLegajos").navGrid("#pagerDatosLegajos",
                {edit: false, add: false, del: false, search: false, refresh: false, view: false});
        $("#gridDatosLegajos").navButtonAdd("#pagerDatosLegajos", {
            caption: "Borrar filtros",
            title: "Borrar filtros",
            buttonicon: 'ui-icon-refresh',
            onClickButton: function () {
                jQuery("#gridDatosLegajos")[0].clearToolbar();
                gridReload('gridDatosLegajos');
            }
        });
        $('#gridDatosLegajos').jqGrid('filterToolbar', {stringResult: true, searchOnEnter: false, autoSearch: false, defaultSearch: 'cn', ignoreCase: true});

        $("#gridDatosLegajosVal").jqGrid({
            width: 450,
            height: 230,
            shrinkToFit: true,
            forceFit: false,
            autowidth: false,
            rowNum: 1000,
            rownumbers: true,
            url: "<?php echo $this->url('datoslegajos', array('action' => 'loadDataGridVal')); ?>",
            datatype: "json",
            mtype: 'POST',
            colNames: ["Id", "PropiedadId", "Valor", "Significado"],
            colModel: [
                {name: 'id', index: 'id',
                    width: 10,
                    align: "center",
                    sortable: false,
                    sorttype: 'int',
                    hidden: true
                },
                {name: 'propiedad', index: 'propiedad',
                    width: 10,
                    align: "center",
                    sortable: true,
                    sorttype: 'int',
                    hidden: true
                },
                {name: 'valor_posible', index: 'valor_posible',
                    width: 15,
                    align: "center",
                    sortable: false,
                    sorttype: 'text',
                    search: true,
                    stype: 'text',
                    searchoptions: {clearSearch: true},
                    editable: true,
                    editrules: {required: true},
                    editoptions: {size: 30}
                },
                {name: 'significado', index: 'significado',
                    width: 15,
                    align: "center",
                    sortable: false,
                    sorttype: 'text',
                    search: true,
                    stype: 'text',
                    searchoptions: {clearSearch: true},
                    editable: true,
                    editrules: {required: true},
                    editoptions: {size: 30}
                }
            ],
            pager: "#pagerDatosLegajosVal",
            sortname: "propiedad",
            sortorder: "ASC",
            viewrecords: true,
            viewsortcols: [true, 'horizontal', true],
            gridview: true,
            hidegrid: false,
            ignoreCase: true,
            autoencode: true,
            pgbuttons: false,
            pginput: false,
            loadonce: true,
            editurl: "<?php echo $this->url('datoslegajos', array('action' => 'editGridItemVal')); ?>",
            caption: "Valores Posibles"
        });
        $("#gridDatosLegajosVal").navGrid("#pagerDatosLegajosVal",
                {edit: false, add: false, del: false, search: false, refresh: false, view: false});
        $("#gridDatosLegajosVal").navButtonAdd("#pagerDatosLegajosVal", {
            caption: "Borrar filtros",
            title: "Borrar filtros",
            buttonicon: 'ui-icon-refresh',
            onClickButton: function () {
                jQuery("#gridDatosLegajosVal")[0].clearToolbar();
            }
        });
        $('#gridDatosLegajosVal').jqGrid('filterToolbar', {stringResult: true, searchOnEnter: false, autoSearch: false, defaultSearch: 'cn', ignoreCase: true});

        //Buttons
        $("#btnAddDatosLegajos").click(function () {
            openDiagDatosLegajos("form-add-datosLegajos", "add", "", "");
        });
        $("#btnDelDatosLegajos").click(function () {
            var rowid = jQuery("#gridDatosLegajos").jqGrid('getGridParam', 'selrow');
            if (rowid != null) {
                var ids = $("#gridDatosLegajosVal").jqGrid('getDataIDs');
                ids = ids.toString();
                ids = ids.split(",");
                var e = 0;

                if (ids != "") {
                    for (var i = 0; i < ids.length; i++) {
                        var data = $("#gridDatosLegajosVal").jqGrid('getRowData', ids[i]);
                        if (data['propiedad'] == rowid) {
                            e++;
                        }
                    }
                }

                if (e == 0) {
                    $.ajax({
                        url: "<?php echo $this->url('datoslegajos', array('action' => 'deleteGridItem')); ?>",
                        global: false,
                        type: "POST",
                        data: "id=" + rowid,
                        dataType: "json",
                        async: false,
                        success: function (result) {
                            gridReload('gridDatosLegajos');
                            gridReload('gridDatosLegajosVal');
                        },
                        error: function (xhr, ajaxOptions, thrownError) {
                            alert(xhr.status + " " + thrownError);
                        }
                    });
                } else {
                    msgAlert("diagAlertMain", "dataAlertMain", "No se puede eliminar la propiedad porque tiene valores asociados.");
                }
            }
            else {
                msgAlert("diagAlertMain", "dataAlertMain", "Por favor seleccione una fila.");
            }
        });
        $("#btnEditDatosLegajos").click(function () {
            var rowid = jQuery("#gridDatosLegajos").jqGrid('getGridParam', 'selrow');
            if (rowid != null) {
                openDiagDatosLegajos("form-edit-datosLegajos", "edit", "gridDatosLegajos", rowid);
            }
            else {
                msgAlert("diagAlertMain", "dataAlertMain", "Por favor seleccione una fila.");
            }
        });
        $("#btnAddDatosLegajosVal").click(function () {
            var rowid = jQuery("#gridDatosLegajos").jqGrid('getGridParam', 'selrow');
            var rowidVal = jQuery("#gridDatosLegajosVal").jqGrid('getGridParam', 'selrow');
            if (rowid != null) {
                openDiagDatosLegajosVal("form-add-datosLegajosVal", "add", "gridDatosLegajosVal", rowidVal);
            }
            else {
                msgAlert("diagAlertMain", "dataAlertMain", "Por favor seleccione una fila.");
            }
        });
        $("#btnDelDatosLegajosVal").click(function () {
            var rowid = jQuery("#gridDatosLegajosVal").jqGrid('getGridParam', 'selrow');
            if (rowid != null) {
                $.ajax({
                    url: "<?php echo $this->url('datoslegajos', array('action' => 'deleteGridItemVal')); ?>",
                    global: false,
                    type: "POST",
                    data: "id=" + rowid,
                    dataType: "json",
                    async: false,
                    success: function () {
                        gridReload('gridDatosLegajosVal');
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        alert(xhr.status + " " + thrownError);
                    }
                });
            }
            else {
                msgAlert("diagAlertMain", "dataAlertMain", "Por favor seleccione una fila.");
            }
        });
        $("#btnEditDatosLegajosVal").click(function () {
            var rowid = jQuery("#gridDatosLegajosVal").jqGrid('getGridParam', 'selrow');
            if (rowid != null) {
                openDiagDatosLegajosVal("form-edit-datosLegajosVal", "edit", "gridDatosLegajosVal", rowid);
            }
            else {
                msgAlert("diagAlertMain", "dataAlertMain", "Por favor seleccione una fila.");
            }
        });

        //Dialog addDatosLegajos
        $("#form-add-datosLegajos").dialog({
            autoOpen: false,
            resizable: true,
            closeOnEscape: true,
            modal: true,
            width: 'auto', // overcomes width:'auto' and maxWidth bug
            height: 'auto',
            maxWidth: 600,
            buttons: {
                'Aceptar': function () {
                    if ($("#valid-form-edit-datosLegajos").valid()) {
                        var descripcion = $("#descripcionAddDatosLegajos").val();
                        var tipo = $("#tipoAddDatosLegajos").val();

                        var ids = $("#gridDatosLegajos").jqGrid('getDataIDs');
                        ids = ids.toString();
                        ids = ids.split(",");
                        var e = 0;

                        if (ids != "") {
                            for (var i = 0; i < ids.length; i++) {
                                var data = $("#gridDatosLegajos").jqGrid('getRowData', ids[i]);
                                if (data['descripcion'].toLowerCase() == descripcion.toLowerCase()) {
                                    e++;
                                }
                            }
                        }

                        if (e == 0) {
                            var data = {
                                "descripcion": descripcion,
                                "tipo_de_campo": tipo
                            };
                            $.ajax({
                                url: "<?php echo $this->url('datoslegajos', array('action' => 'editGridItem')); ?>",
                                global: false,
                                type: "POST",
                                data: "data=" + JSON.stringify(data),
                                dataType: "json",
                                async: false,
                                success: function (result) {
                                    gridReload('gridDatosLegajos');
                                    $("#form-add-datosLegajos").dialog('close');
                                },
                                error: function (xhr, ajaxOptions, thrownError) {
                                    alert(xhr.status + " " + thrownError);
                                }
                            });
                        } else {
                            msgAlert("diagAlertModalAddP", "dataAlertModalAddP", "Ya existe un registro con esa combinacion.");
                        }
                    }
                },
                'Cancelar': function () {
                    validFormAddDatosLegajos.resetForm();
                    $(this).dialog('close');
                }
            },
            close: function () {
                validFormAddDatosLegajos.resetForm();
            }
        });
        //Dialog editDatosLegajos
        $("#form-edit-datosLegajos").dialog({
            autoOpen: false,
            resizable: true,
            closeOnEscape: true,
            modal: true,
            width: 'auto', // overcomes width:'auto' and maxWidth bug
            height: 'auto',
            maxWidth: 600,
            buttons: {
                'Aceptar': function () {
                    if ($("#valid-form-edit-datosLegajos").valid()) {
                        var rowid = jQuery("#gridDatosLegajos").jqGrid('getGridParam', 'selrow');
                        if (rowid != null) {
                            var ids = $("#gridDatosLegajos").jqGrid('getDataIDs');
                            ids = ids.toString();
                            ids = ids.split(",");
                            var e = 0;

                            if (ids != "") {
                                for (var i = 0; i < ids.length; i++) {
                                    var data = $("#gridDatosLegajos").jqGrid('getRowData', ids[i]);
                                    if (data['descripcion'].toLowerCase() == $("#descripcionEditDatosLegajos").val().toLowerCase() && data['id'] != rowid) {
                                        e++;
                                    }
                                }
                            }

                            if (e == 0)
                            {
                                var data = {
                                    "id": rowid,
                                    "descripcion": $("#descripcionEditDatosLegajos").val(),
                                    "tipo_de_campo": $("#tipoEditDatosLegajos").val()
                                };
                                $.ajax({
                                    url: "<?php echo $this->url('datoslegajos', array('action' => 'editGridItem')); ?>",
                                    global: false,
                                    type: "POST",
                                    data: "data=" + JSON.stringify(data),
                                    dataType: "json",
                                    async: false,
                                    success: function (result) {
                                        gridReload('gridDatosLegajos');
                                        $("#form-edit-datosLegajos").dialog('close');
                                    },
                                    error: function (xhr, ajaxOptions, thrownError) {
                                        alert(xhr.status + " " + thrownError);
                                    }
                                });
                            } else {
                                msgAlert("diagAlertModalEditP", "dataAlertModalEditP", "Ya existe un registro con esa combinacion.");
                            }
                        }
                    }
                },
                'Cancelar': function () {
                    validFormEditDatosLegajos.resetForm();
                    $(this).dialog('close');
                }
            },
            close: function () {
                validFormEditDatosLegajos.resetForm();
            }
        });
        //Dialog addDatosLegajosVal
        $("#form-add-datosLegajosVal").dialog({
            autoOpen: false,
            resizable: true,
            closeOnEscape: true,
            modal: true,
            width: 'auto', // overcomes width:'auto' and maxWidth bug
            height: 'auto',
            maxWidth: 600,
            buttons: {
                'Aceptar': function () {
                    if ($("#valid-form-add-datosLegajosVal").valid()) {
                        var rowid = jQuery("#gridDatosLegajos").jqGrid('getGridParam', 'selrow');
                        var ids = $("#gridDatosLegajosVal").jqGrid('getDataIDs');
                        ids = ids.toString();
                        ids = ids.split(",");
                        var e = 0;

                        if (ids != "") {
                            for (var i = 0; i < ids.length; i++) {
                                var data = $("#gridDatosLegajosVal").jqGrid('getRowData', ids[i]);
                                if (data['propiedad'] == rowid && data['valor_posible'].toLowerCase() == $("#valorPosibleAddDatosLegajosVal").val().toLowerCase()) {
                                    e++;
                                }
                            }
                        }

                        if (e == 0)
                        {
                            var data = {
                                "propiedad": rowid,
                                "valor_posible": $("#valorPosibleAddDatosLegajosVal").val(),
                                "significado": $("#significadoAddDatosLegajosVal").val()
                            };
                            $.ajax({
                                url: "<?php echo $this->url('datoslegajos', array('action' => 'editGridItemVal')); ?>",
                                global: false,
                                type: "POST",
                                data: "data=" + JSON.stringify(data),
                                dataType: "json",
                                async: false,
                                success: function () {
                                    loadGridDatosLegajosVal(rowid);
                                    $("#form-add-datosLegajosVal").dialog('close');
                                },
                                error: function (xhr, ajaxOptions, thrownError) {
                                    alert(xhr.status + " " + thrownError);
                                }
                            });
                        } else {
                            msgAlert("diagAlertModalAddPV", "dataAlertModalAddPV", "Ya existe un registro con esa combinacion.");
                        }
                    }
                },
                Cancel: function () {
                    validFormAddDatosLegajosVal.resetForm();
                    $(this).dialog('close');
                }
            },
            close: function () {
                validFormAddDatosLegajosVal.resetForm();
            }
        });
        //Dialog editDatosLegajosVal
        $("#form-edit-datosLegajosVal").dialog({
            autoOpen: false,
            resizable: true,
            closeOnEscape: true,
            modal: true,
            width: 'auto', // overcomes width:'auto' and maxWidth bug
            height: 'auto',
            maxWidth: 600,
            buttons: {
                'Aceptar': function () {
                    if ($("#valid-form-edit-datosLegajos").valid()) {
                        var rowid = jQuery("#gridDatosLegajosVal").jqGrid('getGridParam', 'selrow');
                        if (rowid != null) {
                            var dataGrid = $("#gridDatosLegajosVal").jqGrid('getRowData', rowid);
                            var ids = $("#gridDatosLegajosVal").jqGrid('getDataIDs');
                            ids = ids.toString();
                            ids = ids.split(",");
                            var e = 0;

                            if (ids != "") {
                                for (var i = 0; i < ids.length; i++) {
                                    var data = $("#gridDatosLegajosVal").jqGrid('getRowData', ids[i]);
                                    if (data['valor_posible'].toLowerCase() == $("#valorPosibleEditDatosLegajosVal").val().toLowerCase() && data['id'] != rowid) {
                                        e++;
                                    }
                                }
                            }

                            if (e == 0)
                            {
                                var data = {
                                    "id": rowid,
                                    "valor_posible": $("#valorPosibleEditDatosLegajosVal").val(),
                                    "significado": $("#significadoEditDatosLegajosVal").val()
                                };
                                $.ajax({
                                    url: "<?php echo $this->url('datoslegajos', array('action' => 'editGridItemVal')); ?>",
                                    global: false,
                                    type: "POST",
                                    data: "data=" + JSON.stringify(data),
                                    dataType: "json",
                                    async: false,
                                    success: function (result) {
                                        loadGridDatosLegajosVal(dataGrid.propiedad);
                                        $("#form-edit-datosLegajosVal").dialog('close');
                                    },
                                    error: function (xhr, ajaxOptions, thrownError) {
                                        alert(xhr.status + " " + thrownError);
                                    }
                                });
                            } else {
                                msgAlert("diagAlertModalEditPV", "dataAlertModalEditPV", "Ya existe un registro con esa combinacion.");
                            }
                        }
                    }
                },
                Cancel: function () {
                    validFormEditDatosLegajosVal.resetForm();
                    $(this).dialog('close');
                }
            },
            close: function () {
                validFormEditDatosLegajosVal.resetForm();
            }
        });

        //Validation
        var validFormAddDatosLegajos = $("#valid-form-add-datosLegajos").validate({
            rules: {
                descripcionAddDatosLegajos: {required: true}
            }
        });
        var validFormEditDatosLegajos = $("#valid-form-edit-datosLegajos").validate({
            rules: {
                descripcionEditDatosLegajos: {required: true}
            }
        });
        var validFormAddDatosLegajosVal = $("#valid-form-add-datosLegajosVal").validate({
            rules: {
                valorPosibleAddDatosLegajosVal: {required: true},
                significadoAddDatosLegajosVal: {required: true}
            }
        });
        var validFormEditDatosLegajosVal = $("#valid-form-edit-datosLegajosVal").validate({
            rules: {
                valorPosibleEditDatosLegajosVal: {required: true},
                significadoEditDatosLegajosVal: {required: true}
            }
        });

        //AlertManager
        $('#diagAlertMain').on('closed.bs.alert', function () {
            $('.dataAlertMain').html("");
        });
        $('#diagAlertModalAddP').on('closed.bs.alert', function () {
            $('.dataAlertModalAddP').html("");
        });
        $('#diagAlertModalEditP').on('closed.bs.alert', function () {
            $('.dataAlertModalEditP').html("");
        });
        $('#diagAlertModalAddPV').on('closed.bs.alert', function () {
            $('.dataAlertModalAddPV').html("");
        });
        $('#diagAlertModalEditPV').on('closed.bs.alert', function () {
            $('.dataAlertModalEditPV').html("");
        });
    });

    // remove window resize namespace
    $(document).on("dialogclose", ".ui-dialog", function (event, ui) {
        $(window).off("resize.responsive");
    });

    function gridReload(gridName) {
        $("#" + gridName).setGridParam({datatype: 'json'})/*.setGridParam({rowNum: 1000})*/.trigger('reloadGrid');
    }

    function loadGridDatosLegajosVal(id) {
        if (id != null) {
            var sUrl = "<?php echo $this->url('datoslegajos', array('action' => 'loadDataGridVal')); ?>" + "/" + id;
            $("#gridDatosLegajosVal").setGridParam({datatype: 'json', url: sUrl}).trigger('reloadGrid');
        }
        else {
            msgAlert("diagAlertMain", "dataAlertMain", "Por favor seleccione una fila.");
        }
    }

    function openDiagDatosLegajos(diagName, op, grid, id) {
        clearDataDatosLegajos();
        if (op == "edit") {
            rowdata = jQuery("#" + grid).getRowData(id);
            $('#descripcionEditDatosLegajos').val(rowdata['descripcion']);
            $('#tipoEditDatosLegajos').val(rowdata['tipo_de_campo']);
            $('#' + diagName).dialog('open');
        } else {
            $('#' + diagName).dialog('open');
            $('#tipoAddDatosLegajos option:contains("C")').prop('selected', true);
        }
    }

    function openDiagDatosLegajosVal(diagName, op, grid, id) {
        clearDataDatosLegajosVal();
        if (op == "edit") {
            rowdata = jQuery("#" + grid).getRowData(id);
            $('#valorPosibleEditDatosLegajosVal').val(rowdata['valor_posible']);
            $('#significadoEditDatosLegajosVal').val(rowdata['significado']);
            $('#' + diagName).dialog('open');
        } else {
            $('#' + diagName).dialog('open');
        }
    }

    function clearDataDatosLegajos() {
        $('#descripcionAddDatosLegajos').val("");
        $('#descripcionEditDatosLegajos').val("");
    }

    function clearDataDatosLegajosVal() {
        $('#valorPosibleAddDatosLegajosVal').val("");
        $('#significadoAddDatosLegajosVal').val("");
        $('#valorPosibleEditDatosLegajosVal').val("");
        $('#significadoEditDatosLegajosVal').val("");
    }

    function msgAlert(diagName, selectorName, msg) {
        $('#' + diagName).show();
        $('.' + selectorName).html(msg);
        setTimeout(function () {
            $('#' + diagName).hide("drop", {direction: "up"}, "slow");
            $('.' + selectorName).html("");
        }, 3000);
        return;
    }

</script>

<!-- Dialogo form-add-datosLegajos -->
<div id="form-add-datosLegajos"  title="Agregar registro">
    <form class="form-horizontal" id="valid-form-add-datosLegajos" role="form">
        <div class="form-group">
            <label for="descripcionAddDatosLegajos" class="col-sm-4 control-label">Nombre de campo:</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="descripcionAddDatosLegajos" name="descripcionAddDatosLegajos" placeholder="">
            </div>
        </div>
        <div class="form-group">
            <label for="tipoAddDatosLegajos" class="col-sm-4 control-label">Tipo:</label>
            <div class="col-sm-8">
                <select class="form-control" id="tipoAddDatosLegajos" name="tipoAddDatosLegajos">
                    <option value="C">Caracter</option>
                    <option value="N">Numero</option>
                    <option value="F">Fecha</option>
                </select>
            </div>
        </div>
    </form>
    <div class="alert alert-warning ui-state-highlight ui-corner-all" id="diagAlertModalAddP">
        <a href="#" class="close" data-dismiss="alert">&times;</a>
        <strong><span class="dataAlertModalAddP"></span></strong>
    </div>
</div>

<!-- Dialogo form-edit-datosLegajos -->
<div id="form-edit-datosLegajos"  title="Editar registro">
    <form class="form-horizontal" id="valid-form-edit-datosLegajos" role="form">
        <div class="form-group">
            <label for="descripcionEditDatosLegajos" class="col-sm-4 control-label">Nombre de campo:</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="descripcionEditDatosLegajos" name="descripcionEditDatosLegajos" placeholder="">
            </div>
        </div>
        <div class="form-group">
            <label for="tipoEditDatosLegajos" class="col-sm-4 control-label">Tipo:</label>
            <div class="col-sm-8">
                <select class="form-control" id="tipoEditDatosLegajos" name="tipoEditDatosLegajos">
                    <option value="C">Caracter</option>
                    <option value="N">Numero</option>
                    <option value="F">Fecha</option>
                </select>
            </div>
        </div>
    </form>
    <div class="alert alert-warning ui-state-highlight ui-corner-all" id="diagAlertModalEditP">
        <a href="#" class="close" data-dismiss="alert">&times;</a>
        <strong><span class="dataAlertModalEditP"></span></strong>
    </div>
</div>

<!-- Dialogo form-add-datosLegajosVal -->
<div id="form-add-datosLegajosVal"  title="Agregar registro">
    <form class="form-horizontal" id="valid-form-add-datosLegajosVal" role="form">
        <div class="form-group">
            <label for="valorPosibleAddDatosLegajosVal" class="col-sm-4 control-label">Valor:</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="valorPosibleAddDatosLegajosVal" name="valorPosibleAddDatosLegajosVal" placeholder="">
            </div>
        </div>
        <div class="form-group">
            <label for="significadoAddDatosLegajosVal" class="col-sm-4 control-label">Significado:</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="significadoAddDatosLegajosVal" name="significadoAddDatosLegajosVal" placeholder="">
            </div>
        </div>
    </form>
    <div class="alert alert-warning ui-state-highlight ui-corner-all" id="diagAlertModalAddPV">
        <a href="#" class="close" data-dismiss="alert">&times;</a>
        <strong><span class="dataAlertModalAddPV"></span></strong>
    </div>
</div>

<!-- Dialogo form-edit-datosLegajosVal -->
<div id="form-edit-datosLegajosVal"  title="Editar registro">
    <form class="form-horizontal" id="valid-form-edit-datosLegajosVal" role="form">
        <div class="form-group">
            <label for="valorPosibleEditDatosLegajosVal" class="col-sm-4 control-label">Valor:</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="valorPosibleEditDatosLegajosVal" name="valorPosibleEditDatosLegajosVal" placeholder="">
            </div>
        </div>
        <div class="form-group">
            <label for="significadoEditDatosLegajosVal" class="col-sm-4 control-label">Significado:</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="significadoEditDatosLegajosVal" name="significadoEditDatosLegajosVal" placeholder="">
            </div>
        </div>
    </form>
    <div class="alert alert-warning ui-state-highlight ui-corner-all" id="diagAlertModalEditPV">
        <a href="#" class="close" data-dismiss="alert">&times;</a>
        <strong><span class="dataAlertModalEditPV"></span></strong>
    </div>
</div>