<h1>Alta - Propiedades de Empresa o Liquidación</h1>
<hr/>
<?php
$flash=$this->flashMessenger()
            ->setMessageOpenFormat('<div%s>')
            ->setMessageSeparatorString('')
            ->setMessageCloseString('</div>');
?>
<?php
$this->headTitle("Añadir propiedad");
$form = $this->form;
$form->prepare();
$formLabel = $this->plugin('formLabel');
echo $this->form()->openTag($form);
echo $flash->render('duplicado',array('btn', 'btn-danger'));
?>
<div class="form_element">
<?php
    $descripcion = $form->get('descripcion');
    echo $formLabel->openTag().$descripcion->getOption('label')." ";
    echo $this->formInput($descripcion);
    echo $this->formElementErrors($descripcion);
    echo $formLabel->closeTag();
?>
</div>
 
<div class="form_element">
<?php
    $tipoDeCampo = $form->get('tipo_de_campo');
    echo $formLabel->openTag().$tipoDeCampo->getOption('label')." ";
    echo $this->formInput($tipoDeCampo);
    echo $this->formElementErrors($tipoDeCampo);
    echo $formLabel->closeTag();
?>
</div>
<?php
echo $this->formElement($form->get('submit'));
echo $this->form()->closeTag();
?>