<h1>Propiedades de Empresa o Liquidación</h1>
<?php
$flash=$this->flashMessenger()
            ->setMessageOpenFormat('<div%s>')
            ->setMessageSeparatorString('')
            ->setMessageCloseString('</div>');
?>
<table class="table">
    <tr>
        <td colspan="7">
            <a class="btn btn-success" href="<?=$this->basePath()?>/propiedades/add">Añadir propiedad</a>
              <?php echo $flash->render('add_correcto',array('btn', 'btn-success'));?>
              <?php echo $flash->render('eliminado',array('btn', 'btn-success'));?>
        </td>
    </tr>
    <tr>
        <th>ID</th>
        <th>Propiedad</th>
        <th>Ver</th>
        <th>Modificar</th>
        <th>Eliminar</th>
    </tr>
    <?php foreach($lista as $empresaLiquidacion){ ?>
    <tr style="background-color:<?php echo $this->cycle(array("#F0F0F0","#FFFFFF"))->next()?>">
        <td><?=$empresaLiquidacion["id"]?></td>
        <td><?=$empresaLiquidacion["descripcion"]?></td>
        <td><?=$empresaLiquidacion["tipo_de_campo"]?></td>
        <td><a class="btn btn-success" href="<?=$this->basePath()?>/propiedades/ver/<?=$empresaLiquidacion["id"]?>">Ver</a></td>
        <td><a class="btn btn-primary" href="<?=$this->basePath()?>/propiedades/modificar/<?=$empresaLiquidacion["id"]?>">Modificación</a></td>
        <td><a class="btn btn-danger" href="<?=$this->basePath()?>/propiedades/eliminar/<?=$empresaLiquidacion["id"]?>">Baja</a></td>
    </tr>
    <?php } ?>
</table>