<?php
$title = 'Definición de datos de Empresas';
?>
<h1 class="page-header" style="padding-top:20px"><?php echo $this->escapeHtml($title); ?></h1>
<?php
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
            &times;
            </button>
        <ul><li>')
        ->setMessageSeparatorString('</li><li>')
        ->setMessageCloseString('</li></ul></div>');

echo $flash->render('error', array('alert', 'alert-dismissable', 'alert-danger', 'flashAlert'));
echo $flash->render('info', array('alert', 'alert-dismissable', 'alert-info', 'flashAlert'));
echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning', 'flashAlert'));
echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success', 'flashAlert'));
?>

<script type="text/javascript" src="../js/jqueryValidation/dist/jquery.validate.min.js"></script>    
<script type="text/javascript" src="../js/jqueryValidation/dist/additional-methods.min.js"></script>  
<script type="text/javascript" src="../js/jqueryValidation/dist/localization/messages_es_AR.min.js"></script>  

<div class="alert alert-warning ui-state-highlight ui-corner-all" id="diagAlertMain">
    <a href="#" class="close" data-dismiss="alert">&times;</a>
    <strong><span class="dataAlertMain"></span></strong>
</div>

<br>
<div class="content">
    <div class="row">
        <div class="col-xs-6">
            <div class="btn-group">
                <button type="button" class="btn btn-primary btn-lg" id="btnAddDatosEmpresa">Alta</button>
                <button type="button" class="btn btn-primary btn-lg" id="btnDelDatosEmpresa">Baja</button>
                <button type="button" class="btn btn-primary btn-lg" id="btnEditDatosEmpresa">Modificación</button>
            </div>
            <br>
            <div id="jqGridDatosEmpresa" style="padding-top:10px;">
                <table id="gridDatosEmpresa"></table>
                <div id="pagerDatosEmpresa"></div>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="btn-group">
                <button type="button" class="btn btn-primary btn-lg" id="btnAddDatosEmpresaVal">Alta</button>
                <button type="button" class="btn btn-primary btn-lg" id="btnDelDatosEmpresaVal">Baja</button>
                <button type="button" class="btn btn-primary btn-lg" id="btnEditDatosEmpresaVal">Modificación</button>
            </div>
            <br>
            <div id="jqGridDatosEmpresaVal" style="padding-top:10px;">
                <table id="gridDatosEmpresaVal"></table>
                <div id="pagerDatosEmpresaVal"></div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        //Grids
        $("#gridDatosEmpresa").jqGrid({
            width: 100,
            height: 230,
            autowidth: true,
            rowNum: 1000,
            rownumbers: true,
            url: "<?php echo $this->url('datosempresas', array('action' => 'loadDataGrid')); ?>",
            datatype: 'json',
            mtype: 'POST',
            colNames: ["Id", "Propiedad", "Tipo"],
            colModel: [
                {name: 'id', index: 'id',
                    width: 10,
                    align: "center",
                    sortable: false,
                    sorttype: 'int',
                    hidden: true
                },
                {name: 'descripcion', index: 'descripcion',
                    width: 30,
                    align: "center",
                    sortable: true,
                    sorttype: 'text',
                    search: true,
                    stype: 'text',
                    searchoptions: {clearSearch: true}
                },
                {name: 'tipo_de_campo', index: 'tipo_de_campo',
                    width: 5,
                    align: "center",
                    sortable: true,
                    sorttype: 'text',
                    search: true,
                    stype: 'select',
                    searchoptions: {value: ":;C:Caracter;N:Numero;F:Fecha"}
                }
            ],
            pager: "#pagerDatosEmpresa",
            sortname: "id",
            sortorder: "ASC",
            viewrecords: true,
            viewsortcols: [true, 'horizontal', true],
            gridview: true,
            hidegrid: false,
            ignoreCase: true,
            autoencode: true,
            forceFit: false,
            pgbuttons: false,
            pgtext: false,
            pginput: false,
            loadonce: true,
            editurl: "<?php echo $this->url('datosempresas', array('action' => 'editGridItem')); ?>",
            caption: "Datos de Empresa",
            onSelectRow: function (id) {
                loadGridDatosEmpresaVal(id);
            }
        });
        $("#gridDatosEmpresa").navGrid("#pagerDatosEmpresa",
                {edit: false, add: false, del: false, search: false, refresh: false, view: false});
        $("#gridDatosEmpresa").navButtonAdd("#pagerDatosEmpresa", {
            caption: "Borrar filtros",
            title: "Borrar filtros",
            buttonicon: 'ui-icon-refresh',
            onClickButton: function () {
                jQuery("#gridDatosEmpresa")[0].clearToolbar();
                gridReload('gridDatosEmpresa');
            }
        });
        $('#gridDatosEmpresa').jqGrid('filterToolbar', {stringResult: true, searchOnEnter: false, autoSearch: false, defaultSearch: 'cn', ignoreCase: true});

        $("#gridDatosEmpresaVal").jqGrid({
            width: 450,
            height: 230,
            shrinkToFit: true,
            forceFit: false,
            autowidth: false,
            rowNum: 1000,
            rownumbers: true,
            url: "<?php echo $this->url('datosempresas', array('action' => 'loadDataGridVal')); ?>",
            datatype: "json",
            mtype: 'POST',
            colNames: ["Id", "PropiedadId", "Valor", "Significado"],
            colModel: [
                {name: 'id', index: 'id',
                    width: 10,
                    align: "center",
                    sortable: false,
                    sorttype: 'int',
                    hidden: true
                },
                {name: 'propiedad', index: 'propiedad',
                    width: 10,
                    align: "center",
                    sortable: true,
                    sorttype: 'int',
                    hidden: true
                },
                {name: 'valor_posible', index: 'valor_posible',
                    width: 15,
                    align: "center",
                    sortable: false,
                    sorttype: 'text',
                    search: true,
                    stype: 'text',
                    searchoptions: {clearSearch: true},
                    editable: true,
                    editrules: {required: true},
                    editoptions: {size: 30}
                },
                {name: 'significado', index: 'significado',
                    width: 15,
                    align: "center",
                    sortable: false,
                    sorttype: 'text',
                    search: true,
                    stype: 'text',
                    searchoptions: {clearSearch: true},
                    editable: true,
                    editrules: {required: true},
                    editoptions: {size: 30}
                }
            ],
            pager: "#pagerDatosEmpresaVal",
            sortname: "propiedad",
            sortorder: "ASC",
            viewrecords: true,
            viewsortcols: [true, 'horizontal', true],
            gridview: true,
            hidegrid: false,
            ignoreCase: true,
            autoencode: true,
            pgbuttons: false,
            pginput: false,
            loadonce: true,
            editurl: "<?php echo $this->url('datosempresas', array('action' => 'editGridItemVal')); ?>",
            caption: "Valores Posibles"
        });
        $("#gridDatosEmpresaVal").navGrid("#pagerDatosEmpresaVal",
                {edit: false, add: false, del: false, search: false, refresh: false, view: false});
        $("#gridDatosEmpresaVal").navButtonAdd("#pagerDatosEmpresaVal", {
            caption: "Borrar filtros",
            title: "Borrar filtros",
            buttonicon: 'ui-icon-refresh',
            onClickButton: function () {
                jQuery("#gridDatosEmpresaVal")[0].clearToolbar();
            }
        });
        $('#gridDatosEmpresaVal').jqGrid('filterToolbar', {stringResult: true, searchOnEnter: false, autoSearch: false, defaultSearch: 'cn', ignoreCase: true});

        //Buttons
        $("#btnAddDatosEmpresa").click(function () {
            openDiagDatosEmpresa("form-add-datosEmpresa", "add", "", "");
        });
        $("#btnDelDatosEmpresa").click(function () {
            var rowid = jQuery("#gridDatosEmpresa").jqGrid('getGridParam', 'selrow');
            if (rowid != null) {
                var ids = $("#gridDatosEmpresaVal").jqGrid('getDataIDs');
                ids = ids.toString();
                ids = ids.split(",");
                var e = 0;

                if (ids != "") {
                    for (var i = 0; i < ids.length; i++) {
                        var data = $("#gridDatosEmpresaVal").jqGrid('getRowData', ids[i]);
                        if (data['propiedad'] == rowid) {
                            e++;
                        }
                    }
                }

                if (e == 0) {
                    $.ajax({
                        url: "<?php echo $this->url('datosempresas', array('action' => 'deleteGridItem')); ?>",
                        global: false,
                        type: "POST",
                        data: "id=" + rowid,
                        dataType: "json",
                        async: false,
                        success: function (result) {
                            gridReload('gridDatosEmpresa');
                            gridReload('gridDatosEmpresaVal');
                        },
                        error: function (xhr, ajaxOptions, thrownError) {
                            alert(xhr.status + " " + thrownError);
                        }
                    });
                } else {
                    msgAlert("diagAlertMain", "dataAlertMain", "No se puede eliminar la propiedad porque tiene valores asociados.");
                }
            }
            else {
                msgAlert("diagAlertMain", "dataAlertMain", "Por favor seleccione una fila.");
            }
        });
        $("#btnEditDatosEmpresa").click(function () {
            var rowid = jQuery("#gridDatosEmpresa").jqGrid('getGridParam', 'selrow');
            if (rowid != null) {
                openDiagDatosEmpresa("form-edit-datosEmpresa", "edit", "gridDatosEmpresa", rowid);
            }
            else {
                msgAlert("diagAlertMain", "dataAlertMain", "Por favor seleccione una fila.");
            }
        });
        $("#btnAddDatosEmpresaVal").click(function () {
            var rowid = jQuery("#gridDatosEmpresa").jqGrid('getGridParam', 'selrow');
            var rowidVal = jQuery("#gridDatosEmpresaVal").jqGrid('getGridParam', 'selrow');
            if (rowid != null) {
                openDiagDatosEmpresaVal("form-add-datosEmpresaVal", "add", "gridDatosEmpresaVal", rowidVal);
            }
            else {
                msgAlert("diagAlertMain", "dataAlertMain", "Por favor seleccione una fila.");
            }
        });
        $("#btnDelDatosEmpresaVal").click(function () {
            var rowid = jQuery("#gridDatosEmpresaVal").jqGrid('getGridParam', 'selrow');
            if (rowid != null) {
                $.ajax({
                    url: "<?php echo $this->url('datosempresas', array('action' => 'deleteGridItemVal')); ?>",
                    global: false,
                    type: "POST",
                    data: "id=" + rowid,
                    dataType: "json",
                    async: false,
                    success: function () {
                        gridReload('gridDatosEmpresaVal');
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        alert(xhr.status + " " + thrownError);
                    }
                });
            }
            else {
                msgAlert("diagAlertMain", "dataAlertMain", "Por favor seleccione una fila.");
            }
        });
        $("#btnEditDatosEmpresaVal").click(function () {
            var rowid = jQuery("#gridDatosEmpresaVal").jqGrid('getGridParam', 'selrow');
            if (rowid != null) {
                openDiagDatosEmpresaVal("form-edit-datosEmpresaVal", "edit", "gridDatosEmpresaVal", rowid);
            }
            else {
                msgAlert("diagAlertMain", "dataAlertMain", "Por favor seleccione una fila.");
            }
        });

        //Dialog addDatosEmpresa
        $("#form-add-datosEmpresa").dialog({
            autoOpen: false,
            resizable: true,
            closeOnEscape: true,
            modal: true,
            width: 'auto', // overcomes width:'auto' and maxWidth bug
            height: 'auto',
            maxWidth: 600,
            buttons: {
                'Aceptar': function () {
                    if ($("#valid-form-add-datosEmpresa").valid()) {
                        var descripcion = $("#descripcionAddDatosEmpresa").val();
                        var tipo = $("#tipoAddDatosEmpresa").val();

                        var ids = $("#gridDatosEmpresa").jqGrid('getDataIDs');
                        ids = ids.toString();
                        ids = ids.split(",");
                        var e = 0;

                        if (ids != "") {
                            for (var i = 0; i < ids.length; i++) {
                                var data = $("#gridDatosEmpresa").jqGrid('getRowData', ids[i]);
                                if (data['descripcion'].toLowerCase() == descripcion.toLowerCase()) {
                                    e++;
                                }
                            }
                        }

                        if (e == 0) {
                            var data = {
                                "descripcion": descripcion,
                                "tipo_de_campo": tipo
                            };
                            $.ajax({
                                url: "<?php echo $this->url('datosempresas', array('action' => 'editGridItem')); ?>",
                                global: false,
                                type: "POST",
                                data: "data=" + JSON.stringify(data),
                                dataType: "json",
                                async: false,
                                success: function (result) {
                                    gridReload('gridDatosEmpresa');
                                    $("#form-add-datosEmpresa").dialog('close');
                                },
                                error: function (xhr, ajaxOptions, thrownError) {
                                    alert(xhr.status + " " + thrownError);
                                }
                            });
                        } else {
                            msgAlert("diagAlertModalAddP", "dataAlertModalAddP", "Ya existe un registro con esa combinacion.");
                        }
                    }
                },
                'Cancelar': function () {
                    validFormAddDatosEmpresa.resetForm();
                    $(this).dialog('close');
                }
            },
            close: function () {
                validFormAddDatosEmpresa.resetForm();
            }
        });
        //Dialog editDatosEmpresa
        $("#form-edit-datosEmpresa").dialog({
            autoOpen: false,
            resizable: true,
            closeOnEscape: true,
            modal: true,
            width: 'auto', // overcomes width:'auto' and maxWidth bug
            height: 'auto',
            maxWidth: 600,
            buttons: {
                'Aceptar': function () {
                    if ($("#valid-form-edit-datosEmpresa").valid()) {
                        var rowid = jQuery("#gridDatosEmpresa").jqGrid('getGridParam', 'selrow');
                        if (rowid != null) {
                            var ids = $("#gridDatosEmpresa").jqGrid('getDataIDs');
                            ids = ids.toString();
                            ids = ids.split(",");
                            var e = 0;

                            if (ids != "") {
                                for (var i = 0; i < ids.length; i++) {
                                    var data = $("#gridDatosEmpresa").jqGrid('getRowData', ids[i]);
                                    if (data['descripcion'].toLowerCase() == $("#descripcionEditDatosEmpresa").val().toLowerCase() && data['id'] != rowid) {
                                        e++;
                                    }
                                }
                            }

                            if (e == 0)
                            {
                                var data = {
                                    "id": rowid,
                                    "descripcion": $("#descripcionEditDatosEmpresa").val(),
                                    "tipo_de_campo": $("#tipoEditDatosEmpresa").val()
                                };
                                $.ajax({
                                    url: "<?php echo $this->url('datosempresas', array('action' => 'editGridItem')); ?>",
                                    global: false,
                                    type: "POST",
                                    data: "data=" + JSON.stringify(data),
                                    dataType: "json",
                                    async: false,
                                    success: function (result) {
                                        gridReload('gridDatosEmpresa');
                                        $("#form-edit-datosEmpresa").dialog('close');
                                    },
                                    error: function (xhr, ajaxOptions, thrownError) {
                                        alert(xhr.status + " " + thrownError);
                                    }
                                });
                            } else {
                                msgAlert("diagAlertModalEditP", "dataAlertModalEditP", "Ya existe un registro con esa combinacion.");
                            }
                        }
                    }
                },
                'Cancelar': function () {
                    validFormEditDatosEmpresa.resetForm();
                    $(this).dialog('close');
                }
            },
            close: function () {
                validFormEditDatosEmpresa.resetForm();
            }
        });
        //Dialog addDatosEmpresaVal
        $("#form-add-datosEmpresaVal").dialog({
            autoOpen: false,
            resizable: true,
            closeOnEscape: true,
            modal: true,
            width: 'auto', // overcomes width:'auto' and maxWidth bug
            height: 'auto',
            maxWidth: 600,
            buttons: {
                'Aceptar': function () {
                    if ($("#valid-form-add-datosEmpresaVal").valid()) {
                        var rowid = jQuery("#gridDatosEmpresa").jqGrid('getGridParam', 'selrow');
                        var ids = $("#gridDatosEmpresaVal").jqGrid('getDataIDs');
                        ids = ids.toString();
                        ids = ids.split(",");
                        var e = 0;

                        if (ids != "") {
                            for (var i = 0; i < ids.length; i++) {
                                var data = $("#gridDatosEmpresaVal").jqGrid('getRowData', ids[i]);
                                if (data['propiedad'] == rowid && data['valor_posible'].toLowerCase() == $("#valorPosibleAddDatosEmpresaVal").val().toLowerCase()) {
                                    e++;
                                }
                            }
                        }

                        if (e == 0)
                        {
                            var data = {
                                "propiedad": rowid,
                                "valor_posible": $("#valorPosibleAddDatosEmpresaVal").val(),
                                "significado": $("#significadoAddDatosEmpresaVal").val()
                            };
                            $.ajax({
                                url: "<?php echo $this->url('datosempresas', array('action' => 'editGridItemVal')); ?>",
                                global: false,
                                type: "POST",
                                data: "data=" + JSON.stringify(data),
                                dataType: "json",
                                async: false,
                                success: function () {
                                    loadGridDatosEmpresaVal(rowid);
                                    $("#form-add-datosEmpresaVal").dialog('close');
                                },
                                error: function (xhr, ajaxOptions, thrownError) {
                                    alert(xhr.status + " " + thrownError);
                                }
                            });
                        } else {
                            msgAlert("diagAlertModalAddPV", "dataAlertModalAddPV", "Ya existe un registro con esa combinacion.");
                        }
                    }
                },
                Cancel: function () {
                    validFormAddDatosEmpresaVal.resetForm();
                    $(this).dialog('close');
                }
            },
            close: function () {
                validFormAddDatosEmpresaVal.resetForm();
            }
        });
        //Dialog editDatosEmpresaVal
        $("#form-edit-datosEmpresaVal").dialog({
            autoOpen: false,
            resizable: true,
            closeOnEscape: true,
            modal: true,
            width: 'auto', // overcomes width:'auto' and maxWidth bug
            height: 'auto',
            maxWidth: 600,
            buttons: {
                'Aceptar': function () {
                    if ($("#valid-form-edit-datosEmpresaVal").valid()) {
                        var rowid = jQuery("#gridDatosEmpresaVal").jqGrid('getGridParam', 'selrow');
                        if (rowid != null) {
                            var dataGrid = $("#gridDatosEmpresaVal").jqGrid('getRowData', rowid);
                            var ids = $("#gridDatosEmpresaVal").jqGrid('getDataIDs');
                            ids = ids.toString();
                            ids = ids.split(",");
                            var e = 0;

                            if (ids != "") {
                                for (var i = 0; i < ids.length; i++) {
                                    var data = $("#gridDatosEmpresaVal").jqGrid('getRowData', ids[i]);
                                    if (data['valor_posible'].toLowerCase() == $("#valorPosibleEditDatosEmpresaVal").val().toLowerCase() && data['id'] != rowid) {
                                        e++;
                                    }
                                }
                            }

                            if (e == 0)
                            {
                                var data = {
                                    "id": rowid,
                                    "valor_posible": $("#valorPosibleEditDatosEmpresaVal").val(),
                                    "significado": $("#significadoEditDatosEmpresaVal").val()
                                };
                                $.ajax({
                                    url: "<?php echo $this->url('datosempresas', array('action' => 'editGridItemVal')); ?>",
                                    global: false,
                                    type: "POST",
                                    data: "data=" + JSON.stringify(data),
                                    dataType: "json",
                                    async: false,
                                    success: function (result) {
                                        loadGridDatosEmpresaVal(dataGrid.propiedad);
                                        $("#form-edit-datosEmpresaVal").dialog('close');
                                    },
                                    error: function (xhr, ajaxOptions, thrownError) {
                                        alert(xhr.status + " " + thrownError);
                                    }
                                });
                            } else {
                                msgAlert("diagAlertModalEditPV", "dataAlertModalEditPV", "Ya existe un registro con esa combinacion.");
                            }
                        }
                    }
                },
                Cancel: function () {
                    validFormEditDatosEmpresaVal.resetForm();
                    $(this).dialog('close');
                }
            },
            close: function () {
                validFormEditDatosEmpresaVal.resetForm();
            }
        });

        //Validation
        var validFormAddDatosEmpresa = $("#valid-form-add-datosEmpresa").validate({
            rules: {
                descripcionAddDatosEmpresa: {required: true}
            }
        });
        var validFormEditDatosEmpresa = $("#valid-form-edit-datosEmpresa").validate({
            rules: {
                descripcionEditDatosEmpresa: {required: true}
            }
        });
        var validFormAddDatosEmpresaVal = $("#valid-form-add-datosEmpresaVal").validate({
            rules: {
                valorPosibleAddDatosEmpresaVal: {required: true},
                significadoAddDatosEmpresaVal: {required: true}
            }
        });
        var validFormEditDatosEmpresaVal = $("#valid-form-edit-datosEmpresaVal").validate({
            rules: {
                valorPosibleEditDatosEmpresaVal: {required: true},
                significadoEditDatosEmpresaVal: {required: true}
            }
        });

        //AlertManager
        $('#diagAlertMain').on('closed.bs.alert', function () {
            $('.dataAlertMain').html("");
        });
        $('#diagAlertModalAddP').on('closed.bs.alert', function () {
            $('.dataAlertModalAddP').html("");
        });
        $('#diagAlertModalEditP').on('closed.bs.alert', function () {
            $('.dataAlertModalEditP').html("");
        });
        $('#diagAlertModalAddPV').on('closed.bs.alert', function () {
            $('.dataAlertModalAddPV').html("");
        });
        $('#diagAlertModalEditPV').on('closed.bs.alert', function () {
            $('.dataAlertModalEditPV').html("");
        });
    });

    // remove window resize namespace
    $(document).on("dialogclose", ".ui-dialog", function (event, ui) {
        $(window).off("resize.responsive");
    });

    function gridReload(gridName) {
        $("#" + gridName).setGridParam({datatype: 'json'})/*.setGridParam({rowNum: 1000})*/.trigger('reloadGrid');
    }

    function loadGridDatosEmpresaVal(id) {
        if (id != null) {
            var sUrl = "<?php echo $this->url('datosempresas', array('action' => 'loadDataGridVal')); ?>" + "/" + id;
            $("#gridDatosEmpresaVal").setGridParam({datatype: 'json', url: sUrl}).trigger('reloadGrid');
        }
        else {
            msgAlert("diagAlertMain", "dataAlertMain", "Por favor seleccione una fila.");
        }
    }

    function openDiagDatosEmpresa(diagName, op, grid, id) {
        clearDataDatosEmpresa();
        if (op == "edit") {
            rowdata = jQuery("#" + grid).getRowData(id);
            $('#descripcionEditDatosEmpresa').val(rowdata['descripcion']);
            $('#tipoEditDatosEmpresa').val(rowdata['tipo_de_campo']);
            $('#' + diagName).dialog('open');
        } else {
            $('#' + diagName).dialog('open');
            $('#tipoAddDatosEmpresa option:contains("C")').prop('selected', true);
        }
    }

    function openDiagDatosEmpresaVal(diagName, op, grid, id) {
        clearDataDatosEmpresaVal();
        if (op == "edit") {
            rowdata = jQuery("#" + grid).getRowData(id);
            $('#valorPosibleEditDatosEmpresaVal').val(rowdata['valor_posible']);
            $('#significadoEditDatosEmpresaVal').val(rowdata['significado']);
            $('#' + diagName).dialog('open');
        } else {
            $('#' + diagName).dialog('open');
        }
    }

    function clearDataDatosEmpresa() {
        $('#descripcionAddDatosEmpresa').val("");
        $('#descripcionEditDatosEmpresa').val("");
    }

    function clearDataDatosEmpresaVal() {
        $('#valorPosibleAddDatosEmpresaVal').val("");
        $('#significadoAddDatosEmpresaVal').val("");
        $('#valorPosibleEditDatosEmpresaVal').val("");
        $('#significadoEditDatosEmpresaVal').val("");
    }

    function msgAlert(diagName, selectorName, msg) {
        $('#' + diagName).show();
        $('.' + selectorName).html(msg);
        setTimeout(function () {
            $('#' + diagName).hide("drop", {direction: "up"}, "slow");
            $('.' + selectorName).html("");
        }, 3000);
        return;
    }

</script>

<!-- Dialogo form-add-datosEmpresa -->
<div id="form-add-datosEmpresa"  title="Agregar registro">
    <form class="form-horizontal" id="valid-form-add-datosEmpresa" role="form">
        <div class="form-group">
            <label for="descripcionAddDatosEmpresa" class="col-sm-4 control-label">Nombre de campo:</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="descripcionAddDatosEmpresa" name="descripcionAddDatosEmpresa" placeholder="">
            </div>
        </div>
        <div class="form-group">
            <label for="tipoAddDatosEmpresa" class="col-sm-4 control-label">Tipo:</label>
            <div class="col-sm-8">
                <select class="form-control" id="tipoAddDatosEmpresa" name="tipoAddDatosEmpresa">
                    <option value="C">Caracter</option>
                    <option value="N">Numero</option>
                    <option value="F">Fecha</option>
                </select>
            </div>
        </div>
    </form>
    <div class="alert alert-warning ui-state-highlight ui-corner-all" id="diagAlertModalAddP">
        <a href="#" class="close" data-dismiss="alert">&times;</a>
        <strong><span class="dataAlertModalAddP"></span></strong>
    </div>
</div>

<!-- Dialogo form-edit-datosEmpresa -->
<div id="form-edit-datosEmpresa"  title="Editar registro">
    <form class="form-horizontal" id="valid-form-edit-datosEmpresa" role="form">
        <div class="form-group">
            <label for="descripcionEditDatosEmpresa" class="col-sm-4 control-label">Nombre de campo:</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="descripcionEditDatosEmpresa" name="descripcionEditDatosEmpresa" placeholder="">
            </div>
        </div>
        <div class="form-group">
            <label for="tipoEditDatosEmpresa" class="col-sm-4 control-label">Tipo:</label>
            <div class="col-sm-8">
                <select class="form-control" id="tipoEditDatosEmpresa" name="tipoEditDatosEmpresa">
                    <option value="C">Caracter</option>
                    <option value="N">Numero</option>
                    <option value="F">Fecha</option>
                </select>
            </div>
        </div>
    </form>
    <div class="alert alert-warning ui-state-highlight ui-corner-all" id="diagAlertModalEditP">
        <a href="#" class="close" data-dismiss="alert">&times;</a>
        <strong><span class="dataAlertModalEditP"></span></strong>
    </div>
</div>

<!-- Dialogo form-add-datosEmpresaVal -->
<div id="form-add-datosEmpresaVal"  title="Agregar registro">
    <form class="form-horizontal" id="valid-form-add-datosEmpresaVal" role="form">
        <div class="form-group">
            <label for="valorPosibleAddDatosEmpresaVal" class="col-sm-4 control-label">Valor:</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="valorPosibleAddDatosEmpresaVal" name="valorPosibleAddDatosEmpresaVal" placeholder="">
            </div>
        </div>
        <div class="form-group">
            <label for="significadoAddDatosEmpresaVal" class="col-sm-4 control-label">Significado:</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="significadoAddDatosEmpresaVal" name="significadoAddDatosEmpresaVal" placeholder="">
            </div>
        </div>
    </form>
    <div class="alert alert-warning ui-state-highlight ui-corner-all" id="diagAlertModalAddPV">
        <a href="#" class="close" data-dismiss="alert">&times;</a>
        <strong><span class="dataAlertModalAddPV"></span></strong>
    </div>
</div>

<!-- Dialogo form-edit-datosEmpresaVal -->
<div id="form-edit-datosEmpresaVal"  title="Editar registro">
    <form class="form-horizontal" id="valid-form-edit-datosEmpresaVal" role="form">
        <div class="form-group">
            <label for="valorPosibleEditDatosEmpresaVal" class="col-sm-4 control-label">Valor:</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="valorPosibleEditDatosEmpresaVal" name="valorPosibleEditDatosEmpresaVal" placeholder="">
            </div>
        </div>
        <div class="form-group">
            <label for="significadoEditDatosEmpresaVal" class="col-sm-4 control-label">Significado:</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="significadoEditDatosEmpresaVal" name="significadoEditDatosEmpresaVal" placeholder="">
            </div>
        </div>
    </form>
    <div class="alert alert-warning ui-state-highlight ui-corner-all" id="diagAlertModalEditPV">
        <a href="#" class="close" data-dismiss="alert">&times;</a>
        <strong><span class="dataAlertModalEditPV"></span></strong>
    </div>
</div>