<?php
$title = 'Definición de datos de Empresas';
?>
<h1 class="page-header" style="padding-top:20px"><?php echo $this->escapeHtml($title); ?></h1>
<?php
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
            &times;
            </button>
        <ul><li>')
        ->setMessageSeparatorString('</li><li>')
        ->setMessageCloseString('</li></ul></div>');

echo $flash->render('error', array('alert', 'alert-dismissable', 'alert-danger', 'flashAlert'));
echo $flash->render('info', array('alert', 'alert-dismissable', 'alert-info', 'flashAlert'));
echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning', 'flashAlert'));
echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success', 'flashAlert'));
?>

<div class="alert alert-warning" id="diagAlert">
    <a href="#" class="close" data-dismiss="alert">&times;</a>
    <strong><span class="dataAlert"></span></strong>
</div>

<br>
<div class="content">
    <div class="row">
        <div class="col-xs-6">
            <div class="btn-group">
                <button type="button" class="btn btn-primary btn-lg" id="btnAddDatosEmpresa">Alta</button>
                <button type="button" class="btn btn-primary btn-lg" id="btnDelDatosEmpresa">Baja</button>
                <button type="button" class="btn btn-primary btn-lg" id="btnEditDatosEmpresa">Modificación</button>
            </div>
            <br>
            <div id="jqGridDatosEmpresa" style="padding-top:10px;">
                <table id="gridDatosEmpresa"></table>
                <div id="pagerDatosEmpresa"></div>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="btn-group">
                <button type="button" class="btn btn-primary btn-lg" id="btnAddDatosEmpresaVal">Alta</button>
                <button type="button" class="btn btn-primary btn-lg" id="btnDelDatosEmpresaVal">Baja</button>
                <button type="button" class="btn btn-primary btn-lg" id="btnEditDatosEmpresaVal">Modificación</button>
            </div>
            <br>
            <div id="jqGridDatosEmpresaVal" style="padding-top:10px;">
                <table id="gridDatosEmpresaVal"></table>
                <div id="pagerDatosEmpresaVal"></div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        //Grids
        $("#gridDatosEmpresa").jqGrid({
            width: 100,
            height: 230,
            autowidth: true,
            rownumbers: true,
            url: "<?php echo $this->url('datosempresas', array('action' => 'loadDataGrid')); ?>",
            datatype: 'json',
            mtype: 'POST',
            colNames: ["Id", "Propiedad", "Tipo"],
            colModel: [
                {name: 'id', index: 'id',
                    width: 10,
                    align: "center",
                    sortable: false,
                    sorttype: 'int',
                    hidden: true
                },
                {name: 'descripcion', index: 'descripcion',
                    width: 30,
                    align: "center",
                    sortable: true,
                    sorttype: 'text',
                    search: true,
                    stype: 'text',
                    searchoptions: {clearSearch: true}
                },
                {name: 'tipo_de_campo', index: 'tipo_de_campo',
                    width: 5,
                    align: "center",
                    sortable: true,
                    sorttype: 'text',
                    search: true,
                    stype: 'select',
                    searchoptions: {value: ":;C:Caracter;N:Numero;F:Fecha"}
                }
            ],
            pager: "#pagerDatosEmpresa",
            sortname: "id",
            sortorder: "ASC",
            viewrecords: true,
            viewsortcols: [true, 'horizontal', true],
            gridview: true,
            hidegrid: false,
            ignoreCase: true,
            autoencode: true,
            forceFit: false,
            pgbuttons: false,
            pgtext: false,
            pginput: false,
            loadonce: true,
            editurl: "<?php echo $this->url('datosempresas', array('action' => 'editGridItem')); ?>",
            caption: "Datos de Empresa",
            onSelectRow: function (id) {
                loadGridDatosEmpresaVal(id);
            }
        });
        $("#gridDatosEmpresa").navGrid("#pagerDatosEmpresa",
                {edit: false, add: false, del: false, search: false, refresh: false, view: false});
        $("#gridDatosEmpresa").navButtonAdd("#pagerDatosEmpresa", {
            caption: "Borrar filtros",
            title: "Borrar filtros",
            buttonicon: 'ui-icon-refresh',
            onClickButton: function () {
                jQuery("#gridDatosEmpresa")[0].clearToolbar();
                gridReload('gridDatosEmpresa');
            }
        });
        $('#gridDatosEmpresa').jqGrid('filterToolbar', {stringResult: true, searchOnEnter: false, autoSearch: false, defaultSearch: 'cn', ignoreCase: true});

        $("#gridDatosEmpresaVal").jqGrid({
            width: 450,
            height: 230,
            shrinkToFit: true,
            forceFit: false,
            autowidth: false,
            rownumbers: true,
            url: "<?php echo $this->url('datosempresas', array('action' => 'loadDataGridVal')); ?>",
            datatype: "json",
            mtype: 'POST',
            colNames: ["Id", "PropiedadId", "Valor", "Significado"],
            colModel: [
                {name: 'id', index: 'id',
                    width: 10,
                    align: "center",
                    sortable: false,
                    sorttype: 'int',
                    hidden: true
                },
                {name: 'propiedad', index: 'propiedad',
                    width: 10,
                    align: "center",
                    sortable: true,
                    sorttype: 'int',
                    hidden: true
                },
                {name: 'valor_posible', index: 'valor_posible',
                    width: 15,
                    align: "center",
                    sortable: false,
                    sorttype: 'text',
                    search: true,
                    stype: 'text',
                    searchoptions: {clearSearch: true},
                    editable: true,
                    editrules: {required: true},
                    editoptions: {size: 30}
                },
                {name: 'significado', index: 'significado',
                    width: 15,
                    align: "center",
                    sortable: false,
                    sorttype: 'text',
                    search: true,
                    stype: 'text',
                    searchoptions: {clearSearch: true},
                    editable: true,
                    editrules: {required: true},
                    editoptions: {size: 30}
                }
            ],
            pager: "#pagerDatosEmpresaVal",
            sortname: "propiedad",
            sortorder: "ASC",
            viewrecords: true,
            viewsortcols: [true, 'horizontal', true],
            gridview: true,
            hidegrid: false,
            ignoreCase: true,
            autoencode: true,
            pgbuttons: false,
            pginput: false,
            loadonce: true,
            editurl: "<?php echo $this->url('datosempresas', array('action' => 'editGridItemVal')); ?>",
            caption: "Valores Posibles"
        });
        $("#gridDatosEmpresaVal").navGrid("#pagerDatosEmpresaVal",
                {edit: false, add: false, del: false, search: false, refresh: false, view: false});
        $("#gridDatosEmpresaVal").navButtonAdd("#pagerDatosEmpresaVal", {
            caption: "Borrar filtros",
            title: "Borrar filtros",
            buttonicon: 'ui-icon-refresh',
            onClickButton: function () {
                jQuery("#gridDatosEmpresaVal")[0].clearToolbar();
            }
        });
        $('#gridDatosEmpresaVal').jqGrid('filterToolbar', {stringResult: true, searchOnEnter: false, autoSearch: false, defaultSearch: 'cn', ignoreCase: true});

        //Buttons
        $("#btnAddDatosEmpresa").click(function () {
            openDiagDatosEmpresa("form-add-DatosEmpresa", "add", "", "");
        });
        $("#btnDelDatosEmpresa").click(function () {
            var rowid = jQuery("#gridDatosEmpresa").jqGrid('getGridParam', 'selrow');
            if (rowid != null) {
                var ids = $("#gridDatosEmpresaVal").jqGrid('getDataIDs');
                ids = ids.toString();
                ids = ids.split(",");
                var e = 0;
                
                if( ids != ""){
                    for (var i = 0; i < ids.length; i++) {
                        var data = $("#gridDatosEmpresaVal").jqGrid('getRowData', ids[i]);
                        if (data['propiedad'] == rowid) {
                            e++;
                        }
                    }
                }

                if (e == 0) {
                    $.ajax({
                        url: "<?php echo $this->url('datosempresas', array('action' => 'deleteGridItem')); ?>",
                        global: false,
                        type: "POST",
                        data: "id=" + rowid,
                        dataType: "json",
                        async: false,
                        success: function (msg) {
                            gridReload('gridDatosEmpresa');
                            gridReload('gridDatosEmpresaVal');
                        }
                    });
                } else {
                    msgAlert("diagAlert", "dataAlert", "No se puede eliminar la propiedad porque tiene valores asociados.");
                }
            }
            else {
                msgAlert("diagAlert", "dataAlert", "Por favor seleccione una fila.");
            }
        });
        $("#btnEditDatosEmpresa").click(function () {
            var rowid = jQuery("#gridDatosEmpresa").jqGrid('getGridParam', 'selrow');
            if (rowid != null) {
                openDiagDatosEmpresa("form-edit-DatosEmpresa", "edit", "gridDatosEmpresa", rowid);
            }
            else {
                msgAlert("diagAlert", "dataAlert", "Por favor seleccione una fila.");
            }
        });
        $("#btnAddDatosEmpresaVal").click(function () {
            var rowid = jQuery("#gridDatosEmpresa").jqGrid('getGridParam', 'selrow');
            var rowidVal = jQuery("#gridDatosEmpresaVal").jqGrid('getGridParam', 'selrow');
            if (rowid != null) {
                openDiagDatosEmpresaVal("form-add-DatosEmpresaVal", "add", "gridDatosEmpresaVal", rowidVal);
            }
            else {
                msgAlert("diagAlert", "dataAlert", "Por favor seleccione una fila.");
            }
        });
        $("#btnDelDatosEmpresaVal").click(function () {
            var rowid = jQuery("#gridDatosEmpresaVal").jqGrid('getGridParam', 'selrow');
            if (rowid != null) {
                $.ajax({
                    url: "<?php echo $this->url('datosempresas', array('action' => 'deleteGridItemVal')); ?>",
                    global: false,
                    type: "POST",
                    data: "id=" + rowid,
                    dataType: "json",
                    async: false,
                    success: function () {
                        gridReload('gridDatosEmpresaVal');
                    }
                });
            }
            else {
                msgAlert("diagAlert", "dataAlert", "Por favor seleccione una fila.");
            }
        });
        $("#btnEditDatosEmpresaVal").click(function () {
            var rowid = jQuery("#gridDatosEmpresaVal").jqGrid('getGridParam', 'selrow');
            if (rowid != null) {
                openDiagDatosEmpresaVal("form-edit-DatosEmpresaVal", "edit", "gridDatosEmpresaVal", rowid);
            }
            else {
                msgAlert("diagAlert", "dataAlert", "Por favor seleccione una fila.");
            }
        });

        //Dialog addDatosEmpresa
        $("#form-add-DatosEmpresa").dialog({
            autoOpen: false,
            resizable: true,
            closeOnEscape: true,
            modal: true,
            width: 'auto', // overcomes width:'auto' and maxWidth bug
            height: 'auto',
            maxWidth: 600,
            //fluid: true, //new option
            buttons: {
                'Aceptar': function () {
                    var descripcion = $("#descripcion-add-DatosEmpresa").val();
                    var tipo = $("#tipo-add-DatosEmpresa").val();

                    if (descripcion != '') {
                        var ids = $("#gridDatosEmpresa").jqGrid('getDataIDs');
                        ids = ids.toString();
                        ids = ids.split(",");
                        var e = 0;

                        if( ids != ""){
                            for (var i = 0; i < ids.length; i++) {
                                var data = $("#gridDatosEmpresa").jqGrid('getRowData', ids[i]);
                                if (data['descripcion'].toLowerCase() == descripcion.toLowerCase()) {
                                    e++;
                                }
                            }
                        }

                        if (e == 0) {
                            var data = {
                                "descripcion": descripcion,
                                "tipo_de_campo": tipo
                            };
                            $.ajax({
                                url: "<?php echo $this->url('datosempresas', array('action' => 'editGridItem')); ?>",
                                global: false,
                                type: "POST",
                                data: "data=" + JSON.stringify(data),
                                dataType: "json",
                                async: false,
                                success: function (msg) {
                                    gridReload('gridDatosEmpresa');
                                    $("#form-add-DatosEmpresa").dialog('close');
                                }
                            });
                        } else {
                            msgAlert("diagAlertModalAddE", "dataAlertModal", "Ya existe un registro con esa combinacion.");
                        }
                    }
                },
                'Cancelar': function () {
                    $(this).dialog('close');
                }
            },
            close: function () {
                //nada por ahora
            }
        });
        //Dialog editDatosEmpresa
        $("#form-edit-DatosEmpresa").dialog({
            autoOpen: false,
            resizable: true,
            closeOnEscape: true,
            modal: true,
            width: 'auto', // overcomes width:'auto' and maxWidth bug
            height: 'auto',
            maxWidth: 600,
            //fluid: true, //new option
            buttons: {
                'Aceptar': function () {
                    var rowid = jQuery("#gridDatosEmpresa").jqGrid('getGridParam', 'selrow');
                    if (rowid != null) {
                        var ids = $("#gridDatosEmpresa").jqGrid('getDataIDs');
                        ids = ids.toString();
                        ids = ids.split(",");
                        var e = 0;
                        
                        if( ids != ""){
                            for (var i = 0; i < ids.length; i++) {
                                var data = $("#gridDatosEmpresa").jqGrid('getRowData', ids[i]);
                                if (data['descripcion'].toLowerCase() == $("#descripcion-edit-DatosEmpresa").val().toLowerCase() && data['id'] != rowid) {
                                    e++;
                                }
                            }
                        }

                        if (e == 0)
                        {
                            var data = {
                                "id": rowid,
                                "descripcion": $("#descripcion-edit-DatosEmpresa").val(),
                                "tipo_de_campo": $("#tipo-edit-DatosEmpresa").val()
                            };
                            $.ajax({
                                url: "<?php echo $this->url('datosempresas', array('action' => 'editGridItem')); ?>",
                                global: false,
                                type: "POST",
                                data: "data=" + JSON.stringify(data),
                                dataType: "json",
                                async: false,
                                success: function (msg) {
                                    gridReload('gridDatosEmpresa');
                                    $("#form-edit-DatosEmpresa").dialog('close');
                                }
                            });
                        } else {
                            msgAlert("diagAlertModalEditE", "dataAlertModal", "Ya existe un registro con esa combinacion.");
                        }
                    }
                },
                'Cancelar': function () {
                    $(this).dialog('close');
                }
            },
            close: function () {
                //nada por ahora
            }
        });
        //Dialog addDatosEmpresaVal
        $("#form-add-DatosEmpresaVal").dialog({
            autoOpen: false,
            resizable: true,
            closeOnEscape: true,
            modal: true,
            width: 'auto', // overcomes width:'auto' and maxWidth bug
            height: 'auto',
            maxWidth: 600,
            //fluid: true, //new option
            buttons: {
                'Aceptar': function () {
                    var rowid = jQuery("#gridDatosEmpresa").jqGrid('getGridParam', 'selrow');
                    var ids = $("#gridDatosEmpresaVal").jqGrid('getDataIDs');
                    ids = ids.toString();
                    ids = ids.split(",");
                    var e = 0;
                    
                    if( ids != ""){
                        for (var i = 0; i < ids.length; i++) {
                            var data = $("#gridDatosEmpresaVal").jqGrid('getRowData', ids[i]);
                            if (data['propiedad'] == rowid && data['valor_posible'].toLowerCase() == $("#valor-posible-add-DatosEmpresaVal").val().toLowerCase()) {
                                e++;
                            }
                        }
                    }

                    if (e == 0)
                    {
                        var data = {
                            "propiedad": rowid,
                            "valor_posible": $("#valor-posible-add-DatosEmpresaVal").val(),
                            "significado": $("#significado-add-DatosEmpresaVal").val()
                        };
                        $.ajax({
                            url: "<?php echo $this->url('datosempresas', array('action' => 'editGridItemVal')); ?>",
                            global: false,
                            type: "POST",
                            data: "data=" + JSON.stringify(data),
                            dataType: "json",
                            async: false,
                            success: function () {
                                loadGridDatosEmpresaVal(rowid);
                                $("#form-add-DatosEmpresaVal").dialog('close');
                            }
                        });
                    } else {
                        msgAlert("diagAlertModalAddEV", "dataAlertModal", "Ya existe un registro con esa combinacion.");
                    }
                },
                Cancel: function () {
                    $(this).dialog('close');
                }
            },
            close: function () {
                //nada por ahora
            }
        });
        //Dialog editDatosEmpresaVal
        $("#form-edit-DatosEmpresaVal").dialog({
            autoOpen: false,
            resizable: true,
            closeOnEscape: true,
            modal: true,
            width: 'auto', // overcomes width:'auto' and maxWidth bug
            height: 'auto',
            maxWidth: 600,
            //fluid: true, //new option
            buttons: {
                'Aceptar': function () {
                    var rowid = jQuery("#gridDatosEmpresaVal").jqGrid('getGridParam', 'selrow');
                    if (rowid != null) {
                        var dataGrid = $("#gridDatosEmpresaVal").jqGrid('getRowData', rowid);
                        var ids = $("#gridDatosEmpresaVal").jqGrid('getDataIDs');
                        ids = ids.toString();
                        ids = ids.split(",");
                        var e = 0;
                        
                        if( ids != ""){
                            for (var i = 0; i < ids.length; i++) {
                                var data = $("#gridDatosEmpresaVal").jqGrid('getRowData', ids[i]);
                                if (data['valor_posible'].toLowerCase() == $("#valor-posible-edit-DatosEmpresaVal").val().toLowerCase() && data['id'] != rowid) {
                                    e++;
                                }
                            }
                        }

                        if (e == 0)
                        {
                            var data = {
                                "id": rowid,
                                "valor_posible": $("#valor-posible-edit-DatosEmpresaVal").val(),
                                "significado": $("#significado-edit-DatosEmpresaVal").val()
                            };
                            $.ajax({
                                url: "<?php echo $this->url('datosempresas', array('action' => 'editGridItemVal')); ?>",
                                global: false,
                                type: "POST",
                                data: "data=" + JSON.stringify(data),
                                dataType: "json",
                                async: false,
                                success: function (msg) {
                                    loadGridDatosEmpresaVal(dataGrid.propiedad);
                                    $("#form-edit-DatosEmpresaVal").dialog('close');
                                }
                            });
                        } else {
                            msgAlert("diagAlertModalEditEV", "dataAlertModal", "Ya existe un registro con esa combinacion.");
                        }
                    }
                },
                Cancel: function () {
                    $(this).dialog('close');
                }
            },
            close: function () {
                //nada por ahora
            }
        });

        /*$('input').bind('keypress', function (event) {
         var regex = new RegExp("^[a-zA-Z0-9_ \,._-]+$");
         var key = String.fromCharCode(!event.charCode ? event.which : event.charCode);
         if (!regex.test(key)) {
         event.preventDefault();
         return false;
         }
         });*/

        $('#diagAlert').on('closed.bs.alert', function () {
            $('.dataAlert').html("");
        });
        
        $('#diagAlertModalAddE').on('closed.bs.alert', function () {
            $('.dataAlertModal').html("");
        });
        
        $('#diagAlertModalEditE').on('closed.bs.alert', function () {
            $('.dataAlertModal').html("");
        });
        
        $('#diagAlertModalAddEV').on('closed.bs.alert', function () {
            $('.dataAlertModal').html("");
        });
        
        $('#diagAlertModalEditEV').on('closed.bs.alert', function () {
            $('.dataAlertModal').html("");
        });
    });

    //jqGrid responsive
    jQuery(window).bind('resize', function () {
        //$(".ui-dialog-content").dialog("option", "position", ['center', 'center']);
        // Get width of parent container
        var width = jQuery("#jqGridDatosEmpresa").attr('clientWidth');
        if (width == null || width < 1) {
            // For IE, revert to offsetWidth if necessary
            width = jQuery("#jqGridDatosEmpresa").attr('offsetWidth');
        }
        width = width - 2; // Fudge factor to prevent horizontal scrollbars
        if (width > 0 &&
                // Only resize if new width exceeds a minimal threshold
                // Fixes IE issue with in-place resizing when mousing-over frame bars
                Math.abs(width - jQuery("#gridDatosEmpresa").width()) > 5)
        {
            jQuery("#gridDatosEmpresa").setGridWidth(width);
            //jQuery("#gridDatosEmpresaVal").setGridWidth(width);
        }
    }).trigger('resize');

    /*// run function on all dialog opens
     $(document).on("dialogopen", ".ui-dialog", function (event, ui) {
     fluidDialog();
     });*/

    // remove window resize namespace
    $(document).on("dialogclose", ".ui-dialog", function (event, ui) {
        $(window).off("resize.responsive");
    });

    /*function fluidDialog() {
     var $visible = $(".ui-dialog:visible");
     // each open dialog
     $visible.each(function () {
     var $this = $(this);
     var dialog = $this.find(".ui-dialog-content").data("dialog");
     // if fluid option == true
     if (dialog.options.maxWidth && dialog.options.width) {
     // fix maxWidth bug
     $this.css("max-width", dialog.options.maxWidth);
     //reposition dialog
     dialog.option("position", dialog.options.position);
     }

     if (dialog.options.fluid) {
     // namespace window resize
     $(window).on("resize.responsive", function () {
     var wWidth = $(window).width();
     // check window width against dialog width
     if (wWidth < dialog.options.maxWidth + 50) {
     // keep dialog from filling entire screen
     $this.css("width", "90%");
     }
     //reposition dialog
     dialog.option("position", dialog.options.position);
     });
     }

     });
     }*/

    function gridReload(gridName) {
        $("#" + gridName).setGridParam({datatype: 'json'})/*.setGridParam({rowNum: 10})*/.trigger('reloadGrid');
    }

    function loadGridDatosEmpresaVal(id) {
        if (id != null) {
            var sUrl = "<?php echo $this->url('datosempresas', array('action' => 'loadDataGridVal')); ?>" + "/" + id;
            $("#gridDatosEmpresaVal").setGridParam({datatype: 'json', url: sUrl}).trigger('reloadGrid');
        }
        else {
            msgAlert("diagAlert", "dataAlert", "Por favor seleccione una fila.");
        }
    }

    function openDiagDatosEmpresa(diagName, op, grid, id) {
        clearDataDatosEmpresa();
        if (op == "edit") {
            rowdata = jQuery("#" + grid).getRowData(id);
            $('#descripcion-edit-DatosEmpresa').val(rowdata['descripcion']);
            $('#tipo-edit-DatosEmpresa').val(rowdata['tipo_de_campo']);
            $('#' + diagName).dialog('open');
        } else {
            $('#' + diagName).dialog('open');
            $('#tipo-add-DatosEmpresa option:contains("C")').prop('selected', true);
        }
    }

    function openDiagDatosEmpresaVal(diagName, op, grid, id) {
        clearDataDatosEmpresaVal();
        if (op == "edit") {
            rowdata = jQuery("#" + grid).getRowData(id);
            $('#valor-posible-edit-DatosEmpresaVal').val(rowdata['valor_posible']);
            $('#significado-edit-DatosEmpresaVal').val(rowdata['significado']);
            $('#' + diagName).dialog('open');
        } else {
            $('#' + diagName).dialog('open');
        }
    }

    function clearDataDatosEmpresa() {
        $('#descripcion-add-DatosEmpresa').val("");
        $('#descripcion-edit-DatosEmpresa').val("");
    }

    function clearDataDatosEmpresaVal() {
        $('#valor-posible-add-DatosEmpresaVal').val("");
        $('#significado-add-DatosEmpresaVal').val("");
        $('#valor-posible-edit-DatosEmpresaVal').val("");
        $('#significado-edit-DatosEmpresaVal').val("");
    }

    function msgAlert(diagName, selectorName, msg) {
        $('#' + diagName).show();
        $('.' + selectorName).html(msg);
        setTimeout(function () {
            $('#' + diagName).hide("drop", {direction: "up"}, "slow");
            $('.' + selectorName).html("");
        }, 3000);
        return;
    }

</script>

<!-- Dialogo form-add-DatosEmpresa -->
<div id="form-add-DatosEmpresa"  title="Agregar registro">
    <form class="form-horizontal" id="valid-form-add-DatosEmpresa" role="form">
        <div class="form-group">
            <label for="input-descripcion-add-DatosEmpresa" class="col-sm-4 control-label">Nombre de campo:</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="descripcion-add-DatosEmpresa" placeholder="">
            </div>
        </div>
        <div class="form-group">
            <label for="input-tipo-add-DatosEmpresa" class="col-sm-4 control-label">Tipo:</label>
            <div class="col-sm-8">
                <select class="form-control" id="tipo-add-DatosEmpresa">
                    <option value="C">Caracter</option>
                    <option value="N">Numero</option>
                    <option value="F">Fecha</option>
                </select>
            </div>
        </div>
    </form>
    <div class="alert alert-warning" id="diagAlertModalAddE">
        <a href="#" class="close" data-dismiss="alert">&times;</a>
        <strong><span class="dataAlertModal"></span></strong>
    </div>
</div>

<!-- Dialogo form-edit-DatosEmpresa -->
<div id="form-edit-DatosEmpresa"  title="Editar registro">
    <form class="form-horizontal" id="valid-form-edit-DatosEmpresa" role="form">
        <div class="form-group">
            <label for="input-descripcion-edit-DatosEmpresa" class="col-sm-4 control-label">Nombre de campo:</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="descripcion-edit-DatosEmpresa" placeholder="">
            </div>
        </div>
        <div class="form-group">
            <label for="input-tipo-edit-DatosEmpresa" class="col-sm-4 control-label">Tipo:</label>
            <div class="col-sm-8">
                <select class="form-control" id="tipo-edit-DatosEmpresa">
                    <option value="C">Caracter</option>
                    <option value="N">Numero</option>
                    <option value="F">Fecha</option>
                </select>
            </div>
        </div>
    </form>
    <div class="alert alert-warning" id="diagAlertModalEditE">
        <a href="#" class="close" data-dismiss="alert">&times;</a>
        <strong><span class="dataAlertModal"></span></strong>
    </div>
</div>

<!-- Dialogo form-add-DatosEmpresaVal -->
<div id="form-add-DatosEmpresaVal"  title="Agregar registro">
    <form class="form-horizontal" id="valid-form-add-DatosEmpresaVal" role="form">
        <div class="form-group">
            <label for="input-valor-posible-add-DatosEmpresaVal" class="col-sm-4 control-label">Valor:</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="valor-posible-add-DatosEmpresaVal" placeholder="">
            </div>
        </div>
        <div class="form-group">
            <label for="input-significado-add-DatosEmpresaVal" class="col-sm-4 control-label">Significado:</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="significado-add-DatosEmpresaVal" placeholder="">
            </div>
        </div>
    </form>
    <div class="alert alert-warning" id="diagAlertModalAddEV">
        <a href="#" class="close" data-dismiss="alert">&times;</a>
        <strong><span class="dataAlertModal"></span></strong>
    </div>
</div>

<!-- Dialogo form-add-DatosEmpresaVal -->
<div id="form-edit-DatosEmpresaVal"  title="Editar registro">
    <form class="form-horizontal" id="valid-form-edit-DatosEmpresaVal" role="form">
        <div class="form-group">
            <label for="input-valor-posible-edit-DatosEmpresaVal" class="col-sm-4 control-label">Valor:</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="valor-posible-edit-DatosEmpresaVal" placeholder="">
            </div>
        </div>
        <div class="form-group">
            <label for="input-significado-edit-DatosEmpresaVal" class="col-sm-4 control-label">Significado:</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="significado-edit-DatosEmpresaVal" placeholder="">
            </div>
        </div>
    </form>
    <div class="alert alert-warning" id="diagAlertModalEditE">
        <a href="#" class="close" data-dismiss="alert">&times;</a>
        <strong><span class="dataAlertModal"></span></strong>
    </div>
</div>