<?php echo $this->doctype(); ?>

<!-- <html lang="en"> -->
<html lang="es_ES">
    <head>
    	<?php echo $this->headMeta()->setCharset('utf8')?>  
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
            ->appendName('description', '')
            ->appendName('author', '')
        ?>
        
        <?php echo $this->headTitle(':: Nominas PHP ::'. $this->title)->setSeparator(' - ')->setAutoEscape(false)?>
        
        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        //<!-- Custom styles for this template -->
                        ->prependStylesheet($this->basePath() . '/css/signin.css')
                        //<!-- Bootstrap core CSS -->
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') 
                        ->prependStylesheet($this->basePath() . '/js/jqueryUI/jquery-ui.css')
                        ->prependStylesheet($this->basePath() . '/js/jqueryUI/jquery-ui.theme.css')
        ?>

        <!-- Scripts -->	    
	    <?php echo $this->headScript ()
	    	->prependFile ( $this->basePath () . '/js/jquery-1.11.0.min.js' )
        ?>

		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ?>       
	
	</head>
    <body>
        <div class="container">
            <?php echo $this->content; ?>
        </div>
        <?php echo $this->inlineScript() ?>
        
        <?php echo $this->headScript ()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            //->prependFile($this->basePath() . '/js/docs.min.js')
            //<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
            ->prependFile($this->basePath() . '/js/ie10-viewport-bug-workaround.js')
        ?>
    </body>
</html>
