<?php echo $this->doctype(); ?>

<!-- <html lang="en"> -->
<html lang="es_ES">
    <head>
    	<?php echo $this->headMeta()->setCharset('utf8')?>  
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
            ->appendName('description', '')
            ->appendName('author', '')
        ?>
        
        <?php //echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headTitle(':: Nominas PHP ::'. $this->title)->setSeparator(' - ')->setAutoEscape(false)?>
        
        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        //<!-- Custom styles for this template -->
                        ->prependStylesheet($this->basePath() . '/css/signin.css')
                        //<!-- Bootstrap core CSS -->
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') 
                        
                        ->prependStylesheet($this->basePath() . '/js/jqueryUI/jquery-ui.css')
                        ->prependStylesheet($this->basePath() . '/js/jqueryUI/jquery-ui-theme.css')
        ?>

        <!-- Scripts -->
        
        <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
	    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
	    <script src="../../js/ie-emulation-modes-warning.js"></script>
	    
		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ?>
        
        <!--[if lt IE 9]>
	      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	    <![endif]-->

    </head>
    <body>
		<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
			<div class="container-fluid">
		        <div class="navbar-header">
		          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
		            <span class="sr-only">Toggle navigation</span>
		            <span class="icon-bar"></span>
		            <span class="icon-bar"></span>
		            <span class="icon-bar"></span>
		          </button>
		          <a class="navbar-brand" href="#">Nominas PHP</a>
		          <a class="navbar-brand" href="<?=$this->basePath("usuarios/cerrar")?>">Cerrar sesión</a>
		        </div>
		        <div id="navbar" class="navbar-collapse collapse">
		          <ul class="nav navbar-nav navbar-right">
		          	<!--  <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
		          	-->
		            <li><a href="#">Dashboard</a></li>
		            <li><a href="#">Settings</a></li>
		            <li><a href="#">Profile</a></li>
		            <li><a href="#">Help</a></li>
		          </ul>
		          <form class="navbar-form navbar-right">
		            <input type="text" class="form-control" placeholder="Search...">
		          </form>
		        </div>
			</div>
    	</nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
        </div> <!-- /container -->
<!--         <footer>&copy; 2014</footer>         -->
        <?php echo $this->inlineScript() ?>
        
        <!-- Bootstrap core JavaScript
	    ================================================== -->
	    <!-- Placed at the end of the document so the pages load faster -->
	    <?php echo $this->headScript()
	    //<script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
	    //<script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
	    	//https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js
	    	->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/docs.min.js')
            ->prependFile($this->basePath() . '/js/jqueryUI/jquery-ui.js')
            //<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
			->prependFile($this->basePath() . '/js/ie10-viewport-bug-workaround.js')
        ?>
    </body>
</html>
