<?php echo $this->doctype(); ?>

<html lang="es">
    <head>
        <?php echo $this->headMeta()->setCharset('UTF-8') ?>
        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
                ->appendName('description', '')
                ->appendName('author', '')
        ?>

        <?php echo $this->headTitle(':: Nominas PHP ::' . $this->title)->setSeparator(' - ')->setAutoEscape(false) ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/style.css')
                //<!-- Custom styles for this template -->
                ->prependStylesheet($this->basePath() . '/css/signin.css')
                //<!-- Bootstrap core CSS -->
                ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                ->prependStylesheet($this->basePath() . '/js/jqueryUI/jquery-ui.css')
                ->prependStylesheet($this->basePath() . '/js/jqueryUI/jquery-ui.theme.css')
        ?>

        <!-- Scripts -->
        <script src="../js/jquery-1.11.2.min.js"></script>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ?>       

    </head>
    <body>
        <div class="container">
            <?php
            $flash = $this->flashMessenger();
            $flash->setMessageOpenFormat('<div%s>
				     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
				         &times;
				     </button>
				     <ul><li>')
                    ->setMessageSeparatorString('</li><li>')
                    ->setMessageCloseString('</li></ul></div>');

            echo $flash->render('error', array('alert', 'alert-dismissable', 'alert-danger'));
            echo $flash->render('info', array('alert', 'alert-dismissable', 'alert-info'));
            echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
            echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
            ?>
            <?php echo $this->content; ?>
        </div>
        <?php echo $this->inlineScript() ?>

        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                //->prependFile($this->basePath() . '/js/docs.min.js')
                //<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
                ->prependFile($this->basePath() . '/js/ie10-viewport-bug-workaround.js')
        ?>
    </body>
</html>