<?php
// module/Album/view/album/album/index.phtml:

$title = 'Propiedades de Empresa o Liquidación';
// $this->headTitle($title);
?>
 
<!-- <link rel="stylesheet" type="text/css" media="screen" href="../js/jqGrid/css/ui-lightness/jquery-ui-1.7.1.custom.css" /> -->
<link rel="stylesheet" type="text/css" media="screen"
	href="../js/jqGrid/css/ui.jqgrid.css" />

<!-- <script src="../js/jqGrid/jquery-1.4.2.min.js" type="text/javascript"></script> -->
<script src="//code.jquery.com/jquery-1.11.0.min.js"
	type="text/javascript"></script>
<script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"
	type="text/javascript"></script>
<script src="../js/jqGrid/js/i18n/grid.locale-es.js"
	type="text/javascript"></script>
<script src="../js/jqGrid/js/minified/jquery.jqGrid.min.js"
	type="text/javascript"></script>

<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
	$flash = $this->flashMessenger ()->setMessageOpenFormat ( '<div%s>' )->setMessageSeparatorString ( '' )->setMessageCloseString ( '</div>' );
?>
 <p>
     <a href="<?php echo $this->url('propempliq', array('action'=>'add'));?>">Añadir propiedad</a>
 </p>

 <?php echo $this->displayGrid($this->grid); ?>