<?php
$title = 'Propiedades de Empresa o Liquidación';
?>
	<h1 class="page-header" style="padding-top:20px"><?php echo $this->escapeHtml($title); ?></h1>	
<?php
	$flash = $this->flashMessenger();
	$flash->setMessageOpenFormat('<div%s>
							     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
							         &times;
							     </button>
							     <ul><li>')
								     ->setMessageSeparatorString('</li><li>')
								     ->setMessageCloseString('</li></ul></div>');
		
	echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
	echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
	echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
	echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
?>

<div class="alert alert-warning" id="myAlert" style="display:none">
	<a href="#" class="close" data-dismiss="alert">&times;</a>
	<strong><span class="dataAlert"></span></strong>
</div>

<br>
<div class="content">
	<div class="row">
		<div class="col-xs-6">
			<div class="row">
				<div class="col-xs-6 col-md-2">
					<button type="button" class="btn btn-success" id="btnAddPropiedadEmpLiq">Alta</button>
			  </div>
				<div class="col-xs-6 col-md-2">
					<button type="button" class="btn btn-danger" id="btnDelPropiedadEmpLiq">Baja</button>			  
			  </div>
				<div class="col-xs-6 col-md-2">
					<button type="button" class="btn btn-primary" id="btnEditPropiedadEmpLiq">Modificación</button>
			  </div>
			</div>
			<br>
			<div id="grid">
				<table id="gridPropEmpLiq"></table>
				<div id="pagerPropEmpLiq"></div>
			</div>
		</div>
		<div class="col-xs-6">
			<div class="row">
				<div class="col-xs-6 col-md-2">
					<button type="button" class="btn btn-success" id="btnAddPropiedadEmpLiqVal">Alta</button>
			  </div>
				<div class="col-xs-6 col-md-2">
					<button type="button" class="btn btn-danger" id="btnDelPropiedadEmpLiqVal">Baja</button>
			  </div>
				<div class="col-xs-6 col-md-2">
					<button type="button" class="btn btn-primary" id="btnEditPropiedadEmpLiqVal">Modificación</button>
			  </div>
			</div>
			<br>
			<div id="grid">
				<table id="gridPropEmpLiqVal"></table>
				<div id="pagerPropEmpLiqVal"></div>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
$(document).ready(function () {
    $("#gridPropEmpLiq").jqGrid({
    	width: 100,
        height: 230,
        autowidth: true,
        rownumbers: true,
        //rownumWidth: 20, 
        url:"<?php echo $this->url('propempliq', array('action'=>'loadDataGrid'));?>",
        datatype: 'json',
        mtype: 'POST',
        colNames: ["Id", "Propiedad", "Tipo"],
        colModel: [
            {name:'id', index:'id',
                width:10,
                align: "center",
                hidden:true
            },
            {name:'descripcion', index:'descripcion',
                width:30,
                align: "center",
                //sortable:true,
                editable:true,
                //editrules:{required:false,custom:true,custom_func:allcheck},
                editrules:{required:true}, 
                editoptions:{size:30}
            },
            {name:'tipo_de_campo', index:'tipo_de_campo',
                width:10,
                align: "center",
                //sortable:true,
                editable:true,
				edittype:'select', 
				editoptions:{value:"N:N;C:C;F:F"}
            }
        ],
        pager: "#pagerPropEmpLiq",
        rowNum: 10,
        rowList: [10, 20, 30],
        sortname: "id",
        sortorder: "asc",
        viewrecords: true,
        viewsortcols: [true,'horizontal',true],
        gridview: true,
        hidegrid: false,
        autoencode: true,
        forceFit : false,
   		editurl:"<?php echo $this->url('propempliq', array('action'=>'editGridItem'));?>",
        caption: "Propiedades de Empresa/Liquidación",
        onSelectRow: function(id, form){  
        	loadGridPropEmpLiqVal(id);
        }
    });

    $("#gridPropEmpLiq").navGrid("#pagerPropEmpLiq",
                {edit:false,add:false,del:false,search:false,refresh:true,view:false});

    $("#gridPropEmpLiqVal").jqGrid({
    	width: 450,
        height: 230,
        autowidth: false,
        rownumbers: true,
        //rownumWidth: 20, 
        url:"<?php echo $this->url('propempliq', array('action'=>'loadDataGridVal'));?>",
        datatype: "json",
        mtype: 'POST',
        colNames: ["Id", "PropiedadId", "Valor", "Significado"],
        colModel: [
            {name:'id', index:'id',
                width:10,
                align: "center",
                hidden:true
            },
            {name:'propiedad_id', index:'propiedad_id',
                width:10,
                align: "center",
                hidden:true
            },
            {name:'valor_posible', index:'valor_posible',
                width:15,
                align: "center",
                sortable:false,
                editable:true,
                editrules:{required:true}, 
                editoptions:{size:30}
            },
            {name:'significado', index:'significado',
                width:15,
                align: "center",
                sortable:false,
                editable:true,
                editrules:{required:true}, 
                editoptions:{size:30}
            } 
        ],
        pager: "#pagerPropEmpLiqVal",
        rowNum: 10,
        //rowList: [10, 20, 30],
        //sortname: "propiedad_id",
        //sortorder: "asc",
        viewrecords: true,
        //viewsortcols: [true,'horizontal',true],
        gridview: true,
        hidegrid: false,
        autoencode: true,
        forceFit : true,
   		editurl:"<?php echo $this->url('propempliq', array('action'=>'editGridItemVal'));?>",
        caption: "Valores Posibles" 
    });

    $("#gridPropEmpLiqVal").navGrid("#pagerPropEmpLiqVal",
                {edit:false,add:false,del:false,search:false,refresh:true,view:false});

    jQuery(window).bind('resize', function() {

        // Get width of parent container
        var width = jQuery("#grid").attr('clientWidth');
        if (width == null || width < 1){
            // For IE, revert to offsetWidth if necessary
            width = jQuery("#grid").attr('offsetWidth');
        }
        width = width - 2; // Fudge factor to prevent horizontal scrollbars
        if (width > 0 &&
            // Only resize if new width exceeds a minimal threshold
            // Fixes IE issue with in-place resizing when mousing-over frame bars
            Math.abs(width - jQuery("#gridPropEmpLiq").width()) > 5)
        {
            jQuery("#gridPropEmpLiq").setGridWidth(width);
            //jQuery("#gridPropEmpLiqVal").setGridWidth(width);
        }

    }).trigger('resize');

    //Buttons
    $("#btnAddPropiedadEmpLiq").click(function(){  
    	openDiagPropEmpLiq("form-add-PropEmpLiq","add","","");
    });

    $("#btnDelPropiedadEmpLiq").click(function(){ 
    	var rowid = jQuery("#gridPropEmpLiq").jqGrid('getGridParam','selrow'); 
        if( rowid != null ) {
        	var ids = $("#gridPropEmpLiqVal").jqGrid('getDataIDs'); 
            ids = ids.toString();
            ids = ids.split(",");
            var e = 0;
            
            for(var i=0;i < ids.length;i++){ 
                var data = $("#gridPropEmpLiqVal").jqGrid('getRowData',ids[i]);
                if(data['propiedad_id'] == rowid){
                	e++;
                }
            }	
            
        	if(e == 0){
	        	$.ajax({
	  		      url: "<?php echo $this->url('propempliq', array('action'=>'deleteGridItem'));?>",
	  		      global: false,
	  		      type: "POST",
	  		      data: "id="+rowid,
	  		      dataType: "json",
	  		      async:false,
	  		      success: function(msg){
	  		    	 gridReload('gridPropEmpLiq');
	  		    	 gridReload('gridPropEmpLiqVal');	      		      
	  				}						  
	  			}); 
        	}else{
        		msgAlert("myAlert","dataAlert","No se puede eliminar la propiedad porque tiene valores asociados.");
            	}
        }
        else {
        	msgAlert("myAlert","dataAlert","Por favor seleccione una fila.");
        }
    });

    $("#btnEditPropiedadEmpLiq").click(function(){ 
    	var rowid = jQuery("#gridPropEmpLiq").jqGrid('getGridParam','selrow'); 
        if( rowid != null ) {
        	openDiagPropEmpLiq("form-edit-PropEmpLiq","edit","gridPropEmpLiq",rowid);
        }
        else {
        	msgAlert("myAlert","dataAlert","Por favor seleccione una fila.");
        }
    });

    $("#btnAddPropiedadEmpLiqVal").click(function(){
    	var rowid = jQuery("#gridPropEmpLiq").jqGrid('getGridParam','selrow');
    	var rowidVal = jQuery("#gridPropEmpLiqVal").jqGrid('getGridParam','selrow'); 
        if( rowid != null ) {
        	openDiagPropEmpLiqVal("form-add-PropEmpLiqVal","add","gridPropEmpLiqVal",rowidVal);
        }
        else {
        	msgAlert("myAlert","dataAlert","Por favor seleccione una fila.");
        }   	
    });

    $("#btnDelPropiedadEmpLiqVal").click(function(){ 
    	var rowid = jQuery("#gridPropEmpLiqVal").jqGrid('getGridParam','selrow'); 
        if( rowid != null ) {
        	$.ajax({
  		      url: "<?php echo $this->url('propempliq', array('action'=>'deleteGridItemVal'));?>",
  		      global: false,
  		      type: "POST",
  		      data: "id="+rowid,
  		      dataType: "json",
  		      async:false,
  		      success: function(msg){
  		    	 gridReload('gridPropEmpLiqVal');	      		      
  				}						  
  			});
        }
        else {
        	msgAlert("myAlert","dataAlert","Por favor seleccione una fila.");
        }
    });

    $("#btnEditPropiedadEmpLiqVal").click(function(){ 
    	var rowid = jQuery("#gridPropEmpLiqVal").jqGrid('getGridParam','selrow'); 
        if( rowid != null ) {
        	openDiagPropEmpLiqVal("form-edit-PropEmpLiqVal","edit","gridPropEmpLiqVal",rowid);
        }
        else {
        	msgAlert("myAlert","dataAlert","Por favor seleccione una fila.");
        }
    });

  //Dialog add
    $("#form-add-PropEmpLiq").dialog({
        autoOpen: false,
        resizable: false,
        height: 'auto',
        width: 600,
        modal: true,
        buttons: {
            'Aceptar': function() {
            	var descripcion = $("#descripcion-add-PropEmpLiq").val();
            	var tipo = $("#descripcion-add-PropEmpLiq").val();
            	
        	    if (descripcion != '') {
	            	var ids = $("#gridPropEmpLiq").jqGrid('getDataIDs'); 
	                ids = ids.toString();
	                ids = ids.split(",");
	                var e = 0;
	                
	                for(var i=0;i < ids.length;i++){ 
	                    var data = $("#gridPropEmpLiq").jqGrid('getRowData',ids[i]);
	                    if(data['descripcion'] == descripcion){ 
	                    	e++;
	                    }
	                }	
	                
	            	if(e == 0){
		                var mydata = {
	                        "descripcion": descripcion,
	                        "tipo_de_campo": tipo,
	                      };
	                    
				        $.ajax({
						      url: "<?php echo $this->url('propempliq', array('action'=>'editGridItem'));?>",
						      global: false,
						      type: "POST",
						      data: "data="+JSON.stringify(mydata),
						      dataType: "json",
						      async:false,
						      success: function(msg){
						    	  gridReload('gridPropEmpLiq');
						    	  $("#form-add-PropEmpLiq").dialog('close');      		      
								}						  
						});	
						
	            	}else{
	            		$(this).dialog('close');
	            		msgAlert("myAlert","dataAlert","Ya existe un registro con esa combinacion.");
					}
				}
            },
            
            'Cancelar': function() {
                $(this).dialog('close');
            }
        },
        close: function() {
            //nada por ahora
        }   
    });

  	//Dialog edit
    $("#form-edit-PropEmpLiq").dialog({
        autoOpen: false,
        resizable: false,
        height: 'auto',
        width: 600,
        modal: true,
        buttons: {
            'Aceptar': function() {
            	var rowid = jQuery("#gridPropEmpLiq").jqGrid('getGridParam','selrow'); 
                if( rowid != null ) {  
                	var ids = $("#gridPropEmpLiq").jqGrid('getDataIDs'); 
                    ids = ids.toString();
                    ids = ids.split(",");
                    var e = 0;
                    
                    for(var i=0;i < ids.length;i++){ 
                        var data = $("#gridPropEmpLiq").jqGrid('getRowData',ids[i]);
                        if(data['descripcion'] == $("#descripcion-edit-PropEmpLiq").val() && data['id'] != rowid){ 
                        	e++;
                        }
                    }	
                    
                	if(e == 0)
                    {  
		                var mydata = {
		                                "id": rowid,
		                                "descripcion": $("#descripcion-edit-PropEmpLiq").val(),
		                                "tipo_de_campo": $("#tipo-edit-PropEmpLiq").val(),
		                              };
		                $.ajax({
		        		      url: "<?php echo $this->url('propempliq', array('action'=>'editGridItem'));?>",
		        		      global: false,
		        		      type: "POST",
		        		      data: "data="+JSON.stringify(mydata),
		        		      dataType: "json",
		        		      async:false,
		        		      success: function(msg){
		        		    	  gridReload('gridPropEmpLiq');
		        		    	  $("#form-edit-PropEmpLiq").dialog('close');      		      
		        				}						  
		        			});
        			
                    }else{
                		$(this).dialog('close');
                		msgAlert("myAlert","dataAlert","Ya existe un registro con esa combinacion.");
    				}
                }
            },
            
            'Cancelar': function() {
                $(this).dialog('close');
            }
        },
        close: function() {
            //nada por ahora
        } 
    });
    
	//Dialog addVal
    $("#form-add-PropEmpLiqVal").dialog({
        autoOpen: false,
        resizable: false,
        height: 'auto',
        width: 620,
        modal: true,
        buttons: {
            'Aceptar': function() {
            	var rowid = jQuery("#gridPropEmpLiq").jqGrid('getGridParam','selrow');
            	var ids = $("#gridPropEmpLiqVal").jqGrid('getDataIDs'); 
                ids = ids.toString();
                ids = ids.split(",");
                var e = 0;
                
                for(var i=0;i < ids.length;i++){ 
                    var data = $("#gridPropEmpLiqVal").jqGrid('getRowData',ids[i]);
                    if(data['propiedad_id'] == rowid && data['valor_posible'] == $("#valor-posible-add-PropEmpLiqVal").val()){ 
                    	e++;
                    }
                }	
                
            	if(e == 0)
                {
            		var mydata = {
                            "propiedad_id": rowid,
                            "valor_posible": $("#valor-posible-add-PropEmpLiqVal").val(),
                            "significado": $("#significado-add-PropEmpLiqVal").val(),
                          };
		            $.ajax({
		    		      url: "<?php echo $this->url('propempliq', array('action'=>'editGridItemVal'));?>",
		    		      global: false,
		    		      type: "POST",
		    		      data: "data="+JSON.stringify(mydata),
		    		      dataType: "json",
		    		      async:false,
		    		      success: function(msg){
		    		    	  loadGridPropEmpLiqVal(rowid);
		    		    	  $("#form-add-PropEmpLiqVal").dialog('close');      		      
		    				}						  
		    			});
            	}else{
            			$(this).dialog('close');
            			msgAlert("myAlert","dataAlert","Ya existe un registro con esa combinacion.");
                	}
            },
            
            Cancel: function() {
                $(this).dialog('close');
            }
        },
        close: function() {
            //nada por ahora
        }        
    });

  	//Dialog editVal
    $("#form-edit-PropEmpLiqVal").dialog({
        autoOpen: false,
        resizable: false,
        height: 'auto',
        width: 620,
        modal: true,
        buttons: {
            'Aceptar': function() {
            	var rowid = jQuery("#gridPropEmpLiqVal").jqGrid('getGridParam','selrow'); 
                if( rowid != null ) {  
                	var ids = $("#gridPropEmpLiqVal").jqGrid('getDataIDs'); 
                    ids = ids.toString();
                    ids = ids.split(",");
                    var e = 0;
                    
                    for(var i=0;i < ids.length;i++){ 
                        var data = $("#gridPropEmpLiqVal").jqGrid('getRowData',ids[i]);
                        if(data['valor_posible'] == $("#valor-posible-edit-PropEmpLiqVal").val() && data['id'] != rowid){ 
                        	e++;
                        }
                    }	
                    
                	if(e == 0)
                    {    
		                var mydata = {
		                                "id": rowid,
		                                "valor_posible": $("#valor-posible-edit-PropEmpLiqVal").val(),
		                                "significado": $("#significado-edit-PropEmpLiqVal").val(),
		                              };
		                $.ajax({
		        		      url: "<?php echo $this->url('propempliq', array('action'=>'editGridItemVal'));?>",
		        		      global: false,
		        		      type: "POST",
		        		      data: "data="+JSON.stringify(mydata),
		        		      dataType: "json",
		        		      async:false,
		        		      success: function(msg){
		        		    	  loadGridPropEmpLiqVal(dataGrid.propiedad_id);
		        		    	  $("#form-edit-PropEmpLiqVal").dialog('close');      		      
		        				}						  
		        			});
                    }else{
            			$(this).dialog('close');
            			msgAlert("myAlert","dataAlert","Ya existe un registro con esa combinacion.");
                	}
                }
            },
            
            Cancel: function() {
                $(this).dialog('close');
            }
        },
        close: function() {
            //nada por ahora
        }    
    });

    $('input').bind('keypress', function (event) {
        var regex = new RegExp("^[a-zA-Z0-9_ \,._-]+$");
        var key = String.fromCharCode(!event.charCode ? event.which : event.charCode);
        if (!regex.test(key)) {
           event.preventDefault();
           return false;
        }
    });
    
    $('#myAlert').on('closed.bs.alert', function () {
    		$('.dataAlert').html("");
    	})
}); 

function gridReload(gridName){
	$("#"+gridName).setGridParam({datatype:'json'}).setGridParam({ rowNum: 10 }).trigger('reloadGrid');
}

function loadGridPropEmpLiqVal(id){
	if(id != null){
		var sUrl = "<?php echo $this->url('propempliq', array('action'=>'loadDataGridVal'));?>"+"/"+id;
		$("#gridPropEmpLiqVal").jqGrid('setGridParam',		
			{url:sUrl}
			).trigger('reloadGrid');
	}
	else {
		msgAlert("myAlert","dataAlert","Por favor seleccione una fila.");
	}
}
        
function openDiagPropEmpLiq(diagName, op, grid, id){
	clearDataPropEmpLiq();
	if(op == "edit"){
		rowdata = jQuery("#"+grid).getRowData(id);
		$('#descripcion-edit-PropEmpLiq').val(rowdata['descripcion']);
		$('#tipo-edit-PropEmpLiq').val(rowdata['tipo_de_campo']);
	    $('#'+diagName).dialog('open');
	}else{
		$('#'+diagName).dialog('open');
		$('#tipo-add-PropEmpLiq option:contains("N")').prop('selected', true);
		}
}

function openDiagPropEmpLiqVal(diagName, op, grid, id){
	clearDataPropEmpLiqVal();
	if(op == "edit"){
		rowdata = jQuery("#"+grid).getRowData(id);
		$('#valor-posible-edit-PropEmpLiqVal').val(rowdata['valor_posible']);
		$('#significado-edit-PropEmpLiqVal').val(rowdata['significado']);
	    $('#'+diagName).dialog('open');
	}else{
		$('#'+diagName).dialog('open');
		}
}

function clearDataPropEmpLiq(){
	$('#descripcion-add-PropEmpLiq').val("");
	$('#descripcion-edit-PropEmpLiq').val("");
}

function clearDataPropEmpLiqVal(){
	$('#valor-posible-add-PropEmpLiqVal').val("");
	$('#significado-add-PropEmpLiqVal').val("");
	$('#valor-posible-edit-PropEmpLiqVal').val("");
	$('#significado-edit-PropEmpLiqVal').val("");
}

function msgAlert(diagName, selectorName, msg){
	$('#'+diagName).show();
	$('.'+selectorName).html(msg);
	setTimeout(function(){
			$('#'+diagName).hide();
			$('.'+selectorName).html("");
		},3000)
}

</script>

<!-- Dialogo -->
<div id="form-add-PropEmpLiq"  title="Agregar registro">
	<form class="form-horizontal" id="valid-form-add-PropEmpLiq" role="form">
	  <div class="form-group">
	    <label for="input-descripcion-add-PropEmpLiq" class="col-sm-2 control-label">Propiedad:</label>
	    <div class="col-sm-10">
	      <input type="text" class="form-control" id="descripcion-add-PropEmpLiq" placeholder="">
	    </div>
	  </div>
	  <div class="form-group">
	    <label for="input-tipo-add-PropEmpLiq" class="col-sm-2 control-label">Tipo:</label>
	    <div class="col-sm-10">
	      <select class="form-control" id="tipo-add-PropEmpLiq">
			  <option value="N">N</option>
			  <option value="C">C</option>
			  <option value="F">F</option>
			</select>
	    </div>
	  </div>
	</form>
</div>

<!-- Dialogo -->
<div id="form-edit-PropEmpLiq"  title="Editar registro">
	<form class="form-horizontal" id="valid-form-edit-PropEmpLiq" role="form">
		  <div class="form-group">
		    <label for="input-descripcion-edit-PropEmpLiq" class="col-sm-2 control-label">Propiedad:</label>
		    <div class="col-sm-10">
		      <input type="text" class="form-control" id="descripcion-edit-PropEmpLiq" placeholder="">
		    </div>
		  </div>
		  <div class="form-group">
		    <label for="input-tipo-edit-PropEmpLiq" class="col-sm-2 control-label">Tipo:</label>
		    <div class="col-sm-10">
		      <select class="form-control" id="tipo-edit-PropEmpLiq">
				  <option value="N">N</option>
				  <option value="C">C</option>
				  <option value="F">F</option>
				</select>
		    </div>
		</div>
	</form>
</div>

<!-- Dialogo -->
<div id="form-add-PropEmpLiqVal"  title="Agregar registro">
	<form class="form-horizontal" id="valid-form-add-PropEmpLiqVal" role="form">
		  <div class="form-group">
		    <label for="input-valor-posible-add-PropEmpLiqVal" class="col-sm-2 control-label">Valor:</label>
		    <div class="col-sm-10">
		      <input type="text" class="form-control" id="valor-posible-add-PropEmpLiqVal" placeholder="">
		    </div>
		  </div>
		  <div class="form-group">
		    <label for="input-significado-add-PropEmpLiqVal" class="col-sm-2 control-label">Significado:</label>
		    <div class="col-sm-10">
		      <input type="text" class="form-control" id="significado-add-PropEmpLiqVal" placeholder="">
		    </div>
		</div>
	</form>
</div>

<!-- Dialogo -->
<div id="form-edit-PropEmpLiqVal"  title="Editar registro">
	<form class="form-horizontal" id="valid-form-edit-PropEmpLiqVal" role="form">
		  <div class="form-group">
		    <label for="input-valor-posible-edit-PropEmpLiqVal" class="col-sm-2 control-label">Valor:</label>
		    <div class="col-sm-10">
		      <input type="text" class="form-control" id="valor-posible-edit-PropEmpLiqVal" placeholder="">
		    </div>
		  </div>
		  <div class="form-group">
		    <label for="input-significado-edit-PropEmpLiqVal" class="col-sm-2 control-label">Significado:</label>
		    <div class="col-sm-10">
		      <input type="text" class="form-control" id="significado-edit-PropEmpLiqVal" placeholder="">
		    </div>
		</div>
	</form>
</div>		