<!-- <link rel="stylesheet" type="text/css" media="screen" href="../js/jqGrid/css/ui-lightness/jquery-ui-1.7.1.custom.css" /> -->
<link rel="stylesheet" type="text/css" media="screen"
	href="../js/jqGrid/css/ui.jqgrid.css" />

<!-- <script src="../js/jqGrid/jquery-1.4.2.min.js" type="text/javascript"></script> -->
<script src="//code.jquery.com/jquery-1.11.0.min.js"
	type="text/javascript"></script>
<script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"
	type="text/javascript"></script>
<script src="../js/jqGrid/js/i18n/grid.locale-es.js"
	type="text/javascript"></script>
<script src="../js/jqGrid/js/minified/jquery.jqGrid.min.js"
	type="text/javascript"></script>

<h1>Propiedades de Empresa o Liquidación</h1>
<?php
$flash = $this->flashMessenger ()->setMessageOpenFormat ( '<div%s>' )->setMessageSeparatorString ( '' )->setMessageCloseString ( '</div>' );
?>
<table class="table">
	<tr>
		<td colspan="7"><a class="btn btn-success"
			href="&lt;?=$this-&gt;basePath()?&gt;/propiedades/add">Añadir
				propiedad</a>
              <?php echo $flash->render('add_correcto',array('btn', 'btn-success'));?>
              <?php echo $flash->render('eliminado',array('btn', 'btn-success'));?>
        </td>
	</tr>
	<tr>
		<th>ID</th>
		<th>Propiedad</th>
		<th>Ver</th>
		<th>Modificar</th>
		<th>Eliminar</th>
	</tr>
    <?php foreach($lista as $empresaLiquidacion){ ?>
    <tr style='background-color: &amp;amp;'>
		<td><?=$empresaLiquidacion["id"]?></td>
		<td><?=$empresaLiquidacion["descripcion"]?></td>
		<td><?=$empresaLiquidacion["tipo_de_campo"]?></td>
		<td><a class="btn btn-success"
			href='&lt;?=$this-&gt;basePath()?&gt;/propiedades/ver/&lt;?=$empresaLiquidacion["id"]?&gt;'>Ver</a></td>
		<td><a class="btn btn-primary"
			href='&lt;?=$this-&gt;basePath()?&gt;/propiedades/modificar/&lt;?=$empresaLiquidacion["id"]?&gt;'>Modificación</a></td>
		<td><a class="btn btn-danger"
			href='&lt;?=$this-&gt;basePath()?&gt;/propiedades/eliminar/&lt;?=$empresaLiquidacion["id"]?&gt;'>Baja</a></td>
	</tr>
    <?php } ?>
</table>