<?php
$title = 'Propiedades de Empresa o Liquidación';
?>

<hr>
	<h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>
<hr/>
<?php
	$flash = $this->flashMessenger ()->setMessageOpenFormat ( '<div%s>' )->setMessageSeparatorString ( '' )->setMessageCloseString ( '</div>' );
?>

<br>
<div class="content">
	<div class="row">
		<div class="col-xs-6">
			<div class="row">
				<div class="col-xs-6 col-md-4">
					<a class="btn btn-success" id="btnAddPropiedadEmpLiq">Alta</a>
			  </div>
				<div class="col-xs-6 col-md-4">
					<a class="btn btn-danger" id="btnDelPropiedadEmpLiq">Baja</a>			  
			  </div>
				<div class="col-xs-6 col-md-4">
					<a class="btn btn-primary" id="btnEditPropiedadEmpLiq">Modificación</a>
			  </div>
			</div>
			<br>
			<div id="grid">
				<table id="gridPropEmpLiq"></table>
				<div id="pagerPropEmpLiq"></div>
			</div>
		</div>
		<div class="col-xs-6">
			<div class="row">
				<div class="col-xs-6 col-md-4">
					<a class="btn btn-success" id="btnAddPropiedadEmpLiqVal">Alta</a>
			  </div>
				<div class="col-xs-6 col-md-4">
					<a class="btn btn-danger" id="btnDelPropiedadEmpLiqVal">Baja</a>
			  </div>
				<div class="col-xs-6 col-md-4">
					<a class="btn btn-primary" id="btnEditPropiedadEmpLiqVal">Modificación</a>
			  </div>
			</div>
			<br>
			<div id="grid">
				<table id="gridPropEmpLiqVal"></table>
				<div id="pagerPropEmpLiqVal"></div>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
$(document).ready(function () {
    $("#gridPropEmpLiq").jqGrid({
    	width: 100,
        height: 230,
        autowidth: true,
        rownumbers: true,
        //rownumWidth: 20, 
        url:"<?php echo $this->url('propempliq', array('action'=>'loadDataGrid'));?>",
        datatype: 'json',
        mtype: 'POST',
        colNames: ["Id", "Propiedad", "Tipo"],
        colModel: [
            {name:'id', index:'id',
                width:10,
                align: "center",
                hidden:true
            },
            {name:'descripcion', index:'descripcion',
                width:30,
                align: "center",
                //sortable:true,
                editable:true,
                editrules:{required:false,custom:true,custom_func:allcheck}, 
                editoptions:{size:30}
            },
            {name:'tipo_de_campo', index:'tipo_de_campo',
                width:10,
                align: "center",
                //sortable:true,
                editable:true,
				edittype:'select', 
				editoptions:{value:"N:N;C:C;F:F"}
            }
        ],
        pager: "#pagerPropEmpLiq",
        rowNum: 10,
        rowList: [10, 20, 30],
        sortname: "id",
        sortorder: "asc",
        viewrecords: true,
        viewsortcols: [true,'horizontal',true],
        gridview: true,
        hidegrid: false,
        autoencode: true,
        forceFit : false,
   		editurl:"<?php echo $this->url('propempliq', array('action'=>'editGridItem'));?>",
        caption: "Propiedades de Empresa/Liquidación",
        onSelectRow: function(id, form){  
        	loadGridPropEmpLiqVal(id);
        }
    });

    $("#gridPropEmpLiq").navGrid("#pagerPropEmpLiq",
                {edit:false,add:false,del:false,search:false,refresh:false,view:false});

    $("#gridPropEmpLiqVal").jqGrid({
    	width: 100,
        height: 230,
        autowidth: true,
        rownumbers: true,
        //rownumWidth: 20, 
        url:"<?php echo $this->url('propempliq', array('action'=>'loadDataGridVal'));?>",
        datatype: "json",
        mtype: 'POST',
        colNames: ["Id", "PropiedadId", "Valor", "Significado"],
        colModel: [
            {name:'id', index:'id',
                width:10,
                align: "center",
                hidden:true
            },
            {name:'propiedad_id', index:'propiedad_id',
                width:10,
                align: "center",
                hidden:true
            },
            {name:'valor_posible', index:'valor_posible',
                width:15,
                align: "center",
                //sortable:true,
                editable:true,
                editrules:{required:false,custom:true,custom_func:allcheck}, 
                editoptions:{size:30}
            },
            {name:'significado', index:'significado',
                width:15,
                align: "center",
                //sortable:true,
                editable:true,
                editrules:{required:false,custom:true,custom_func:allcheck}, 
                editoptions:{size:30}
            } 
        ],
        pager: "#pagerPropEmpLiqVal",
        rowNum: 10,
        rowList: [10, 20, 30],
        sortname: "id",
        sortorder: "asc",
        viewrecords: true,
        viewsortcols: [true,'horizontal',true],
        gridview: true,
        hidegrid: false,
        autoencode: true,
        forceFit : false,
   		editurl:"<?php echo $this->url('propempliq', array('action'=>'editGridItemVal'));?>",
        caption: "Valores Posibles" 
    });

    $("#gridPropEmpLiqVal").navGrid("#pagerPropEmpLiqVal",
                {edit:false,add:false,del:false,search:false,refresh:false,view:false});

    $("#btnAddPropiedadEmpLiq").click(function(){  
    	openDiagPropEmpLiq("form-add-PropEmpLiq","add","","");
    });

    $("#btnDelPropiedadEmpLiq").click(function(){ 
    	var rowid = jQuery("#gridPropEmpLiq").jqGrid('getGridParam','selrow'); 
        if( rowid != null ) {
        	$.ajax({
  		      url: "<?php echo $this->url('propempliq', array('action'=>'deleteGridItem'));?>",
  		      global: false,
  		      type: "POST",
  		      data: "id="+rowid,
  		      dataType: "json",
  		      async:false,
  		      success: function(msg){
  		    	 gridReload('gridPropEmpLiq');
  		    	 gridReload('gridPropEmpLiqVal');	      		      
  				}						  
  			}); 
        }
        else {
            alert("Por favor seleccione una fila."); 
        }
    });

    $("#btnEditPropiedadEmpLiq").click(function(){ 
    	var rowid = jQuery("#gridPropEmpLiq").jqGrid('getGridParam','selrow'); 
        if( rowid != null ) {
        	openDiagPropEmpLiq("form-edit-PropEmpLiq","edit","gridPropEmpLiq",rowid);
        }
        else {
            alert("Por favor seleccione una fila."); 
        }
    });

    $("#btnAddPropiedadEmpLiqVal").click(function(){
    	var rowid = jQuery("#gridPropEmpLiq").jqGrid('getGridParam','selrow');
    	var rowidVal = jQuery("#gridPropEmpLiqVal").jqGrid('getGridParam','selrow'); 
        if( rowid != null ) {
        	openDiagPropEmpLiqVal("form-add-PropEmpLiqVal","add","gridPropEmpLiqVal",rowidVal);
        }
        else {
            alert("Por favor seleccione una fila."); 
        }   	
    });

    $("#btnDelPropiedadEmpLiqVal").click(function(){ 
    	var rowid = jQuery("#gridPropEmpLiqVal").jqGrid('getGridParam','selrow'); 
        if( rowid != null ) {
        	$.ajax({
  		      url: "<?php echo $this->url('propempliq', array('action'=>'deleteGridItemVal'));?>",
  		      global: false,
  		      type: "POST",
  		      data: "id="+rowid,
  		      dataType: "json",
  		      async:false,
  		      success: function(msg){
  		    	 gridReload('gridPropEmpLiqVal');	      		      
  				}						  
  			});
        }
        else {
            alert("Please Select Row to delete!"); 
        }
    });

    $("#btnEditPropiedadEmpLiqVal").click(function(){ 
    	var rowid = jQuery("#gridPropEmpLiqVal").jqGrid('getGridParam','selrow'); 
        if( rowid != null ) {
        	openDiagPropEmpLiqVal("form-edit-PropEmpLiqVal","edit","gridPropEmpLiqVal",rowid);
        }
        else {
            alert("Por favor seleccione una fila."); 
        }
    });

  //Dialog add
    $("#form-add-PropEmpLiq").dialog({
        autoOpen: false,
        resizable: false,
        height: 'auto',
        width: 350,
        modal: true,
        buttons: {
            'Aceptar': function() {
            	var rowid = jQuery("#gridPropEmpLiq").jqGrid('getGridParam','selrow');
            	var dataGrid   = jQuery("#gridPropEmpLiq").jqGrid('getRowData', rowid);	
            	if($("#valor-posible-add-PropEmpLiq").val() != dataGrid.valor_posible){
	                if( rowid != null ) {
		                var mydata = {
		                                "decripcion": $("#decripcion-add-PropEmpLiq").val(),
		                                "tipo_de_campo": $("#tipo-add-PropEmpLiq").val(),
		                              };
		                $.ajax({
		        		      url: "<?php echo $this->url('propempliq', array('action'=>'editGridItem'));?>",
		        		      global: false,
		        		      type: "POST",
		        		      data: "data="+JSON.stringify(mydata),
		        		      dataType: "json",
		        		      async:false,
		        		      success: function(msg){
		        		    	  gridReload('gridPropEmpLiq');
		        		    	  $("#form-add-PropEmpLiq").dialog('close');      		      
		        				}						  
		        			});
	                }
            	}else{
						alert("Ya existe un registro con esa combinacion.")
                	}
            },
            
            Cancel: function() {
                $(this).dialog('close');
            }
        },
        close: function() {
            //nada por ahora
        }
        
    });

  	//Dialog edit
    $("#form-edit-PropEmpLiq").dialog({
        autoOpen: false,
        resizable: false,
        height: 'auto',
        width: 350,
        modal: true,
        buttons: {
            'Aceptar': function() {
            	var rowid = jQuery("#gridPropEmpLiqVal").jqGrid('getGridParam','selrow'); 
                if( rowid != null ) {    
	                var mydata = {
	                                "id": rowid,
	                                "decripcion": $("#decripcion-edit-PropEmpLiq").val(),
	                                "tipo_de_campo": $("#tipo-edit-PropEmpLiq").val(),
	                              };
	                $.ajax({
	        		      url: "<?php echo $this->url('propempliq', array('action'=>'editGridItem'));?>",
	        		      global: false,
	        		      type: "POST",
	        		      data: "data="+JSON.stringify(mydata),
	        		      dataType: "json",
	        		      async:false,
	        		      success: function(msg){
	        		    	  gridReload('gridPropEmpLiq');
	        		    	  $("#form-edit-PropEmpLiq").dialog('close');      		      
	        				}						  
	        			});
                }
            },
            
            Cancel: function() {
                $(this).dialog('close');
            }
        },
        close: function() {
            //nada por ahora
        }
        
    });
    
	//Dialog addVal
    $("#form-add-PropEmpLiqVal").dialog({
        autoOpen: false,
        resizable: false,
        height: 'auto',
        width: 350,
        modal: true,
        buttons: {
            'Aceptar': function() {
            	var rowid = jQuery("#gridPropEmpLiq").jqGrid('getGridParam','selrow');
            	var dataGrid   = jQuery("#gridPropEmpLiqVal").jqGrid('getRowData', rowid);	
            	if($("#valor-posible-add-PropEmpLiqVal").val() != dataGrid.valor_posible){
	                if( rowid != null ) {
		                var mydata = {
		                                "propiedad_id": rowid,
		                                "valor_posible": $("#valor-posible-add-PropEmpLiqVal").val(),
		                                "significado": $("#significado-add-PropEmpLiqVal").val(),
		                              };
		                $.ajax({
		        		      url: "<?php echo $this->url('propempliq', array('action'=>'editGridItemVal'));?>",
		        		      global: false,
		        		      type: "POST",
		        		      data: "data="+JSON.stringify(mydata),
		        		      dataType: "json",
		        		      async:false,
		        		      success: function(msg){
		        		    	  loadGridPropEmpLiqVal(rowid);
		        		    	  $("#form-add-PropEmpLiqVal").dialog('close');      		      
		        				}						  
		        			});
	                }
            	}else{
						alert("Ya existe un registro con esa combinacion.")
                	}
            },
            
            Cancel: function() {
                $(this).dialog('close');
            }
        },
        close: function() {
            //nada por ahora
        }
        
    });

  	//Dialog editVal
    $("#form-edit-PropEmpLiqVal").dialog({
        autoOpen: false,
        resizable: false,
        height: 'auto',
        width: 350,
        modal: true,
        buttons: {
            'Aceptar': function() {
            	var rowid = jQuery("#gridPropEmpLiqVal").jqGrid('getGridParam','selrow'); 
				var dataGrid   = jQuery("#gridPropEmpLiqVal").jqGrid('getRowData', rowid);	
                if( rowid != null ) {    
	                var mydata = {
	                                "id": rowid,
	                                "valor_posible": $("#valor-posible-edit-PropEmpLiqVal").val(),
	                                "significado": $("#significado-edit-PropEmpLiqVal").val(),
	                              };
	                $.ajax({
	        		      url: "<?php echo $this->url('propempliq', array('action'=>'editGridItemVal'));?>",
	        		      global: false,
	        		      type: "POST",
	        		      data: "data="+JSON.stringify(mydata),
	        		      dataType: "json",
	        		      async:false,
	        		      success: function(msg){
	        		    	  loadGridPropEmpLiqVal(dataGrid.propiedad_id);
	        		    	  $("#form-edit-PropEmpLiqVal").dialog('close');      		      
	        				}						  
	        			});
                }
            },
            
            Cancel: function() {
                $(this).dialog('close');
            }
        },
        close: function() {
            //nada por ahora
        }
        
    }); 
}); 


function allcheck(value, colname){
    var permitidos =/^[0-9a-zA-Z|ñ|Ñ|\s|\_|\-|\.]*$/; //La cadena ha de estar compuesta únicamente por letras
    if(permitidos.test(value)){
        return [true,""];
    }else{
        return [false,colname+": Introduzca carácteres válidos."];
    }
}

function gridReload(gridName){
	$("#"+gridName).setGridParam({datatype:'json'}).setGridParam({ rowNum: 10 }).trigger('reloadGrid');
}

function loadGridPropEmpLiqVal(id){
	if(id != null){
		var sUrl = "<?php echo $this->url('propempliq', array('action'=>'loadDataGridVal'));?>"+"/"+id;
		$("#gridPropEmpLiqVal").jqGrid('setGridParam',		
			{url:sUrl}
			).trigger('reloadGrid');
	}
	else {
	    alert("Por favor seleccione una fila."); 
	}
}
        
function openDiagPropEmpLiq(diagName, op, grid, id){
	clearDataPropEmpLiq();
	if(op == "edit"){
		rowdata = jQuery("#"+grid).getRowData(id);
		$('#decripcion-edit-PropEmpLiq').val(rowdata['descripcion']);
		$('#tipo-edit-PropEmpLiq').val(rowdata['tipo_de_campo']);
	    $('#'+diagName).dialog('open');
	}else{
		$('#'+diagName).dialog('open');
		}
}

function openDiagPropEmpLiqVal(diagName, op, grid, id){
	clearDataPropEmpLiqVal();
	if(op == "edit"){
		rowdata = jQuery("#"+grid).getRowData(id);
		$('#valor-posible-edit-PropEmpLiqVal').val(rowdata['valor_posible']);
		$('#significado-edit-PropEmpLiqVal').val(rowdata['significado']);
	    $('#'+diagName).dialog('open');
	}else{
		$('#'+diagName).dialog('open');
		}
}


function clearDataPropEmpLiq(){
	$('#decripcion-add-PropEmpLiq').val("");
	$('#tipo-add-PropEmpLiq').val("");
	$('#decripcion-edit-PropEmpLiq').val("");
	$('#tipo-edit-PropEmpLiq').val("");
}

function clearDataPropEmpLiqVal(){
	$('#valor-posible-add-PropEmpLiqVal').val("");
	$('#significado-add-PropEmpLiqVal').val("");
	$('#valor-posible-edit-PropEmpLiqVal').val("");
	$('#significado-edit-PropEmpLiqVal').val("");
}
</script>

<!-- Dialogo -->
<div id="form-add-PropEmpLiq"  title="Agregar registro">
        <table>
            <tr>
                <td class="flab">Propiedad: </td>
                <td class="fcon">
                    <input type="text" id="decripcion-add-PropEmpLiq"  name="decripcion-add-PropEmpLiq" value="" style="width:162px;">
                </td>
            </tr>
            <tr>
                <td class="flab">Tipo: </td>
                <td class="fcon"> 
                    <select id="tipo-add-PropEmpLiq" name="tipo-add-PropEmpLiqVal">
					  <option value="N" selected>N</option>
					  <option value="C">C</option>
					  <option value="F">F</option>
					</select> 
                </td>
            </tr>
        </table>
</div>

<!-- Dialogo -->
<div id="form-edit-PropEmpLiq"  title="Editar registro">
        <table>
            <tr>
                <td class="flab">Propiedad: </td>
                <td class="fcon">
                    <input type="text" id="decripcion-edit-PropEmpLiq"  name="decripcion-edit-PropEmpLiq" value="" style="width:162px;">
                </td>
            </tr>
            <tr>
                <td class="flab">Tipo: </td>
                <td class="fcon">
                	<select id="tipo-edit-PropEmpLiq" name="tipo-edit-PropEmpLiq">
					  <option value="N" selected>N</option>
					  <option value="C">C</option>
					  <option value="F">F</option>
					</select> 
                </td>
            </tr>
        </table>
</div>

<!-- Dialogo -->
<div id="form-add-PropEmpLiqVal"  title="Agregar registro">
        <table>
            <tr>
                <td class="flab">Valor: </td>
                <td class="fcon">
                    <input type="text" id="valor-posible-add-PropEmpLiqVal"  name="valor-posible-add-PropEmpLiqVal" value="" style="width:162px;">
                </td>
            </tr>
            <tr>
                <td class="flab">Significado: </td>
                <td class="fcon">
                    <input type="text" id="significado-add-PropEmpLiqVal"  name="significado-add-PropEmpLiqVal"  value="" style="width:162px;" >
                </td>
            </tr>
        </table>
</div>

<!-- Dialogo -->
<div id="form-edit-PropEmpLiqVal"  title="Editar registro">
        <table>
            <tr>
                <td class="flab">Valor: </td>
                <td class="fcon">
                    <input type="text" id="valor-posible-edit-PropEmpLiqVal"  name="valor-posible-edit-PropEmpLiqVal" value="" style="width:162px;">
                </td>
            </tr>
            <tr>
                <td class="flab">Significado: </td>
                <td class="fcon">
                    <input type="text" id="significado-edit-PropEmpLiqVal"  name="significado-edit-PropEmpLiqVal"  value="" style="width:162px;" >
                </td>
            </tr>
        </table>
</div>