<?php
$title = 'Definición de datos de Familiares';
?>
<h1 class="page-header" style="padding-top:20px"><?php echo $this->escapeHtml($title); ?></h1>
<?php
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
            &times;
            </button>
        <ul><li>')
        ->setMessageSeparatorString('</li><li>')
        ->setMessageCloseString('</li></ul></div>');

echo $flash->render('error', array('alert', 'alert-dismissable', 'alert-danger', 'flashAlert'));
echo $flash->render('info', array('alert', 'alert-dismissable', 'alert-info', 'flashAlert'));
echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning', 'flashAlert'));
echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success', 'flashAlert'));
?>

<script type="text/javascript" src="../js/jqueryValidation/dist/jquery.validate.min.js"></script>    
<script type="text/javascript" src="../js/jqueryValidation/dist/additional-methods.min.js"></script>  
<script type="text/javascript" src="../js/jqueryValidation/dist/localization/messages_es_AR.min.js"></script>  

<div class="alert alert-warning ui-state-highlight ui-corner-all" id="diagAlertMain">
    <a href="#" class="close" data-dismiss="alert">&times;</a>
    <strong><span class="dataAlertMain"></span></strong>
</div>

<br>
<div class="content">
    <div class="row">
        <div class="col-xs-6">
            <div class="btn-group">
                <button type="button" class="btn btn-primary btn-lg" id="btnAddDatosFamiliares">Alta</button>
                <button type="button" class="btn btn-primary btn-lg" id="btnDelDatosFamiliares">Baja</button>
                <button type="button" class="btn btn-primary btn-lg" id="btnEditDatosFamiliares">Modificación</button>
            </div>
            <br>
            <div id="jqGridDatosFamiliares" style="padding-top:10px;">
                <table id="gridDatosFamiliares"></table>
                <div id="pagerDatosFamiliares"></div>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="btn-group">
                <button type="button" class="btn btn-primary btn-lg" id="btnAddDatosFamiliaresVal">Alta</button>
                <button type="button" class="btn btn-primary btn-lg" id="btnDelDatosFamiliaresVal">Baja</button>
                <button type="button" class="btn btn-primary btn-lg" id="btnEditDatosFamiliaresVal">Modificación</button>
            </div>
            <br>
            <div id="jqGridDatosFamiliaresVal" style="padding-top:10px;">
                <table id="gridDatosFamiliaresVal"></table>
                <div id="pagerDatosFamiliaresVal"></div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        //Grids
        $("#gridDatosFamiliares").jqGrid({
            width: 100,
            height: 230,
            autowidth: true,
            rowNum: 1000,
            rownumbers: true,
            url: "<?php echo $this->url('datosfamiliares', array('action' => 'loadDataGrid')); ?>",
            datatype: 'json',
            mtype: 'GET',
            colNames: ["Id", "Propiedad", "Tipo"],
            colModel: [
                {name: 'id', index: 'id',
                    width: 10,
                    align: "center",
                    sortable: false,
                    sorttype: 'int',
                    hidden: true
                },
                {name: 'descripcion', index: 'descripcion',
                    width: 30,
                    align: "center",
                    sortable: true,
                    sorttype: 'text',
                    search: true,
                    stype: 'text',
                    searchoptions: {clearSearch: true}
                },
                {name: 'tipo_de_campo', index: 'tipo_de_campo',
                    width: 5,
                    align: "center",
                    sortable: true,
                    sorttype: 'text',
                    search: true,
                    stype: 'select',
                    searchoptions: {value: ":;C:Caracter;N:Numero;F:Fecha"}
                }
            ],
            pager: "#pagerDatosFamiliares",
            sortname: "id",
            sortorder: "ASC",
            viewrecords: true,
            viewsortcols: [true, 'horizontal', true],
            gridview: true,
            hidegrid: false,
            ignoreCase: true,
            autoencode: true,
            forceFit: false,
            pgbuttons: false,
            pgtext: false,
            pginput: false,
            loadonce: true,
            editurl: "<?php echo $this->url('datosfamiliares', array('action' => 'editGridItem')); ?>",
            caption: "Datos de Familiares",
            onSelectRow: function (id) {
                loadGridDatosFamiliaresVal(id);
            }
        });
        $("#gridDatosFamiliares").navGrid("#pagerDatosFamiliares",
                {edit: false, add: false, del: false, search: false, refresh: false, view: false});
        $("#gridDatosFamiliares").navButtonAdd("#pagerDatosFamiliares", {
            caption: "Borrar filtros",
            title: "Borrar filtros",
            buttonicon: 'ui-icon-refresh',
            onClickButton: function () {
                jQuery("#gridDatosFamiliares")[0].clearToolbar();
                gridReload('gridDatosFamiliares');
            }
        });
        $('#gridDatosFamiliares').jqGrid('filterToolbar', {stringResult: true, searchOnEnter: false, autoSearch: false, defaultSearch: 'cn', ignoreCase: true});

        $("#gridDatosFamiliaresVal").jqGrid({
            width: 450,
            height: 230,
            shrinkToFit: true,
            forceFit: false,
            autowidth: false,
            rowNum: 1000,
            rownumbers: true,
            url: "<?php echo $this->url('datosfamiliares', array('action' => 'loadDataGridVal')); ?>",
            datatype: "json",
            mtype: 'GET',
            colNames: ["Id", "PropiedadId", "Valor", "Significado"],
            colModel: [
                {name: 'id', index: 'id',
                    width: 10,
                    align: "center",
                    sortable: false,
                    sorttype: 'int',
                    hidden: true
                },
                {name: 'propiedad', index: 'propiedad',
                    width: 10,
                    align: "center",
                    sortable: true,
                    sorttype: 'int',
                    hidden: true
                },
                {name: 'valor_posible', index: 'valor_posible',
                    width: 15,
                    align: "center",
                    sortable: false,
                    sorttype: 'text',
                    search: true,
                    stype: 'text',
                    searchoptions: {clearSearch: true},
                    editable: true,
                    editrules: {required: true},
                    editoptions: {size: 30}
                },
                {name: 'significado', index: 'significado',
                    width: 15,
                    align: "center",
                    sortable: false,
                    sorttype: 'text',
                    search: true,
                    stype: 'text',
                    searchoptions: {clearSearch: true},
                    editable: true,
                    editrules: {required: true},
                    editoptions: {size: 30}
                }
            ],
            pager: "#pagerDatosFamiliaresVal",
            sortname: "propiedad",
            sortorder: "ASC",
            viewrecords: true,
            viewsortcols: [true, 'horizontal', true],
            gridview: true,
            hidegrid: false,
            ignoreCase: true,
            autoencode: true,
            pgbuttons: false,
            pginput: false,
            loadonce: true,
            editurl: "<?php echo $this->url('datosfamiliares', array('action' => 'editGridItemVal')); ?>",
            caption: "Valores Posibles"
        });
        $("#gridDatosFamiliaresVal").navGrid("#pagerDatosFamiliaresVal",
                {edit: false, add: false, del: false, search: false, refresh: false, view: false});
        $("#gridDatosFamiliaresVal").navButtonAdd("#pagerDatosFamiliaresVal", {
            caption: "Borrar filtros",
            title: "Borrar filtros",
            buttonicon: 'ui-icon-refresh',
            onClickButton: function () {
                jQuery("#gridDatosFamiliaresVal")[0].clearToolbar();
            }
        });
        $('#gridDatosFamiliaresVal').jqGrid('filterToolbar', {stringResult: true, searchOnEnter: false, autoSearch: false, defaultSearch: 'cn', ignoreCase: true});

        //Buttons
        $("#btnAddDatosFamiliares").click(function () {
            openDiagDatosFamiliares("form-add-datosFamiliares", "add", "", "");
        });
        $("#btnDelDatosFamiliares").click(function () {
            var rowid = jQuery("#gridDatosFamiliares").jqGrid('getGridParam', 'selrow');
            if (rowid != null) {
                var ids = $("#gridDatosFamiliaresVal").jqGrid('getDataIDs');
                ids = ids.toString();
                ids = ids.split(",");
                var e = 0;

                if (ids != "") {
                    for (var i = 0; i < ids.length; i++) {
                        var data = $("#gridDatosFamiliaresVal").jqGrid('getRowData', ids[i]);
                        if (data['propiedad'] == rowid) {
                            e++;
                        }
                    }
                }

                if (e == 0) {
                    $.ajax({
                        url: "<?php echo $this->url('datosfamiliares', array('action' => 'deleteGridItem')); ?>",
                        global: false,
                        type: "GET",
                        data: "id=" + rowid,
                        dataType: "json",
                        async: true,
                        success: function (result) {
                            gridReload('gridDatosFamiliares');
                            gridReload('gridDatosFamiliaresVal');
                        },
                        error: function (xhr, ajaxOptions, thrownError) {
                            alert(xhr.status + " " + thrownError);
                        }
                    });
                } else {
                    msgAlert("diagAlertMain", "dataAlertMain", "No se puede eliminar la propiedad porque tiene valores asociados.");
                }
            }
            else {
                msgAlert("diagAlertMain", "dataAlertMain", "Por favor seleccione una fila.");
            }
        });
        $("#btnEditDatosFamiliares").click(function () {
            var rowid = jQuery("#gridDatosFamiliares").jqGrid('getGridParam', 'selrow');
            if (rowid != null) {
                openDiagDatosFamiliares("form-edit-datosFamiliares", "edit", "gridDatosFamiliares", rowid);
            }
            else {
                msgAlert("diagAlertMain", "dataAlertMain", "Por favor seleccione una fila.");
            }
        });
        $("#btnAddDatosFamiliaresVal").click(function () {
            var rowid = jQuery("#gridDatosFamiliares").jqGrid('getGridParam', 'selrow');
            var rowidVal = jQuery("#gridDatosFamiliaresVal").jqGrid('getGridParam', 'selrow');
            if (rowid != null) {
                openDiagDatosFamiliaresVal("form-add-datosFamiliaresVal", "add", "gridDatosFamiliaresVal", rowidVal);
            }
            else {
                msgAlert("diagAlertMain", "dataAlertMain", "Por favor seleccione una fila.");
            }
        });
        $("#btnDelDatosFamiliaresVal").click(function () {
            var rowid = jQuery("#gridDatosFamiliaresVal").jqGrid('getGridParam', 'selrow');
            if (rowid != null) {
                $.ajax({
                    url: "<?php echo $this->url('datosfamiliares', array('action' => 'deleteGridItemVal')); ?>",
                    global: false,
                    type: "GET",
                    data: "id=" + rowid,
                    dataType: "json",
                    async: true,
                    success: function () {
                        gridReload('gridDatosFamiliaresVal');
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        alert(xhr.status + " " + thrownError);
                    }
                });
            }
            else {
                msgAlert("diagAlertMain", "dataAlertMain", "Por favor seleccione una fila.");
            }
        });
        $("#btnEditDatosFamiliaresVal").click(function () {
            var rowid = jQuery("#gridDatosFamiliaresVal").jqGrid('getGridParam', 'selrow');
            if (rowid != null) {
                openDiagDatosFamiliaresVal("form-edit-datosFamiliaresVal", "edit", "gridDatosFamiliaresVal", rowid);
            }
            else {
                msgAlert("diagAlertMain", "dataAlertMain", "Por favor seleccione una fila.");
            }
        });

        //Dialog addDatosFamiliares
        $("#form-add-datosFamiliares").dialog({
            autoOpen: false,
            resizable: true,
            closeOnEscape: true,
            modal: true,
            width: 'auto', // overcomes width:'auto' and maxWidth bug
            height: 'auto',
            maxWidth: 600,
            buttons: {
                'Aceptar': function () {
                    if ($("#valid-form-add-datosFamiliares").valid()) {
                        var descripcion = $("#descripcionAddDatosFamiliares").val();
                        var tipo = $("#tipoAddDatosFamiliares").val();

                        var ids = $("#gridDatosFamiliares").jqGrid('getDataIDs');
                        ids = ids.toString();
                        ids = ids.split(",");
                        var e = 0;

                        if (ids != "") {
                            for (var i = 0; i < ids.length; i++) {
                                var data = $("#gridDatosFamiliares").jqGrid('getRowData', ids[i]);
                                if (data['descripcion'].toLowerCase() == descripcion.toLowerCase()) {
                                    e++;
                                }
                            }
                        }

                        if (e == 0) {
                            var data = {
                                "descripcion": descripcion,
                                "tipo_de_campo": tipo
                            };
                            $.ajax({
                                url: "<?php echo $this->url('datosfamiliares', array('action' => 'editGridItem')); ?>",
                                global: false,
                                type: "POST",
                                data: "data=" + JSON.stringify(data),
                                dataType: "json",
                                async: true,
                                success: function (result) {
                                    gridReload('gridDatosFamiliares');
                                    $("#form-add-datosFamiliares").dialog('close');
                                },
                                error: function (xhr, ajaxOptions, thrownError) {
                                    alert(xhr.status + " " + thrownError);
                                }
                            });
                        } else {
                            msgAlert("diagAlertModalAddP", "dataAlertModalAddP", "Ya existe un registro con esa combinacion.");
                        }
                    }
                },
                'Cancelar': function () {
                    validFormAddDatosFamiliares.resetForm();
                    $(this).dialog('close');
                }
            },
            close: function () {
                validFormAddDatosFamiliares.resetForm();
            }
        });
        //Dialog editDatosFamiliares
        $("#form-edit-datosFamiliares").dialog({
            autoOpen: false,
            resizable: true,
            closeOnEscape: true,
            modal: true,
            width: 'auto', // overcomes width:'auto' and maxWidth bug
            height: 'auto',
            maxWidth: 600,
            buttons: {
                'Aceptar': function () {
                    if ($("#valid-form-add-datosFamiliares").valid()) {
                        var rowid = jQuery("#gridDatosFamiliares").jqGrid('getGridParam', 'selrow');
                        if (rowid != null) {
                            var ids = $("#gridDatosFamiliares").jqGrid('getDataIDs');
                            ids = ids.toString();
                            ids = ids.split(",");
                            var e = 0;

                            if (ids != "") {
                                for (var i = 0; i < ids.length; i++) {
                                    var data = $("#gridDatosFamiliares").jqGrid('getRowData', ids[i]);
                                    if (data['descripcion'].toLowerCase() == $("#descripcionEditDatosFamiliares").val().toLowerCase() && data['id'] != rowid) {
                                        e++;
                                    }
                                }
                            }

                            if (e == 0)
                            {
                                var data = {
                                    "id": rowid,
                                    "descripcion": $("#descripcionEditDatosFamiliares").val(),
                                    "tipo_de_campo": $("#tipoEditDatosFamiliares").val()
                                };
                                $.ajax({
                                    url: "<?php echo $this->url('datosfamiliares', array('action' => 'editGridItem')); ?>",
                                    global: false,
                                    type: "POST",
                                    data: "data=" + JSON.stringify(data),
                                    dataType: "json",
                                    async: true,
                                    success: function (result) {
                                        gridReload('gridDatosFamiliares');
                                        $("#form-edit-datosFamiliares").dialog('close');
                                    },
                                    error: function (xhr, ajaxOptions, thrownError) {
                                        alert(xhr.status + " " + thrownError);
                                    }
                                });
                            } else {
                                msgAlert("diagAlertModalEditP", "dataAlertModal", "Ya existe un registro con esa combinacion.");
                            }
                        }
                    }
                },
                'Cancelar': function () {
                    validFormEditDatosFamiliares.resetForm();
                    $(this).dialog('close');
                }
            },
            close: function () {
                validFormEditDatosFamiliares.resetForm();
            }
        });
        //Dialog addDatosFamiliaresVal
        $("#form-add-datosFamiliaresVal").dialog({
            autoOpen: false,
            resizable: true,
            closeOnEscape: true,
            modal: true,
            width: 'auto', // overcomes width:'auto' and maxWidth bug
            height: 'auto',
            maxWidth: 600,
            buttons: {
                'Aceptar': function () {
                    if ($("#valid-form-add-datosFamiliares").valid()) {
                        var rowid = jQuery("#gridDatosFamiliares").jqGrid('getGridParam', 'selrow');
                        var ids = $("#gridDatosFamiliaresVal").jqGrid('getDataIDs');
                        ids = ids.toString();
                        ids = ids.split(",");
                        var e = 0;

                        if (ids != "") {
                            for (var i = 0; i < ids.length; i++) {
                                var data = $("#gridDatosFamiliaresVal").jqGrid('getRowData', ids[i]);
                                if (data['propiedad'] == rowid && data['valor_posible'].toLowerCase() == $("#valorPosibleAddDatosFamiliaresVal").val().toLowerCase()) {
                                    e++;
                                }
                            }
                        }

                        if (e == 0)
                        {
                            var data = {
                                "propiedad": rowid,
                                "valor_posible": $("#valorPosibleAddDatosFamiliaresVal").val(),
                                "significado": $("#significadoAddDatosFamiliaresVal").val()
                            };
                            $.ajax({
                                url: "<?php echo $this->url('datosfamiliares', array('action' => 'editGridItemVal')); ?>",
                                global: false,
                                type: "POST",
                                data: "data=" + JSON.stringify(data),
                                dataType: "json",
                                async: true,
                                success: function () {
                                    loadGridDatosFamiliaresVal(rowid);
                                    $("#form-add-datosFamiliaresVal").dialog('close');
                                },
                                error: function (xhr, ajaxOptions, thrownError) {
                                    alert(xhr.status + " " + thrownError);
                                }
                            });
                        } else {
                            msgAlert("diagAlertModalAddPV", "dataAlertModal", "Ya existe un registro con esa combinacion.");
                        }
                    }
                },
                Cancel: function () {
                    validFormAddDatosFamiliaresVal.resetForm();
                    $(this).dialog('close');
                }
            },
            close: function () {
                validFormAddDatosFamiliaresVal.resetForm();
            }
        });
        //Dialog editDatosFamiliaresVal
        $("#form-edit-datosFamiliaresVal").dialog({
            autoOpen: false,
            resizable: true,
            closeOnEscape: true,
            modal: true,
            width: 'auto', // overcomes width:'auto' and maxWidth bug
            height: 'auto',
            maxWidth: 600,
            buttons: {
                'Aceptar': function () {
                    if ($("#valid-form-add-datosFamiliares").valid()) {
                        var rowid = jQuery("#gridDatosFamiliaresVal").jqGrid('getGridParam', 'selrow');
                        if (rowid != null) {
                            var dataGrid = $("#gridDatosFamiliaresVal").jqGrid('getRowData', rowid);
                            var ids = $("#gridDatosFamiliaresVal").jqGrid('getDataIDs');
                            ids = ids.toString();
                            ids = ids.split(",");
                            var e = 0;

                            if (ids != "") {
                                for (var i = 0; i < ids.length; i++) {
                                    var data = $("#gridDatosFamiliaresVal").jqGrid('getRowData', ids[i]);
                                    if (data['valor_posible'].toLowerCase() == $("#valorPosibleEditDatosFamiliaresVal").val().toLowerCase() && data['id'] != rowid) {
                                        e++;
                                    }
                                }
                            }

                            if (e == 0)
                            {
                                var data = {
                                    "id": rowid,
                                    "valor_posible": $("#valorPosibleEditDatosFamiliaresVal").val(),
                                    "significado": $("#significadoEditDatosFamiliaresVal").val()
                                };
                                $.ajax({
                                    url: "<?php echo $this->url('datosfamiliares', array('action' => 'editGridItemVal')); ?>",
                                    global: false,
                                    type: "POST",
                                    data: "data=" + JSON.stringify(data),
                                    dataType: "json",
                                    async: true,
                                    success: function (result) {
                                        loadGridDatosFamiliaresVal(dataGrid.propiedad);
                                        $("#form-edit-datosFamiliaresVal").dialog('close');
                                    },
                                    error: function (xhr, ajaxOptions, thrownError) {
                                        alert(xhr.status + " " + thrownError);
                                    }
                                });
                            } else {
                                msgAlert("diagAlertModalEditPV", "dataAlertModalEditPV", "Ya existe un registro con esa combinacion.");
                            }
                        }
                    }
                },
                Cancel: function () {
                    validFormEditDatosFamiliaresVal.resetForm();
                    $(this).dialog('close');
                }
            },
            close: function () {
                validFormEditDatosFamiliaresVal.resetForm();
            }
        });

        //Validation
        var validFormAddDatosFamiliares = $("#valid-form-add-datosFamiliares").validate({
            rules: {
                descripcionAddDatosFamiliares: {required: true}
            }
        });
        var validFormEditDatosFamiliares = $("#valid-form-edit-datosFamiliares").validate({
            rules: {
                descripcionEditDatosFamiliares: {required: true}
            }
        });
        var validFormAddDatosFamiliaresVal = $("#valid-form-add-datosFamiliaresVal").validate({
            rules: {
                valorPosibleAddDatosFamiliaresVal: {required: true},
                significadoAddDatosFamiliaresVal: {required: true}
            }
        });
        var validFormEditDatosFamiliaresVal = $("#valid-form-edit-datosFamiliaresVal").validate({
            rules: {
                valorPosibleEditDatosFamiliaresVal: {required: true},
                significadoEditDatosFamiliaresVal: {required: true}
            }
        });

        //AlertManager
        $('#diagAlertMain').on('closed.bs.alert', function () {
            $('.dataAlertMain').html("");
        });
        $('#diagAlertModalAddP').on('closed.bs.alert', function () {
            $('.dataAlertModalAddP').html("");
        });
        $('#diagAlertModalEditP').on('closed.bs.alert', function () {
            $('.dataAlertModalEditP').html("");
        });
        $('#diagAlertModalAddPV').on('closed.bs.alert', function () {
            $('.dataAlertModalAddPV').html("");
        });
        $('#diagAlertModalEditPV').on('closed.bs.alert', function () {
            $('.dataAlertModalEditPV').html("");
        });
    });

    // remove window resize namespace
    $(document).on("dialogclose", ".ui-dialog", function (event, ui) {
        $(window).off("resize.responsive");
    });

    function gridReload(gridName) {
        $("#" + gridName).setGridParam({datatype: 'json'})/*.setGridParam({rowNum: 1000})*/.trigger('reloadGrid');
    }

    function loadGridDatosFamiliaresVal(id) {
        if (id != null) {
            var sUrl = "<?php echo $this->url('datosfamiliares', array('action' => 'loadDataGridVal')); ?>" + "/" + id;
            $("#gridDatosFamiliaresVal").setGridParam({datatype: 'json', url: sUrl}).trigger('reloadGrid');
        }
        else {
            msgAlert("diagAlertMain", "dataAlertMain", "Por favor seleccione una fila.");
        }
    }

    function openDiagDatosFamiliares(diagName, op, grid, id) {
        clearDataDatosFamiliares();
        if (op == "edit") {
            rowdata = jQuery("#" + grid).getRowData(id);
            $('#descripcionEditDatosFamiliares').val(rowdata['descripcion']);
            $('#tipoEditDatosFamiliares').val(rowdata['tipo_de_campo']);
            $('#' + diagName).dialog('open');
        } else {
            $('#' + diagName).dialog('open');
            $('#tipoAddDatosFamiliares option:contains("C")').prop('selected', true);
        }
    }

    function openDiagDatosFamiliaresVal(diagName, op, grid, id) {
        clearDataDatosFamiliaresVal();
        if (op == "edit") {
            rowdata = jQuery("#" + grid).getRowData(id);
            $('#valorPosibleEditDatosFamiliaresVal').val(rowdata['valor_posible']);
            $('#significadoEditDatosFamiliaresVal').val(rowdata['significado']);
            $('#' + diagName).dialog('open');
        } else {
            $('#' + diagName).dialog('open');
        }
    }

    function clearDataDatosFamiliares() {
        $('#descripcionAddDatosFamiliares').val("");
        $('#descripcionEditDatosFamiliares').val("");
    }

    function clearDataDatosFamiliaresVal() {
        $('#valorPosibleAddDatosFamiliaresVal').val("");
        $('#significadoAddDatosFamiliaresVal').val("");
        $('#valorPosibleEditDatosFamiliaresVal').val("");
        $('#significadoEditDatosFamiliaresVal').val("");
    }

    function msgAlert(diagName, selectorName, msg) {
        $('#' + diagName).show();
        $('.' + selectorName).html(msg);
        setTimeout(function () {
            $('#' + diagName).hide("drop", {direction: "up"}, "slow");
            $('.' + selectorName).html("");
        }, 3000);
        return;
    }

</script>

<!-- Dialogo form-add-datosFamiliares -->
<div id="form-add-datosFamiliares"  title="Agregar registro">
    <form class="form-horizontal" id="valid-form-add-datosFamiliares" role="form">
        <div class="form-group">
            <label for="descripcionAddDatosFamiliares" class="col-sm-4 control-label">Nombre de campo:</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="descripcionAddDatosFamiliares" name="descripcionAddDatosFamiliares" placeholder="">
            </div>
        </div>
        <div class="form-group">
            <label for="tipoAddDatosFamiliares" class="col-sm-4 control-label">Tipo:</label>
            <div class="col-sm-8">
                <select class="form-control" id="tipoAddDatosFamiliares" name="tipoAddDatosFamiliares">
                    <option value="C">Caracter</option>
                    <option value="N">Numero</option>
                    <option value="F">Fecha</option>
                </select>
            </div>
        </div>
    </form>
    <div class="alert alert-warning ui-state-highlight ui-corner-all"" id="diagAlertModalAddP">
        <a href="#" class="close" data-dismiss="alert">&times;</a>
        <strong><span class="dataAlertModalAddP"></span></strong>
    </div>
</div>

<!-- Dialogo form-edit-datosFamiliares -->
<div id="form-edit-datosFamiliares"  title="Editar registro">
    <form class="form-horizontal" id="valid-form-edit-datosFamiliares" role="form">
        <div class="form-group">
            <label for="descripcionEditDatosFamiliares" class="col-sm-4 control-label">Nombre de campo:</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="descripcionEditDatosFamiliares" name="descripcionEditDatosFamiliares" placeholder="">
            </div>
        </div>
        <div class="form-group">
            <label for="tipoEditDatosFamiliares" class="col-sm-4 control-label">Tipo:</label>
            <div class="col-sm-8">
                <select class="form-control" id="tipoEditDatosFamiliares" name="tipoEditDatosFamiliares">
                    <option value="C">Caracter</option>
                    <option value="N">Numero</option>
                    <option value="F">Fecha</option>
                </select>
            </div>
        </div>
    </form>
    <div class="alert alert-warning ui-state-highlight ui-corner-all"" id="diagAlertModalEditP">
        <a href="#" class="close" data-dismiss="alert">&times;</a>
        <strong><span class="dataAlertModalEditP"></span></strong>
    </div>
</div>

<!-- Dialogo form-add-datosFamiliaresVal -->
<div id="form-add-datosFamiliaresVal"  title="Agregar registro">
    <form class="form-horizontal" id="valid-form-add-datosFamiliaresVal" role="form">
        <div class="form-group">
            <label for="valorPosibleAddDatosFamiliaresVal" class="col-sm-4 control-label">Valor:</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="valorPosibleAddDatosFamiliaresVal" name="valorPosibleAddDatosFamiliaresVal" placeholder="">
            </div>
        </div>
        <div class="form-group">
            <label for="significadoAddDatosFamiliaresVal" class="col-sm-4 control-label">Significado:</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="significadoAddDatosFamiliaresVal" name="significadoAddDatosFamiliaresVal"placeholder="">
            </div>
        </div>
    </form>
    <div class="alert alert-warning ui-state-highlight ui-corner-all"" id="diagAlertModalAddPV">
        <a href="#" class="close" data-dismiss="alert">&times;</a>
        <strong><span class="dataAlertModalAddPV"></span></strong>
    </div>
</div>

<!-- Dialogo form-add-datosFamiliaresVal -->
<div id="form-edit-datosFamiliaresVal"  title="Editar registro">
    <form class="form-horizontal" id="valid-form-edit-datosFamiliaresVal" role="form">
        <div class="form-group">
            <label for="valorPosibleEditDatosFamiliaresVal" class="col-sm-4 control-label">Valor:</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="valorPosibleEditDatosFamiliaresVal" name="valorPosibleEditDatosFamiliaresVal"placeholder="">
            </div>
        </div>
        <div class="form-group">
            <label for="significadoEditDatosFamiliaresVal" class="col-sm-4 control-label">Significado:</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="significadoEditDatosFamiliaresVal" name="significadoEditDatosFamiliaresVal" placeholder="">
            </div>
        </div>
    </form>
    <div class="alert alert-warning ui-state-highlight ui-corner-all"" id="diagAlertModalEditPV">
        <a href="#" class="close" data-dismiss="alert">&times;</a>
        <strong><span class="dataAlertModalEditPV"></span></strong>
    </div>
</div>