<?php
$title = 'Vistas de datos de Familiares';
?>
<h1 class="page-header" style="padding-top:20px"><?php echo $this->escapeHtml($title); ?></h1>
<?php
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
            &times;
            </button>
        <ul><li>')
        ->setMessageSeparatorString('</li><li>')
        ->setMessageCloseString('</li></ul></div>');

echo $flash->render('error', array('alert', 'alert-dismissable', 'alert-danger', 'flashAlert'));
echo $flash->render('info', array('alert', 'alert-dismissable', 'alert-info', 'flashAlert'));
echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning', 'flashAlert'));
echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success', 'flashAlert'));
?>

<div class="alert alert-warning" id="diagAlert">
    <a href="#" class="close" data-dismiss="alert">&times;</a>
    <strong><span class="dataAlert"></span></strong>
</div>

<br>
<div class="content">
    <div class="row">
        <div class="col-xs-6">
            <div class="btn-group">
                <button type="button" class="btn btn-primary btn-lg" id="btnAddVistasFamiliares">Alta</button>
                <button type="button" class="btn btn-primary btn-lg" id="btnDelVistasFamiliares">Baja</button>
                <button type="button" class="btn btn-primary btn-lg" id="btnEditVistasFamiliares">Modificacion</button>
            </div>
            <br>
            <div id="jqGridVistasFamiliares" style="padding-top:10px;">
                <table id="gridVistasFamiliares"></table>
                <div id="pagerVistasFamiliares"></div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    var oEdit = false;
    var lastSel;
    $(document).ready(function () {
        //Grids
        $("#gridVistasFamiliares").jqGrid({
            width: 100,
            height: 230,
            autowidth: true,
            rownumbers: true,
            url: "<?php echo $this->url('vistasfamiliares', array('action' => 'loadViewGrid')); ?>",
            datatype: 'json',
            mtype: 'POST',
            colNames: ["Id", "Vista", "Extranet"],
            colModel: [
                {name: 'id', index: 'id',
                    width: 10,
                    align: "center",
                    sortable: false,
                    sorttype: 'int',
                    hidden: true
                },
                {name: 'descripcion', index: 'descripcion',
                    width: 30,
                    align: "center",
                    sortable: true,
                    sorttype: 'text',
                    search: true,
                    stype: 'text',
                    searchoptions: {clearSearch: true}
                },
                {name: 'extranet_permitido', index: 'extranet_permitido',
                    width: 5,
                    align: "center",
                    sortable: true,
                    sorttype: 'text',
                    search: true,
                    stype: 'select',
                    searchoptions: {value: ":;S:Si;N:No"}
                }
            ],
            pager: "#pagerVistasFamiliares",
            sortname: "id",
            sortorder: "ASC",
            viewrecords: true,
            viewsortcols: [true, 'horizontal', true],
            gridview: true,
            hidegrid: false,
            ignoreCase: true,
            autoencode: true,
            forceFit: false,
            pgbuttons: false,
            pgtext: false,
            pginput: false,
            loadonce: true,
            editurl: "<?php echo $this->url('vistasfamiliares', array('action' => 'editGridItem')); ?>",
            caption: "Vistas de Familiares"
        });
        $("#gridVistasFamiliares").navGrid("#pagerVistasFamiliares",
                {edit: false, add: false, del: false, search: false, refresh: false, view: false});
        $("#gridVistasFamiliares").navButtonAdd("#pagerVistasFamiliares", {
            caption: "Borrar filtros",
            title: "Borrar filtros",
            buttonicon: 'ui-icon-refresh',
            onClickButton: function () {
                jQuery("#gridVistasFamiliares")[0].clearToolbar();
                gridReload('gridVistasFamiliares');
            }
        });
        $('#gridVistasFamiliares').jqGrid('filterToolbar', {stringResult: true, searchOnEnter: false, autoSearch: false, defaultSearch: 'cn', ignoreCase: true});

        $("#gridPropiedadesFamiliares").jqGrid({
            width: 460,
            height: 150,
            shrinkToFit: true,
            forceFit: false,
            autowidth: false,
            rowNum: 1000,
            rownumbers: true,
            datatype: "local",
            colNames: ["Id", "Propiedad", "Tipo"],
            colModel: [
                {name: 'id', index: 'id',
                    width: 10,
                    align: "center",
                    sortable: false,
                    sorttype: 'int',
                    hidden: true
                },
                {name: 'descripcion', index: 'descripcion',
                    width: 30,
                    align: "center",
                    sortable: true,
                    sorttype: 'text',
                    search: true,
                    stype: 'text',
                    searchoptions: {clearSearch: true}
                },
                {name: 'tipo_de_campo', index: 'tipo_de_campo',
                    width: 10,
                    align: "center",
                    sortable: true,
                    sorttype: 'text',
                    search: true,
                    stype: 'select',
                    searchoptions: {value: ":;C:Caracter;N:Numero;F:Fecha"}
                }
            ],
            pager: "#pagerPropiedadesFamiliares",
            sortname: "id",
            sortorder: "ASC",
            viewrecords: true,
            viewsortcols: [true, 'horizontal', true],
            gridview: true,
            hidegrid: false,
            ignoreCase: true,
            autoencode: true,
            pgbuttons: false,
            pgtext: false,
            pginput: false,
            loadonce: true,
            caption: "Lista de datos posibles"
        });
        $("#gridPropiedadesFamiliares").navGrid("#pagerPropiedadesFamiliares",
                {edit: false, add: false, del: false, search: false, refresh: false, view: false});
//        $("#gridPropiedadesFamiliares").navButtonAdd("#pagerPropiedadesFamiliares", {
//            caption: "Borrar filtros",
//            title: "Borrar filtros",
//            buttonicon: 'ui-icon-refresh',
//            onClickButton: function () {
//                jQuery("#gridPropiedadesFamiliares")[0].clearToolbar();
//                //loadGrid('gridPropiedadesFamiliares');
//                //gridReload('gridPropiedadesFamiliares');
//            }
//        });
        $('#gridPropiedadesFamiliares').jqGrid('filterToolbar', {stringResult: true, searchOnEnter: false, autoSearch: false, defaultSearch: 'cn', ignoreCase: true});

        $("#gridDatosVistasFamiliares").jqGrid({
            width: 400,
            height: 150,
            shrinkToFit: true,
            forceFit: false,
            autowidth: false,
            rowNum: 1000,
            rownumbers: true,
            datatype: 'local',
            colNames: ["Id", "PropiedadId", "Propiedad", "Tipo", "FormularioId", "Orden", "Modificable"],
            colModel: [
                {name: 'id', index: 'id',
                    width: 10,
                    align: "center",
                    sortable: false,
                    sorttype: 'int',
                    hidden: true
                },
                {name: 'propiedadId', index: 'propiedadId',
                    width: 10,
                    align: "center",
                    sortable: true,
                    sorttype: 'int',
                    hidden: true
                },
                {name: 'propiedad', index: 'propiedad',
                    width: 30,
                    align: "center",
                    sortable: true,
                    sorttype: 'text',
                    search: true,
                    stype: 'text',
                    searchoptions: {clearSearch: true}
                },
                {name: 'tipo', index: 'tipo',
                    width: 10,
                    align: "center",
                    sortable: false,
                    sorttype: 'text',
                    hidden: true
                },
                {name: 'formularioId', index: 'formularioId',
                    width: 10,
                    align: "center",
                    sortable: false,
                    sorttype: 'int',
                    hidden: true
                },
                {name: 'orden', index: 'orden',
                    width: 10,
                    align: "center",
                    sortable: true,
                    search: true,
                    stype: 'text',
                    searchoptions: {clearSearch: true},
                    editable: false,
                    editoptions: {size: 30}
                },
                {name: 'solo_lectura', index: 'solo_lectura',
                    width: 10,
                    align: "center",
                    sortable: true,
                    search: true,
                    stype: 'select',
                    searchoptions: {value: ":;S:Si;N:No"},
                    editable: true,
                    edittype: 'select',
                    editoptions: {value: ":;S:Si;N:No"}
                }
            ],
            pager: "#pagerDatosVistasFamiliares",
            sortname: "id",
            sortorder: "ASC",
            viewrecords: true,
            viewsortcols: [true, 'horizontal', true],
            gridview: true,
            hidegrid: false,
            ignoreCase: true,
            autoencode: true,
            pgbuttons: false,
            pgtext: false,
            pginput: false,
            loadonce: true,
            editurl: "clientArray",
            caption: "Datos en las vistas",
            cellEdit: true,
            cellsubmit: 'clientArray'
        });
        $("#gridDatosVistasFamiliares").navGrid("#pagerDatosVistasFamiliares",
                {edit: false, add: false, del: false, search: false, refresh: false, view: false});
//        $("#gridDatosVistasFamiliares").navButtonAdd("#pagerDatosVistasFamiliares", {
//            caption: "Borrar filtros",
//            title: "Borrar filtros",
//            buttonicon: 'ui-icon-refresh',
//            onClickButton: function () {
//                jQuery("#gridDatosVistasFamiliares")[0].clearToolbar();
//                //loadGrid('gridDatosVistasFamiliares');
//                //gridReload('gridDatosVistasFamiliares');
//            }
//        });
        $('#gridDatosVistasFamiliares').jqGrid('filterToolbar', {stringResult: true, searchOnEnter: false, autoSearch: false, defaultSearch: 'cn', ignoreCase: true});
        jQuery("#gridDatosVistasFamiliares").jqGrid('sortableRows', {
            update: function (e, ui) {
                reOrder('gridDatosVistasFamiliares', 'orden');
            }
        });

        //Buttons
        $("#btnAddVistasFamiliares").click(function () {
            openDiagVistasFamiliares("form-add-edit-VistasFamiliares", "add", "", "");
        });
        $("#btnDelVistasFamiliares").click(function () {
            var rowid = jQuery("#gridVistasFamiliares").jqGrid('getGridParam', 'selrow');
            if (rowid != null) {
                $.ajax({
                    url: "<?php echo $this->url('vistasfamiliares', array('action' => 'deleteGridItem')); ?>",
                    global: false,
                    type: "POST",
                    data: "id=" + rowid,
                    dataType: "json",
                    async: false,
                    success: function (msg) {
                        gridReload('gridVistasFamiliares');
                    }
                });
            }
            else {
                msgAlert("diagAlert", "dataAlert", "Por favor seleccione una fila.");
            }
        });
        $("#btnEditVistasFamiliares").click(function () {
            var rowid = jQuery("#gridVistasFamiliares").jqGrid('getGridParam', 'selrow');
            if (rowid != null) {
                openDiagVistasFamiliares("form-add-edit-VistasFamiliares", "edit", "gridVistasFamiliares", rowid);
            }
            else {
                msgAlert("diagAlert", "dataAlert", "Por favor seleccione una fila.");
            }
        });

        //btnAddAllData =>>
        $("#btnAddAllData").click(function () {
            var dataGrid = jQuery("#gridPropiedadesFamiliares").jqGrid('getGridParam', 'data');
            if (dataGrid.length > 0) {
                for (var i = 0; i < dataGrid.length; i++) {
                    var ids = $("#gridDatosVistasFamiliares").jqGrid('getDataIDs');
                    ids = ids.toString();
                    ids = ids.split(",");

                    var data = {
                        "propiedadId": dataGrid[i]['id'],
                        "propiedad": dataGrid[i]['descripcion'],
                        "tipo": dataGrid[i]['tipo_de_campo'],
                        "formularioId": "",
                        "orden": (ids.length > 0 && ids[0] != 'undefined' && ids[0] != "") ? ids.length + 1 : 1,
                        "solo_lectura": "Si"
                    };

                    if (ids.length > 0 && ids[0] != 'undefined' && ids[0] != "") {
                        $("#gridDatosVistasFamiliares").jqGrid('addRowData', parseInt(ids[ids.length - 1]) + 1, data);
                    } else {
                        $("#gridDatosVistasFamiliares").jqGrid('addRowData', 1, data);
                    }
                }
                deleteGrid('gridPropiedadesFamiliares');
            }
        });
        //btnAddSingleData >
        $("#btnAddSingleData").click(function () {
            var rowid = jQuery("#gridPropiedadesFamiliares").jqGrid('getGridParam', 'selrow');
            if (rowid != null) {
                var dataRow = $("#gridPropiedadesFamiliares").jqGrid('getRowData', rowid);
                var ids = $("#gridDatosVistasFamiliares").jqGrid('getDataIDs');
                ids = ids.toString();
                ids = ids.split(",");

                var data = {
                    "propiedadId": dataRow['id'],
                    "propiedad": dataRow['descripcion'],
                    "tipo": dataRow['tipo_de_campo'],
                    "formularioId": "",
                    "orden": (ids.length > 0 && ids[0] != 'undefined' && ids[0] != "") ? ids.length + 1 : 1,
                    "solo_lectura": "Si"
                };

                if (ids.length > 0 && ids[0] != 'undefined' && ids[0] != "") {
                    $("#gridDatosVistasFamiliares").jqGrid('addRowData', ids.length + 1, data);
                } else {
                    $("#gridDatosVistasFamiliares").jqGrid('addRowData', 1, data);
                }
                $("#gridPropiedadesFamiliares").jqGrid('delRowData', rowid);
            }
            else {
                msgAlert("diagAlertModal", "dataAlertModal", "Por favor seleccione una fila.");
            }
        });
        //btnDelSingleData <
        $("#btnDelSingleData").click(function () {
            var rowid = jQuery("#gridDatosVistasFamiliares").jqGrid('getGridParam', 'selrow');
            if (rowid != null) {
                var dataRow = $("#gridDatosVistasFamiliares").jqGrid('getRowData', rowid);
                var data = {
                    "id": dataRow['propiedadId'],
                    "descripcion": dataRow['propiedad'],
                    "tipo_de_campo": dataRow['tipo']
                };

                $("#gridPropiedadesFamiliares").jqGrid('addRowData', dataRow['propiedadId'], data);
                $("#gridDatosVistasFamiliares").jqGrid('delRowData', rowid);
                reOrder('gridDatosVistasFamiliares', 'orden');
                $("#gridPropiedadesFamiliares").setGridParam({datatype: 'local', sortname: 'id'}).trigger('reloadGrid');
            }
            else {
                msgAlert("diagAlertModal", "dataAlertModal", "Por favor seleccione una fila.");
            }
        });
        //btnDelAllData <<=
        $("#btnDelAllData").click(function () {
            var dataGrid = jQuery("#gridDatosVistasFamiliares").jqGrid('getGridParam', 'data');
            if (dataGrid.length > 0) {
                for (var i = 0; i < dataGrid.length; i++) {
                    var ids = $("#gridPropiedadesFamiliares").jqGrid('getDataIDs');
                    ids = ids.toString();
                    ids = ids.split(",");

                    var data = {
                        "id": dataGrid[i]['propiedadId'],
                        "descripcion": dataGrid[i]['propiedad'],
                        "tipo_de_campo": dataGrid[i]['tipo']
                    };

                    if (ids.length > 0 && ids[0] != 'undefined' && ids[0] != "") {
                        $("#gridPropiedadesFamiliares").jqGrid('addRowData', parseInt(ids[ids.length - 1]) + 1, data);
                    } else {
                        $("#gridPropiedadesFamiliares").jqGrid('addRowData', 1, data);
                    }
                }
                $("#gridPropiedadesFamiliares").setGridParam({datatype: 'local', sortname: 'id'}).trigger('reloadGrid');
                deleteGrid('gridDatosVistasFamiliares');
            }
        });

        //Dialog addVistasFamiliares
        $("#form-add-edit-VistasFamiliares").dialog({
            autoOpen: false,
            resizable: true,
            draggable: true,
            closeOnEscape: false,
            modal: true,
            width: 'auto', //1000, 
            height: 'auto', //500,
            maxWidth: 1200,
            //position: ['center',110] , //{ my: "center", at: "center", of: window }
            //fluid: true, //new option
            open: function (event, ui) {
                $(event.target).parent().css('position', 'fixed');
                $(event.target).parent().css('top', '110px');
                $(event.target).parent().css('left', '275px');
            },
            buttons: {
                'Aceptar': function () {
                    var descripcion = $("#descripcion-add-VistasFamiliares").val();
                    var extranet = $("#extranet-add-VistasFamiliares").val();

                    if (descripcion != '') {
                        var ids = $("#gridVistasFamiliares").jqGrid('getDataIDs');
                        ids = ids.toString();
                        ids = ids.split(",");

                        var e = 0;
                        var rowid = "";

                        if (oEdit) {
                            rowid = jQuery("#gridVistasFamiliares").jqGrid('getGridParam', 'selrow');
                            if (rowid != null) {
                                if (ids != "") {
                                    for (var i = 0; i < ids.length; i++) {
                                        var data = $("#gridVistasFamiliares").jqGrid('getRowData', ids[i]);
                                        if (data['descripcion'].toLowerCase() == $("#descripcion-add-VistasFamiliares").val().toLowerCase() && data['id'] != rowid) {
                                            e++;
                                        }
                                    }
                                }
                            } else {
                                msgAlert("diagAlert", "dataAlert", "Por favor seleccione una fila.");
                            }
                        } else {
                            if (ids != "") {
                                for (var i = 0; i < ids.length; i++) {
                                    var data = $("#gridVistasFamiliares").jqGrid('getRowData', ids[i]);
                                    if (data['descripcion'].toLowerCase() == descripcion.toLowerCase()) {
                                        e++;
                                    }
                                }
                            }
                        }
                        if (e == 0) {
                            var dataGridDatosVistas = jQuery("#gridDatosVistasFamiliares").jqGrid('getGridParam', 'data');
                            if (dataGridDatosVistas.length > 0) {
                                var data = {
                                    "id": rowid,
                                    "descripcion": descripcion,
                                    "extranet_permitido": extranet,
                                    "vistas_propiedades": dataGridDatosVistas
                                };
                                $.ajax({
                                    url: "<?php echo $this->url('vistasfamiliares', array('action' => 'editGridItem')); ?>",
                                    global: false,
                                    type: "POST",
                                    data: "data=" + JSON.stringify(data),
                                    dataType: "json",
                                    async: false,
                                    success: function (msg) {
                                        gridReload('gridVistasFamiliares');
                                        $("#form-add-edit-VistasFamiliares").dialog('close');
                                    }
                                });
                            } else {
                                msgAlert("diagAlertModal", "dataAlertModal", "No ha agregado datos para la vista.");
                            }
                        } else {
                            msgAlert("diagAlertModal", "dataAlertModal", "Ya existe un registro con esa combinacion.");
                        }
                    } else {
                        msgAlert("diagAlertModal", "dataAlertModal", "Ingrese un valor al campo Vista.");
                    }
                },
                'Cancelar': function () {
                    deleteGrid('gridPropiedadesFamiliares');
                    deleteGrid('gridDatosVistasFamiliares');
                    $(this).dialog('close');
                }
            },
            close: function () {
                deleteGrid('gridPropiedadesFamiliares');
                deleteGrid('gridDatosVistasFamiliares');
            }
        });

        $('#diagAlert').on('closed.bs.alert', function () {
            $('.dataAlert').html("");
        });

        $('#diagAlertModal').on('closed.bs.alert', function () {
            $('.dataAlertModal').html("");
        });
    });

    // remove window resize namespace
    $(document).on("dialogclose", ".ui-dialog", function (event, ui) {
        $(window).off("resize.responsive");
    });

    function gridReload(gridName) {
        $("#" + gridName).setGridParam({datatype: 'json'})/*.setGridParam({rowNum: 10})*/.trigger('reloadGrid');
    }

    function openDiagVistasFamiliares(diagName, op, grid, id) {
        clearDataVistasFamiliares();
        if (op == "edit") {
            rowdata = jQuery("#" + grid).getRowData(id);
            $('#descripcion-add-VistasFamiliares').val(rowdata['descripcion']);
            $('#extranet-add-VistasFamiliares').val(rowdata['extranet_permitido']);
            $('#' + diagName).dialog("option", "title", "Editar registro");
            $('#' + diagName).dialog('open');
            $('#' + diagName).dialog('moveToTop');
            loadGrid("gridPropiedadesFamiliares", rowdata['id']);
            loadGrid("gridDatosVistasFamiliares", rowdata['id']);
            oEdit = true;
        } else {
            $('#' + diagName).dialog("option", "title", "Agregar registro");
            $('#' + diagName).dialog('open');
            $('#' + diagName).dialog('moveToTop');
            $('#extranet-add-VistasFamiliares option:contains("C")').prop('selected', true);
            loadGrid("gridPropiedadesFamiliares");
            loadGrid("gridDatosVistasFamiliares");
            oEdit = false;
        }
    }

    function clearDataVistasFamiliares() {
        $('#descripcion-add-VistasFamiliares').val("");
        $('#descripcion-edit-VistasFamiliares').val("");
    }

    function msgAlert(diagName, selectorName, msg) {
        $('#' + diagName).show();
        $('.' + selectorName).html(msg);
        setTimeout(function () {
            $('#' + diagName).hide("drop", {direction: "up"}, "slow");
            $('.' + selectorName).html("");
        }, 3000);
        return;
    }

    function loadGrid(gridName, rowid) {
        switch (gridName) {
            case 'gridPropiedadesFamiliares':
                $.ajax({
                    url: "<?php echo $this->url('vistasfamiliares', array('action' => 'loadPropGrid')); ?>",
                    global: false,
                    type: "POST",
                    data: "id=" + rowid,
                    dataType: "json",
                    async: false,
                    success: function (result) {
                        if (result.type == "success") {// ok	
                            deleteGrid('gridPropiedadesFamiliares');
                            if (result.data.length > 0) {
                                for (var i = 0; i < result.data.length; i++) {
                                    var dataLocal = {
                                        "id": result.data[i][0],
                                        "descripcion": result.data[i][1],
                                        "tipo_de_campo": result.data[i][2]
                                    };
                                    var ids = jQuery("#gridPropiedadesFamiliares").jqGrid('getDataIDs');
                                    ids = ids.toString();

                                    ids = ids.split(",");
                                    if (ids.length > 0 && ids[0] != 'undefined' && ids[0] != "") {
                                        $("#gridPropiedadesFamiliares").jqGrid('addRowData', ids.length + 1, dataLocal);
                                    } else {
                                        $("#gridPropiedadesFamiliares").jqGrid('addRowData', 1, dataLocal);
                                    }
                                }
                            }
                        }
                    }
                });
                break;
            case 'gridDatosVistasFamiliares':
                $.ajax({
                    url: "<?php echo $this->url('vistasfamiliares', array('action' => 'loadDataGrid')); ?>",
                    global: false,
                    type: "POST",
                    data: "id=" + rowid,
                    dataType: "json",
                    async: false,
                    success: function (result) {
                        if (result.type == "success") {
                            deleteGrid('gridDatosVistasFamiliares');
                            if (result.data.length > 0) {
                                for (var i = 0; i < result.data.length; i++) {
                                    var dataLocal = {
                                        "id": result.data[i][0],
                                        "propiedadId": result.data[i][1],
                                        "propiedad": result.data[i][2],
                                        "formularioId": result.data[i][3],
                                        "orden": result.data[i][4],
                                        "solo_lectura": result.data[i][5]
                                    };
                                    var ids = jQuery("#gridDatosVistasFamiliares").jqGrid('getDataIDs');
                                    ids = ids.toString();

                                    ids = ids.split(",");
                                    if (ids.length > 0 && ids[0] != 'undefined' && ids[0] != "") {
                                        $("#gridDatosVistasFamiliares").jqGrid('addRowData', ids.length + 1, dataLocal);
                                    } else {
                                        $("#gridDatosVistasFamiliares").jqGrid('addRowData', 1, dataLocal);
                                    }
                                }
                            }
                        }
                    }
                });
                break;
        }
    }

    function deleteGrid(gridName) {
        var $table;
        $table = $('#' + gridName);

        var ids = $table.jqGrid('getDataIDs');
        ids = ids.toString();
        ids = ids.split(",");
        if (ids.length > 0) {
            for (var i = 0; i < ids.length; i++) {
                $table.delRowData(ids[i]);
            }
        }
        $table.clearGridData(true).trigger("reloadGrid");
    }

    function reOrder(gridName, sortField) {
        var ids = $("#" + gridName).jqGrid('getDataIDs');
        ids = ids.toString();
        ids = ids.split(",");

        var orden = 1;

        if (ids != "") {
            for (var i = 0; i < ids.length; i++) {
                jQuery('#' + gridName).setCell(ids[i], sortField, orden);
                orden++;
            }
        }
    }

</script>

<!-- Dialogo form-add-edit-VistasFamiliares -->
<div id="form-add-edit-VistasFamiliares" class="container-fluid" title="" >
    <form class="form-horizontal" role="form">
        <div class="row">
            <div class="form-group col-xs-2 col-md-4">
                <label for="input-descripcion-add-VistasFamiliares" class="col-sm-4 control-label">Vista:</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="descripcion-add-VistasFamiliares" placeholder="">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-xs-2 col-md-4">
                <label for="input-extranet-add-VistasFamiliares" class="col-sm-4 control-label">Extranet:</label>
                <div class="col-sm-8">
                    <select class="form-control" id="extranet-add-VistasFamiliares">
                        <option value="S">Si</option>
                        <option value="N">No</option>
                    </select>
                </div>
            </div>
        </div>
    </form>
    <div class="row">
        <div class="col-xs-6 col-sm-6">
            <div id="jqGridPropiedadesFamiliares" style="padding-top:10px;">
                <table id="gridPropiedadesFamiliares"></table>
                <div id="pagerPropiedadesFamiliares"></div>
            </div>
        </div>
        <div class="col-xs-6 col-sm-1">
            <div class="btn-group-vertical" style="padding-top:70px;">
                <button type="button" class="btn btn-info btn-xs" id="btnAddAllData">=>></button>
                <button type="button" class="btn btn-info btn-xs" id="btnAddSingleData">></button>
                <button type="button" class="btn btn-info btn-xs" id="btnDelSingleData"><</button>
                <button type="button" class="btn btn-info btn-xs" id="btnDelAllData"><<=</button>
            </div>
        </div>
        <div class="col-xs-6 col-sm-5">
            <div id="jqGridDatosVistasFamiliares" style="padding-top:10px;">
                <table id="gridDatosVistasFamiliares"></table>
                <div id="pagerDatosVistasFamiliares"></div>
            </div>
        </div>
    </div>
    <div class="alert alert-warning" id="diagAlertModal">
        <a href="#" class="close" data-dismiss="alert">&times;</a>
        <strong><span class="dataAlertModal"></span></strong>
    </div>
</div>