<?php
$title = 'Vistas de datos de Empresas';
?>
<h1 class="page-header" style="padding-top:20px"><?php echo $this->escapeHtml($title); ?></h1>
<?php
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
            &times;
            </button>
        <ul><li>')
        ->setMessageSeparatorString('</li><li>')
        ->setMessageCloseString('</li></ul></div>');

echo $flash->render('error', array('alert', 'alert-dismissable', 'alert-danger', 'flashAlert'));
echo $flash->render('info', array('alert', 'alert-dismissable', 'alert-info', 'flashAlert'));
echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning', 'flashAlert'));
echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success', 'flashAlert'));
?>

<script type="text/javascript" src="../js/jqueryValidation/dist/jquery.validate.min.js"></script>    
<script type="text/javascript" src="../js/jqueryValidation/dist/additional-methods.min.js"></script>  
<script type="text/javascript" src="../js/jqueryValidation/dist/localization/messages_es_AR.min.js"></script> 

<div class="alert alert-warning ui-state-highlight ui-corner-all" id="diagAlertMain">
    <a href="#" class="close" data-dismiss="alert">&times;</a>
    <strong><span class="dataAlertMain"></span></strong>
</div>

<br>
<div class="content">
    <div class="row">
        <div class="col-xs-6">
            <div class="btn-group">
                <button type="button" class="btn btn-primary btn-lg" id="btnAddVistasEmpresa">Alta</button>
                <button type="button" class="btn btn-primary btn-lg" id="btnDelVistasEmpresa">Baja</button>
                <button type="button" class="btn btn-primary btn-lg" id="btnEditVistasEmpresa">Modificación</button>
            </div>
            <br>
            <div id="jqGridVistasEmpresa" style="padding-top:10px;">
                <table id="gridVistasEmpresa"></table>
                <div id="pagerVistasEmpresa"></div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    var oEdit = false;
    var lastSel;

    $(document).ready(function () {
        //Grids
        $("#gridVistasEmpresa").jqGrid({
            width: 100,
            height: 230,
            autowidth: true,
            rowNum: 1000,
            rownumbers: true,
            url: "<?php echo $this->url('vistasempresas', array('action' => 'loadViewGrid')); ?>",
            datatype: 'json',
            mtype: 'GET',
            colNames: ["Id", "Vista", "Extranet"],
            colModel: [
                {name: 'id', index: 'id',
                    width: 10,
                    align: "center",
                    sortable: false,
                    sorttype: 'int',
                    hidden: true
                },
                {name: 'descripcion', index: 'descripcion',
                    width: 30,
                    align: "center",
                    sortable: true,
                    sorttype: 'text',
                    search: true,
                    stype: 'text',
                    searchoptions: {clearSearch: true}
                },
                {name: 'extranet_permitido', index: 'extranet_permitido',
                    width: 5,
                    align: "center",
                    sortable: true,
                    sorttype: 'text',
                    search: true,
                    stype: 'select',
                    searchoptions: {value: ":;S:Si;N:No"}
                }
            ],
            pager: "#pagerVistasEmpresa",
            sortname: "id",
            sortorder: "ASC",
            viewrecords: true,
            viewsortcols: [true, 'horizontal', true],
            gridview: true,
            hidegrid: false,
            ignoreCase: true,
            autoencode: true,
            forceFit: false,
            pgbuttons: false,
            pgtext: false,
            pginput: false,
            loadonce: true,
            editurl: "<?php echo $this->url('vistasempresas', array('action' => 'editGridItem')); ?>",
            caption: "Vistas de Empresa"
        });
        $("#gridVistasEmpresa").navGrid("#pagerVistasEmpresa",
                {edit: false, add: false, del: false, search: false, refresh: false, view: false});
        $("#gridVistasEmpresa").navButtonAdd("#pagerVistasEmpresa", {
            caption: "Borrar filtros",
            title: "Borrar filtros",
            buttonicon: 'ui-icon-refresh',
            onClickButton: function () {
                jQuery("#gridVistasEmpresa")[0].clearToolbar();
                gridReload('gridVistasEmpresa');
            }
        });
        $('#gridVistasEmpresa').jqGrid('filterToolbar', {stringResult: true, searchOnEnter: false, autoSearch: false, defaultSearch: 'cn', ignoreCase: true});

        $("#gridPropiedadesEmpresa").jqGrid({
            width: 460,
            height: 150,
            shrinkToFit: true,
            forceFit: false,
            autowidth: true,
            rowNum: 1000,
            rownumbers: true,
            datatype: "local",
            colNames: ["Id", "Propiedad", "Tipo"],
            colModel: [
                {name: 'id', index: 'id',
                    width: 10,
                    align: "center",
                    sortable: false,
                    sorttype: 'int',
                    hidden: true
                },
                {name: 'descripcion', index: 'descripcion',
                    width: 30,
                    align: "center",
                    sortable: true,
                    sorttype: 'text',
                    search: true,
                    stype: 'text',
                    searchoptions: {clearSearch: true}
                },
                {name: 'tipo', index: 'tipo',
                    width: 10,
                    align: "center",
                    sortable: true,
                    sorttype: 'text',
                    search: true,
                    stype: 'select',
                    searchoptions: {value: ":;C:Caracter;N:Numero;F:Fecha"}
                }
            ],
            pager: "#pagerPropiedadesEmpresa",
            sortname: "id",
            sortorder: "ASC",
            viewrecords: true,
            viewsortcols: [true, 'horizontal', true],
            gridview: true,
            hidegrid: false,
            ignoreCase: true,
            autoencode: true,
            pgbuttons: false,
            pgtext: false,
            pginput: false,
            loadonce: true,
            caption: "Lista de datos posibles"
        });
        $("#gridPropiedadesEmpresa").navGrid("#pagerPropiedadesEmpresa",
                {edit: false, add: false, del: false, search: false, refresh: false, view: false});
        $("#gridPropiedadesEmpresa").navButtonAdd("#pagerPropiedadesEmpresa", {
            caption: "Borrar filtros",
            title: "Borrar filtros",
            buttonicon: 'ui-icon-refresh',
            onClickButton: function () {
                jQuery("#gridPropiedadesEmpresa")[0].clearToolbar();
            }
        });
        $('#gridPropiedadesEmpresa').jqGrid('filterToolbar', {stringResult: true, searchOnEnter: false, autoSearch: false, defaultSearch: 'cn', ignoreCase: true});

        $("#gridDatosVistasEmpresa").jqGrid({
            width: 400,
            height: 150,
            shrinkToFit: true,
            forceFit: false,
            autowidth: true,
            rowNum: 1000,
            rownumbers: true,
            datatype: 'local',
            colNames: ["Id", "PropiedadId", "Propiedad", "Tipo", "FormularioId", "Orden", "SL"],
            colModel: [
                {name: 'id', index: 'id',
                    width: 10,
                    align: "center",
                    sortable: false,
                    sorttype: 'int',
                    hidden: true
                },
                {name: 'propiedadId', index: 'propiedadId',
                    width: 10,
                    align: "center",
                    sortable: true,
                    sorttype: 'int',
                    hidden: true
                },
                {name: 'propiedad', index: 'propiedad',
                    width: 30,
                    align: "center",
                    sortable: true,
                    sorttype: 'text',
                    search: true,
                    stype: 'text',
                    searchoptions: {clearSearch: true}
                },
                {name: 'tipo', index: 'tipo',
                    width: 10,
                    align: "center",
                    sortable: false,
                    sorttype: 'text',
                    hidden: true
                },
                {name: 'formularioId', index: 'formularioId',
                    width: 10,
                    align: "center",
                    sortable: false,
                    sorttype: 'int',
                    hidden: true
                },
                {name: 'orden', index: 'orden',
                    width: 10,
                    align: "center",
                    sortable: true,
                    sorttype: 'int',
                    search: true,
                    stype: 'text',
                    searchoptions: {clearSearch: true},
                    editable: false,
                    editoptions: {size: 30}
                },
                {name: 'solo_lectura', index: 'solo_lectura',
                    width: 10,
                    align: "center",
                    sortable: true,
                    search: true,
                    stype: 'select',
                    searchoptions: {value: ":;S:Si;N:No"},
                    editable: true,
                    edittype: 'select',
                    editoptions: {value: ":;S:Si;N:No"}
                }
            ],
            pager: "#pagerDatosVistasEmpresa",
            sortname: "orden",
            sortorder: "ASC",
            viewrecords: true,
            viewsortcols: [true, 'horizontal', true],
            gridview: true,
            hidegrid: false,
            ignoreCase: true,
            autoencode: true,
            pgbuttons: false,
            pgtext: false,
            pginput: false,
            loadonce: true,
            editurl: "clientArray",
            caption: "Datos en las vistas",
            cellEdit: true,
            cellsubmit: 'clientArray'
        });
        $("#gridDatosVistasEmpresa").navGrid("#pagerDatosVistasEmpresa",
                {edit: false, add: false, del: false, search: false, refresh: false, view: false});
        $("#gridDatosVistasEmpresa").navButtonAdd("#pagerDatosVistasEmpresa", {
            caption: "Borrar filtros",
            title: "Borrar filtros",
            buttonicon: 'ui-icon-refresh',
            onClickButton: function () {
                jQuery("#gridDatosVistasEmpresa")[0].clearToolbar();
            }
        });
        $('#gridDatosVistasEmpresa').jqGrid('filterToolbar', {stringResult: true, searchOnEnter: false, autoSearch: false, defaultSearch: 'cn', ignoreCase: true});
        jQuery("#gridDatosVistasEmpresa").jqGrid('sortableRows', {
            update: function (e, ui) {
                reOrder('gridDatosVistasEmpresa', 'orden');
            }
        });

        //Buttons
        $("#btnAddVistasEmpresa").click(function () {
            openDiagVistasEmpresa("form-add-edit-vistasEmpresa", "add", "", "");
        });
        $("#btnDelVistasEmpresa").click(function () {
            var rowid = jQuery("#gridVistasEmpresa").jqGrid('getGridParam', 'selrow');
            if (rowid != null) {
                $.ajax({
                    url: "<?php echo $this->url('vistasempresas', array('action' => 'deleteGridItem')); ?>",
                    global: false,
                    type: "GET",
                    data: "id=" + rowid,
                    dataType: "json",
                    async: true,
                    success: function (result) {
                        gridReload('gridVistasEmpresa');
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        alert(xhr.status + " " + thrownError);
                    }
                });
            }
            else {
                msgAlert("diagAlertMain", "dataAlertMain", "Por favor seleccione una fila.");
            }
        });
        $("#btnEditVistasEmpresa").click(function () {
            var rowid = jQuery("#gridVistasEmpresa").jqGrid('getGridParam', 'selrow');
            if (rowid != null) {
                openDiagVistasEmpresa("form-add-edit-vistasEmpresa", "edit", "gridVistasEmpresa", rowid);
            }
            else {
                msgAlert("diagAlertMain", "dataAlertMain", "Por favor seleccione una fila.");
            }
        });

        //btnAddAllData =>>
        $("#btnAddAllData").click(function () {
            var dataGrid = jQuery("#gridPropiedadesEmpresa").jqGrid('getGridParam', 'data');
            if (dataGrid.length > 0) {
                for (var i = 0; i < dataGrid.length; i++) {
                    var ids = $("#gridDatosVistasEmpresa").jqGrid('getDataIDs');
                    ids = ids.toString();
                    ids = ids.split(",");

                    var data = {
                        "id": 0,
                        "propiedadId": dataGrid[i]['id'],
                        "propiedad": dataGrid[i]['descripcion'],
                        "tipo": dataGrid[i]['tipo'],
                        "formularioId": "",
                        "orden": (ids.length > 0 && ids[0] != 'undefined' && ids[0] != "") ? ids.length + 1 : 1,
                        "solo_lectura": "N"
                    };

                    if (ids.length > 0 && ids[0] != 'undefined' && ids[0] != "") {
                        $("#gridDatosVistasEmpresa").jqGrid('addRowData', parseInt(ids[ids.length - 1]) + 1, data);
                    } else {
                        $("#gridDatosVistasEmpresa").jqGrid('addRowData', 1, data);
                    }
                }
                deleteGrid('gridPropiedadesEmpresa');
            }
        });
        //btnAddSingleData >
        $("#btnAddSingleData").click(function () {
            var rowid = jQuery("#gridPropiedadesEmpresa").jqGrid('getGridParam', 'selrow');
            if (rowid != null) {
                var dataRow = $("#gridPropiedadesEmpresa").jqGrid('getRowData', rowid);
                var ids = $("#gridDatosVistasEmpresa").jqGrid('getDataIDs');
                ids = ids.toString();
                ids = ids.split(",");

                var data = {
                    "id": 0,
                    "propiedadId": dataRow['id'],
                    "propiedad": dataRow['descripcion'],
                    "tipo": dataRow['tipo'],
                    "formularioId": "",
                    "orden": (ids.length > 0 && ids[0] != 'undefined' && ids[0] != "") ? ids.length + 1 : 1,
                    "solo_lectura": "N"
                };

                if (ids.length > 0 && ids[0] != 'undefined' && ids[0] != "") {
                    $("#gridDatosVistasEmpresa").jqGrid('addRowData', ids.length + 1, data);
                } else {
                    $("#gridDatosVistasEmpresa").jqGrid('addRowData', 1, data);
                }
                $("#gridPropiedadesEmpresa").jqGrid('delRowData', rowid);
            }
            else {
                msgAlert("diagAlertModal", "dataAlertModal", "Por favor seleccione una fila.");
            }
        });
        //btnDelSingleData <
        $("#btnDelSingleData").click(function () {
            var rowid = jQuery("#gridDatosVistasEmpresa").jqGrid('getGridParam', 'selrow');
            if (rowid != null) {
                var dataRow = $("#gridDatosVistasEmpresa").jqGrid('getRowData', rowid);
                var data = {
                    "id": dataRow['propiedadId'],
                    "descripcion": dataRow['propiedad'],
                    "tipo": dataRow['tipo']
                };

                $("#gridPropiedadesEmpresa").jqGrid('addRowData', dataRow['propiedadId'], data);
                $("#gridDatosVistasEmpresa").jqGrid('delRowData', rowid);
                reOrder('gridDatosVistasEmpresa', 'orden');
                $("#gridPropiedadesEmpresa").setGridParam({datatype: 'local', sortname: 'id'}).trigger('reloadGrid');
            }
            else {
                msgAlert("diagAlertModal", "dataAlertModal", "Por favor seleccione una fila.");
            }
        });
        //btnDelAllData <<=
        $("#btnDelAllData").click(function () {
            var dataGrid = jQuery("#gridDatosVistasEmpresa").jqGrid('getGridParam', 'data');
            if (dataGrid.length > 0) {
                for (var i = 0; i < dataGrid.length; i++) {
                    var ids = $("#gridPropiedadesEmpresa").jqGrid('getDataIDs');
                    ids = ids.toString();
                    ids = ids.split(",");

                    var data = {
                        "id": dataGrid[i]['propiedadId'],
                        "descripcion": dataGrid[i]['propiedad'],
                        "tipo": dataGrid[i]['tipo']
                    };

                    if (ids.length > 0 && ids[0] != 'undefined' && ids[0] != "") {
                        $("#gridPropiedadesEmpresa").jqGrid('addRowData', parseInt(ids[ids.length - 1]) + 1, data);
                    } else {
                        $("#gridPropiedadesEmpresa").jqGrid('addRowData', 1, data);
                    }
                }
                $("#gridPropiedadesEmpresa").setGridParam({datatype: 'local', sortname: 'id'}).trigger('reloadGrid');
                deleteGrid('gridDatosVistasEmpresa');
            }
        });

        //Dialog addVistasEmpresa
        $("#form-add-edit-vistasEmpresa").dialog({
            autoOpen: false,
            resizable: true,
            draggable: true,
            closeOnEscape: false,
            modal: true,
            width: 'auto', //1000, 
            height: 'auto', //500,
            maxWidth: 1200,
            open: function (event, ui) {
                $(event.target).parent().css('position', 'fixed');
                $(event.target).parent().css('top', '110px');
                $(event.target).parent().css('left', '275px');
            },
            buttons: {
                'Aceptar': function () {
                    if ($("#valid-form-add-edit-vistasEmpresa").valid()) {
                        var descripcion = $("#descripcionAddEditVistasEmpresa").val();
                        var extranet = $("#extranetAddEditVistasEmpresa").val();

                        var ids = $("#gridVistasEmpresa").jqGrid('getDataIDs');
                        ids = ids.toString();
                        ids = ids.split(",");

                        var e = 0;
                        var rowid = "";

                        if (oEdit) {
                            rowid = jQuery("#gridVistasEmpresa").jqGrid('getGridParam', 'selrow');
                            if (rowid != null) {
                                if (ids != "") {
                                    for (var i = 0; i < ids.length; i++) {
                                        var data = $("#gridVistasEmpresa").jqGrid('getRowData', ids[i]);
                                        if (data['id'] != rowid) {
                                            if (data['descripcion'].toLowerCase() == descripcion.toLowerCase()) {
                                                e++;
                                            }
                                        }
                                    }
                                }
                            } else {
                                msgAlert("diagAlertMain", "dataAlertMain", "Por favor seleccione una fila.");
                            }
                        } else {
                            if (ids != "") {
                                for (var i = 0; i < ids.length; i++) {
                                    var data = $("#gridVistasEmpresa").jqGrid('getRowData', ids[i]);
                                    if (data['descripcion'].toLowerCase() == descripcion.toLowerCase()) {
                                        e++;
                                    }
                                }
                            }
                        }
                        if (e == 0) {
                            var dataGridDatosVistas = jQuery("#gridDatosVistasEmpresa").jqGrid('getGridParam', 'data');
                            if (dataGridDatosVistas.length > 0) {
                                var data = {
                                    "id": rowid,
                                    "descripcion": descripcion,
                                    "extranet_permitido": extranet,
                                    "vistas_propiedades": dataGridDatosVistas
                                };
                                $.ajax({
                                    url: "<?php echo $this->url('vistasempresas', array('action' => 'editGridItem')); ?>",
                                    global: false,
                                    type: "POST",
                                    data: "data=" + JSON.stringify(data),
                                    dataType: "json",
                                    async: true,
                                    success: function (result) {
                                        gridReload('gridVistasEmpresa');
                                        $("#form-add-edit-vistasEmpresa").dialog('close');
                                    },
                                    error: function (xhr, ajaxOptions, thrownError) {
                                        alert(xhr.status + " " + thrownError);
                                    }
                                });
                            } else {
                                msgAlert("diagAlertModal", "dataAlertModal", "No ha agregado datos para la vista.");
                            }
                        } else {
                            msgAlert("diagAlertModal", "dataAlertModal", "Ya existe un registro con esa combinacion.");
                        }
                    }
                },
                'Cancelar': function () {
                    deleteGrid('gridPropiedadesEmpresa');
                    deleteGrid('gridDatosVistasEmpresa');
                    validFormAddEditVistasEmpresa.resetForm();
                    $(this).dialog('close');
                }
            },
            close: function () {
                deleteGrid('gridPropiedadesEmpresa');
                deleteGrid('gridDatosVistasEmpresa');
                validFormAddEditVistasEmpresa.resetForm();
            }
        });

        //Validation
        var validFormAddEditVistasEmpresa = $("#valid-form-add-edit-vistasEmpresa").validate({
            rules: {
                descripcionAddEditVistasEmpresa: {required: true}
            }
        });

        //AlertManager
        $('#diagAlertMain').on('closed.bs.alert', function () {
            $('.dataAlertMain').html("");
        });
        $('#diagAlertModal').on('closed.bs.alert', function () {
            $('.dataAlertModal').html("");
        });
    });

    // remove window resize namespace
    $(document).on("dialogclose", ".ui-dialog", function (event, ui) {
        $(window).off("resize.responsive");
    });

    function gridReload(gridName) {
        $("#" + gridName).setGridParam({datatype: 'json'})/*.setGridParam({rowNum: 1000})*/.trigger('reloadGrid');
    }

    function openDiagVistasEmpresa(diagName, op, grid, id) {
        clearDataVistasEmpresa();
        if (op == "edit") {
            var rowdata = jQuery("#" + grid).getRowData(id);
            $('#descripcionAddEditVistasEmpresa').val(rowdata['descripcion']);
            $('#extranetAddEditVistasEmpresa').val(rowdata['extranet_permitido']);
            $('#' + diagName).dialog("option", "title", "Editar registro");
            $('#' + diagName).dialog('open');
            $('#' + diagName).dialog('moveToTop');
            loadGrid("gridPropiedadesEmpresa", rowdata['id']);
            loadGrid("gridDatosVistasEmpresa", rowdata['id']);
            oEdit = true;
        } else {
            $('#' + diagName).dialog("option", "title", "Agregar registro");
            $('#' + diagName).dialog('open');
            $('#' + diagName).dialog('moveToTop');
            $('#extranetAddEditVistasEmpresa option:contains("C")').prop('selected', true);
            loadGrid("gridPropiedadesEmpresa");
            loadGrid("gridDatosVistasEmpresa");
            oEdit = false;
        }
    }

    function clearDataVistasEmpresa() {
        $('#descripcionAddEditVistasEmpresa').val("");
    }

    function msgAlert(diagName, selectorName, msg) {
        $('#' + diagName).show();
        $('.' + selectorName).html(msg);
        setTimeout(function () {
            $('#' + diagName).hide("drop", {direction: "up"}, "slow");
            $('.' + selectorName).html("");
        }, 3000);
        return;
    }

    function loadGrid(gridName, rowid) {
        switch (gridName) {
            case 'gridPropiedadesEmpresa':
                $.ajax({
                    url: "<?php echo $this->url('vistasempresas', array('action' => 'loadPropGrid')); ?>",
                    global: false,
                    type: "GET",
                    data: "id=" + rowid,
                    dataType: "json",
                    async: true,
                    success: function (result) {
                        deleteGrid('gridPropiedadesEmpresa');
                        if (result.data.length > 0) {
                            for (var i = 0; i < result.data.length; i++) {
                                var dataLocal = {
                                    "id": result.data[i][0],
                                    "descripcion": result.data[i][1],
                                    "tipo": result.data[i][2]
                                };
                                var ids = jQuery("#gridPropiedadesEmpresa").jqGrid('getDataIDs');
                                ids = ids.toString();

                                ids = ids.split(",");
                                if (ids.length > 0 && ids[0] != 'undefined' && ids[0] != "") {
                                    $("#gridPropiedadesEmpresa").jqGrid('addRowData', ids.length + 1, dataLocal);
                                } else {
                                    $("#gridPropiedadesEmpresa").jqGrid('addRowData', 1, dataLocal);
                                }
                            }
                        }
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        alert(xhr.status + " " + thrownError);
                    }
                });
                break;
            case 'gridDatosVistasEmpresa':
                $.ajax({
                    url: "<?php echo $this->url('vistasempresas', array('action' => 'loadDataGrid')); ?>",
                    global: false,
                    type: "GET",
                    data: "id=" + rowid,
                    dataType: "json",
                    async: true,
                    success: function (result) {
                        deleteGrid('gridDatosVistasEmpresa');
                        if (result.data.length > 0) {
                            for (var i = 0; i < result.data.length; i++) {
                                var dataLocal = {
                                    "id": result.data[i][0],
                                    "propiedadId": result.data[i][1],
                                    "propiedad": result.data[i][2],
                                    "tipo": result.data[i][3],
                                    "formularioId": result.data[i][4],
                                    "orden": result.data[i][5],
                                    "solo_lectura": result.data[i][6]
                                };
                                var ids = jQuery("#gridDatosVistasEmpresa").jqGrid('getDataIDs');
                                ids = ids.toString();

                                ids = ids.split(",");
                                if (ids.length > 0 && ids[0] != 'undefined' && ids[0] != "") {
                                    $("#gridDatosVistasEmpresa").jqGrid('addRowData', ids.length + 1, dataLocal);
                                } else {
                                    $("#gridDatosVistasEmpresa").jqGrid('addRowData', 1, dataLocal);
                                }
                            }
                        }
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        alert(xhr.status + " " + thrownError);
                    }
                });
                break;
        }
    }

    function deleteGrid(gridName) {
        var $table;
        $table = $('#' + gridName);

        var ids = $table.jqGrid('getDataIDs');
        ids = ids.toString();
        ids = ids.split(",");
        if (ids.length > 0) {
            for (var i = 0; i < ids.length; i++) {
                $table.delRowData(ids[i]);
            }
        }
        $table.clearGridData(true).trigger("reloadGrid");
    }

    function reOrder(gridName, sortField) {
        var ids = $("#" + gridName).jqGrid('getDataIDs');
        ids = ids.toString();
        ids = ids.split(",");

        var orden = 1;

        if (ids != "") {
            for (var i = 0; i < ids.length; i++) {
                jQuery('#' + gridName).setCell(ids[i], sortField, orden);
                orden++;
            }
        }
    }

</script>

<!-- Dialogo form-add-edit-vistasEmpresa -->
<div id="form-add-edit-vistasEmpresa" class="container-fluid" title="" >
    <form class="form-horizontal" id="valid-form-add-edit-vistasEmpresa" role="form">
        <div class="row">
            <div class="form-group col-xs-2 col-md-4">
                <label for="descripcionAddEditVistasEmpresa" class="col-sm-4 control-label">Vista:</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="descripcionAddEditVistasEmpresa" name="descripcionAddEditVistasEmpresa" placeholder="">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-xs-2 col-md-4">
                <label for="extranetAddEditVistasEmpresa" class="col-sm-4 control-label">Extranet:</label>
                <div class="col-sm-8">
                    <select class="form-control" id="extranetAddEditVistasEmpresa" name="extranetAddEditVistasEmpresa">
                        <option value="S">Si</option>
                        <option value="N">No</option>
                    </select>
                </div>
            </div>
        </div>
    </form>
    <div class="row">
        <div class="col-xs-6 col-sm-6">
            <div id="jqGridPropiedadesEmpresa" style="padding-top:10px;">
                <table id="gridPropiedadesEmpresa"></table>
                <div id="pagerPropiedadesEmpresa"></div>
            </div>
        </div>
        <div class="col-xs-6 col-sm-1">
            <div class="btn-group-vertical" role="group" style="padding-top:70px; padding-left:10px;">
                <button type="button" class="btn btn-info btn-xs" id="btnAddAllData">
                    <span class="glyphicon glyphicon-forward" aria-hidden="true"></span>
                </button>
                <button type="button" class="btn btn-info btn-xs" id="btnAddSingleData">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                </button>
                <button type="button" class="btn btn-info btn-xs" id="btnDelSingleData">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                </button>
                <button type="button" class="btn btn-info btn-xs" id="btnDelAllData">
                    <span class="glyphicon glyphicon-backward" aria-hidden="true"></span>
                </button>
            </div>
        </div>
        <div class="col-xs-6 col-sm-5">
            <div id="jqGridDatosVistasEmpresa" style="padding-top:10px;">
                <table id="gridDatosVistasEmpresa"></table>
                <div id="pagerDatosVistasEmpresa"></div>
            </div>
        </div>
    </div>
    <div class="alert alert-warning ui-state-highlight ui-corner-all" id="diagAlertModal">
        <a href="#" class="close" data-dismiss="alert">&times;</a>
        <strong><span class="dataAlertModal"></span></strong>
    </div>
</div>